### ISSUE TITLE
Fichier INI

### ISSUE THREAD

**Issue by matthieuy** [Universal-Rom-Tools/Universal-XML-Scraper#1]
Le fichier ini est écrasé à chaque lancement du script, du coup je dois refaire toute la configuration des chemins à chaque fois. (la partie `LAST_USE` du fichier)

Note : sous Recalbox v4 : Le chemin est `\\RECALBOX\share\roms\...` et non `\\RECALBOX\User data`

**Comment by Universal-Rom-Tools** [comment]
En toute logique, le fichier ini n'est "écrasé" que dans le cas d'une nouvelle version (parce que des modifications peuvent avoir lieu sur les profils d'une version à l'autre)

Tu me confirme que tu as la dernière version et que tout au début du fichier tu as bien le tag suivant : 

```
[GENERAL]
$verINI	= '1.0.0.8'
```

Si ce n'est pas le cas, ajoute le ;) (mais normalement, si tu as la dernière version, il devrait l'ajouter tout seul après avoir mis à jour ton fichier ini.)


Merci pour les paths, je vais vérifier ;) et corriger dès que j'ai 5 minutes ;)
