### ISSUE TITLE
Add tabulation to gamelist.xml for better readability

### ISSUE THREAD

**Issue by paradadf** [Universal-Rom-Tools/Universal-XML-Scraper#10]
A picture is worth a thousand words...

Currently:
![coding_style_notab](https://cloud.githubusercontent.com/assets/15956550/17644407/1265933e-6186-11e6-8c57-1eb1dc494130.png)

With tabs (from my old scraps):
![coding_style_tab](https://cloud.githubusercontent.com/assets/15956550/17644408/2088f56e-6186-11e6-882c-f993d4155c02.png)

**Comment by Universal-Rom-Tools** [comment]
Yep, I know...

But It's in the buildin function I use...
Need to change these function, but that need's a lot of work ^^

I put that on My to do list

**Comment by Universal-Rom-Tools** [comment]
Last version 1.5.0.6 have a Tidy function ;)

Normally your XML File must be indented
