### ISSUE TITLE
Error Connecting to Database

### ISSUE THREAD

**Issue by slydisciple** [Universal-Rom-Tools/Universal-XML-Scraper#100]
![error](https://cloud.githubusercontent.com/assets/24701204/21490610/c3a5447e-cbbb-11e6-92db-4f273a603501.PNG)

See image above.  Son restarted my computer with a hard restart.  No matter how many times I reinstall the program, restart the computer, flush the registry, reconnect to the network, this is the error I get when opening the program.  Please help.

**Comment by willz173** [comment]
Same thing is happening to me. I'm pretty sure it just means there working on the servers. You just gotta wait it out and hopefully they'll be back up soon.

**Comment by slydisciple** [comment]
Sweet.  If thats the problem, I totally understand.  Would be nice to know when maintenance windows are occurring.   Just in case, here is the log file.  
[log.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/673580/log.txt)

**Comment by peterpan123123** [comment]
Was announced 23h ago.
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/issues/97

**Comment by slydisciple** [comment]
Derp.  Thanks peter.  I guess I should be more diligent.

**Comment by Universal-Rom-Tools** [comment]
Need to be a little more patient ;)

New Server is very near to be up ;)

**Comment by Universal-Rom-Tools** [comment]
Nomally OK now
no news in 8 days...  I close the issue
