### ISSUE TITLE
MAME Scraping

### ISSUE THREAD

**Issue by slydisciple** [Universal-Rom-Tools/Universal-XML-Scraper#101]
As many of you know, MAME games come in zip files.  When scraping MAME roms, it seems as if the scraper is going inside of the games zip file and scanning every individual file within the zip file.  Is this necessary?  It takes a very long time doing it this way, and seems unnecessary unless there is a benefit I am not understanding.  Thanks.

**Comment by Universal-Rom-Tools** [comment]
Normally, UXS unzip file "only" if he doesn't found a match by hash or by romfilename.

So it's just because server isn't up yet you have strange thing.

normally all will be OK very soon ;)

**Comment by giventofly** [comment]
I'm having some problems with mame, usually it would hit every game (almost all) now i've done some Mixtemplate alterations and was updating the arcade folder, and now its selecting all the wrong games (and hashinf inside the .zip) and reinstalled the uxs to check if it could be some option i've changed but even with stock configurations the same pattern happens even when before it worked great.

want to open a new issue?

**Comment by MartinStell** [comment]
I have the same problem.

**Comment by tifsmo** [comment]
same issue here. also it takes forever for every single game.

**Comment by Universal-Rom-Tools** [comment]
See #108 

Normally it's ok now.. It was an API problem and it was corrected yesterday.

**Comment by Universal-Rom-Tools** [comment]
Done
