### ISSUE TITLE
2.1.0.0 SSH?

### ISSUE THREAD

**Issue by giallone1970** [Universal-Rom-Tools/Universal-XML-Scraper#103]
with latest version, i can setup my options but when i go to issue an SSH command (stop emustation) nothing happens and then, every command i try to selct after gives no asnwer (nothing happens)
if i choose scrape then answer "yes" to request about stopping emu station, nothing happens and all menu commands are not respoinmsive (i have to close program with task manager then)

ADD:
program also stucks tinkering with options (is related to website updates going on?)
currently is unusable for me....

both with 64bit and normal version

**Comment by scrumpydaniel** [comment]
This is the same with me now. Think it may be due to the updates their doing.

**Comment by trutrax** [comment]
same issue here and the http://www.screenscraper.fr/ website seems to be up again. Might an an issue with the most recent release...

**Comment by MartinStell** [comment]
Program does not work for me either.  I tried the old versions too.  It was a great program when it worked.  I hope it can eventually be fixed.

**Comment by Zuberi81** [comment]
Hi, I'm new and I was wondering if I was doing something wrong, but I have this same issue. I'm using the latest version 2.1.0.0

**Comment by neogeronimo** [comment]
We were changing the servers
Now it's stable.
By the way, it seems like there are some problems with the last issue of UXS

**Comment by hellbillie** [comment]
The SSH command is not working as of 12/30/16 with the latest version 2.1.0.0 on all the log files for USX it ends with "SSH : killall emulationstation" then the program pretty much stops responding and emulation station does not shut down.

**Comment by Universal-Rom-Tools** [comment]
At least the 2.1.0.1 will work..

**Comment by Universal-Rom-Tools** [comment]
Normally Solved.
I close the issue
