### ISSUE TITLE
Problem dowloading 2D box

### ISSUE THREAD

**Issue by grahamshandor** [Universal-Rom-Tools/Universal-XML-Scraper#104]
Hello,

I have a porblem. I wish to only Scrap 2D box or Wheels for my games, but only screenshot work? Do you know why? SHould i just wait (website under maintenance) or is it a bug?

Thank you.

**Comment by Universal-Rom-Tools** [comment]
Corrected in 2.1.0.1 ;)

**Comment by grahamshandor** [comment]
Thank you very much. You're doing a great job!
