### ISSUE TITLE
Hashing on the pi, filename problem

### ISSUE THREAD

**Issue by giventofly** [Universal-Rom-Tools/Universal-XML-Scraper#105]
Hi,

i was hashing on the pi and noticed a small problem (was taking too long) checked the game, and noticed that games with ' on the name crash. have to escape the file.

and killed the process of the hashing and it continued for the rest, was hung probably waiting for a return that didn't happened.

http://imgur.com/a/EAoDc

btw, can the option to do the hashing on the pi be added somewhere in the menu? or define for x system? i can't do the scrape all systems because dreamcast and psx need to do the hash on the pi. i have to do one by one, then change the hash on the pi and do dreamcast+psx.

thank you.

**Comment by giventofly** [comment]
checked now a game with ' and it did well, don't know if it was related with the long name or ' + spaces or just some random crash (but did happen with 2 games in a row with the ' so i thought that was the cause).

**Comment by Universal-Rom-Tools** [comment]
I need to add the / before the '...

I'll do that in the next version ;)

**Comment by Universal-Rom-Tools** [comment]
done in the 2.1.0.2
