### ISSUE TITLE
[sugestion] Add select rom name from list when not found

### ISSUE THREAD

**Issue by giventofly** [Universal-Rom-Tools/Universal-XML-Scraper#107]
could there be a way to give options to select a rom when its not found? similar to ES scrapper, or in alternative add the link from screenscrapper.fr.

something like this in the missing_gamelist :
rom name.ext screenscrapper.fr/link

Because for some roms the rom info is there but for some reason nor the hashing or filename gives the result

**Comment by Universal-Rom-Tools** [comment]
link or name is impossible. The API don't work this way...

But maybe a Hash ;) I think about it ;)

**Comment by giventofly** [comment]
but the hash is already the way its working, do the api give a list of results?

**Comment by Universal-Rom-Tools** [comment]
The Idea is when you have a missing.txt file, check Screenscraper if the game exist, and found a Hash of a rom.
Add this new Hash to the missing file and rescrape using the missing file new hash...

It's way to be perfect. The best way is to send us you hash to add them to the DB ;)

**Comment by giventofly** [comment]
Oh, never thought of adding my hash to screenscrapper, tought it should be done by some admin.

can you give me a quick steps on how to add hashfiles to screenscrapper? i will gladly add all of my missing results there :)

**Comment by Universal-Rom-Tools** [comment]
juste send me you missing file ;) (or pastebin them ;) )

I'm an admin and can add them ;)

**Comment by giventofly** [comment]
[_Dreamcast_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/679758/_Dreamcast_missing.txt)
[_Game Boy Advance_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/679759/_Game.Boy.Advance_missing.txt)
[_Megadrive_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/679763/_Megadrive_missing.txt)
[_Neo-Geo Pocket Color_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/679761/_Neo-Geo.Pocket.Color_missing.txt)
[_NES_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/679760/_NES_missing.txt)
[_Nintendo 64_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/679762/_Nintendo.64_missing.txt)
[_Playstation_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/679764/_Playstation_missing.txt)
[_Super Nintendo_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/679765/_Super.Nintendo_missing.txt)

these are my missing roms.

thank you, some of the dreamcast and psx are missing because of the ' on the filename, at this moment i'm kind of busy doing some java codding but later will give it a better look and give something that is missing (will wait until you update the dreamcast and psx hashes).

thank you a lot, in the future, can i contact again to add missing hashes?

**Comment by giventofly** [comment]
did you had the time to add those hashes?

**Comment by Universal-Rom-Tools** [comment]
Sorry I completely forgot you message ><

So I just did it : 

Some are autoassociated.
Some are already in DB (but mayby orpheans.. So you need to associate them to the good game)
Some are just added to the DB (So they are orphens and they need a manual association you can do on the web site)

BUT.

I canno't import Dreamcast, Playstation, and supernintendo... CRC32 are missing in the file (it's normal on "big" file, I don't calculate them to win some time on scrape).

Can you use F-CRC Calcultor ( http://ffulgore.free.fr/site/f-crc/us/download.htm ) ?

Just dl it, launch it, drag and drop your missing rom in it.
Check the CRC and MD5 check box.
Launch the calculation.
And send me the report ;) (it normally have the same format as the missing file...)

Thank you.

**Comment by giventofly** [comment]
I don't have windows to do that, but will do the crc32 on the dreamcast, ps1 and snes that are missing, you need crc or crc32? (i guess i will do both :) ).

when i'm at home i will put here the list.

regarding the orphans and such, how can i associate and know what are the ones missing? i find the screenscrapper.fr site kind of hard to deal with in terms of intuitivity design. but if you gave me some pointers i would gladly associate the games with the hash.

**Comment by Universal-Rom-Tools** [comment]
??? How do you use Universal XML Scraper if you don't have windows ???

To associate orphean it's pretty simple : 
Register to : http://www.screenscraper.fr/
Login
Choose your language (small flag in the upper right corner)
Go to "Rom" / "Your system"
Select "show only orphean"
found the orphean rom you want to associate.
Now 3 possibilities : 
In the first listing you have the matching game, choose it and submit
if not, in the second listing (full plateform game lisintg) you have a matching game, choose it and submit
if not, the game may not exist, simply check : "NEW GAME" put the good name (not always the same as the rom) add a "source" to help moderator validate your proposal. And submit ;)

**Comment by giventofly** [comment]
Sorry, what i meant was, i don't the roms easily available on windows, have to transfer many GB over the network, its easier to do the hashings on the pi for me in those cases. But i will check how i can get the hashes better.

All right, will try to check what i can do today :) thank you

**Comment by Universal-Rom-Tools** [comment]
just try http://ffulgore.free.fr/site/f-crc/us/download.htm ;) you can Hash from a network drive ;)
And you will be sure the output file will be correct to import them ;)

**Comment by giventofly** [comment]
Took some time, but here they are.

if i need to do something else, just let me know, thank you.

[_PSP_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/735492/_PSP_missing.txt)
[_Saturn_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/735490/_Saturn_missing.txt)
[_Dreamcast_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/735493/_Dreamcast_missing.txt)
[_Mega-CD_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/735491/_Mega-CD_missing.txt)
[_Playstation_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/735489/_Playstation_missing.txt)

**Comment by giventofly** [comment]
any feedback?

**Comment by Universal-Rom-Tools** [comment]
Totally forgot to say it's done ><

(long time ago :S )

But now there is some new orphean rom who want an association to the matching game ;)
