### ISSUE TITLE
Rating not retreived from screensrapper

### ISSUE THREAD

**Issue by shoblingr** [Universal-Rom-Tools/Universal-XML-Scraper#109]
Hi,

I scrapped some gba roms chere there was ratings on screescrapper.fr (eg plateforme=12&gameid=3776).
Using UXS tool, no rating is retrieved. After some basics checks with fiddler, it seems the api/jeuInfos.php do not return the rating value.
Do you confirm the bug ?

Thanks and regards,
Stef

**Comment by tifsmo** [comment]
its not only gba roms. i did a fresh install and no system i scraped has any ratings

**Comment by Universal-Rom-Tools** [comment]
I pass that to the Screenscraper Dev ;)

**Comment by shoblingr** [comment]
It is fixed now, thanks!

**Comment by Universal-Rom-Tools** [comment]
Great ;) I close the Issue
