### ISSUE TITLE
Every ROM release date says "unknown"

### ISSUE THREAD

**Issue by jrlepage** [Universal-Rom-Tools/Universal-XML-Scraper#110]
When I scrape using the latest version, for every ROM on every system it says "unknown" instead of the game release date in the metadata. This is true even when it gets the artwork and other metadata properly.

**Comment by devilbubull** [comment]
same issue

**Comment by jrlepage** [comment]
Sorry forgot to mention - this was an issue for me on Win 10 x64.

**Comment by jrlepage** [comment]
Note: This is also true when using sselph scraper and specifying screensrcraper.fr as the source. Sounds like a server issue... Anyone find a workaround for this?

**Comment by jrlepage** [comment]
I guess this may be more of a theme-specific issue. In Pixel theme it's not a problem. In Carbon, it's annoying because a bunch of ROMS have "unknown" in their metadata.

**Comment by Universal-Rom-Tools** [comment]
Very strange problem... There is no "unknown" in my code... 

So can you check your gamelist.xml file to see if there is really unknown as name ?

If not, maybe there is a problem with your theme...

**Comment by jrlepage** [comment]
It looks like a theme problem never mind!
