### ISSUE TITLE
Windows Vista - can not start version greater 2.0.0.0

### ISSUE THREAD

**Issue by pelztier3011** [Universal-Rom-Tools/Universal-XML-Scraper#111]
Error is:
---------------------------
Fehler
---------------------------
In Universal XML Scraper ist ein Problem aufgetreten !

(err_SystemList)
---------------------------
OK   
---------------------------

**Comment by krazynez** [comment]
Same here but i'm on windows 10.

Every time I open UXS it says Universal XML Scraper fatal error ! (err_SystemList)
d
http://pastebin.com/y0euNLGd

**Comment by jrlepage** [comment]
Same issue in Windows 10. Just started this morning...

**Comment by SpaceSocks** [comment]
must be server side. allot of people having same issue.

**Comment by Universal-Rom-Tools** [comment]
See here : #
