### ISSUE TITLE
Universal XML Scraper fatal error! (err_SystemList)

### ISSUE THREAD

**Issue by SpaceSocks** [Universal-Rom-Tools/Universal-XML-Scraper#114]
Getting this error when I try to launch the scraper. Before going to bed last night I selected to Scrape all systems. When I got up It stopped after only about 1/3 of my systems. I exited the program and when tried to restart got that error. So I thought something on my RetroPie SD card was messed up. I decided to format the SD Card and re-image again with RetroPie 4.1. I even deleted my copy of Universal XML Scraper and re-downloaded latest build and I still get the error when I launch the program. I cant even get into the program. Someone please help?

![xml](https://cloud.githubusercontent.com/assets/24867255/21583256/84fe0526-d03e-11e6-9419-8a0ca444125e.JPG)

**Comment by raulromanp** [comment]
Same problem

**Comment by slydisciple** [comment]
Bump.  Here is the log file.  I would like to financially support the tool, but I have not been able to use it appropriately since trying it (about the last 9 days).  Love the concept and hope these bugs get flushed out.

[log.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/680301/log.txt)

**Comment by bshank2324** [comment]
This error developed half way through a scrape for me as well with current version.  I got the same error message with version 2.1.0.0 but when I tried version 2.0.0.9, the error message changed to "Problem connecting to the database."  I did have several successful scrapes with the current version prior to it failing leading me to believe it is server side.  This is an awesome scraper so I will wait until those much smarter than me make the magic pixies dance again.  Much thanks for a wonderful product!

**Comment by goalkeepr** [comment]
They changed the dev password on screenscraper.fr - that's the problem.

**Comment by raulromanp** [comment]
Now the error doesn't appear but the scrapper doesn't find roms. All missing :(

**Comment by Universal-Rom-Tools** [comment]
Normally all is working well now.

Can you keep me up to date to know if I can close this issue ?

Thank you

**Comment by bshank2324** [comment]
seems to be working fine for me now

**Comment by Universal-Rom-Tools** [comment]
oki ;) I close the issue.

thanks ;)

**Comment by redriche** [comment]
happening again?
