### ISSUE TITLE
Hashing

### ISSUE THREAD

**Issue by whyttygr3326** [Universal-Rom-Tools/Universal-XML-Scraper#116]
Using the newest version. Whenever I go to scrape. At the bottom is says hashing but flies through the games with no images showing up. Is anyone else having this problem?

**Comment by tsarrack** [comment]
Yeah. I'm having the same problem right now.

**Comment by hulk7999** [comment]
Im pretty sure we are all going through the same stuff. It seems like its server side. They seem to have fixed the connection issue now it seems like none of the images are transferring over during the download. I tried 2 small directories I had and it deleted my old scrapes and left them blank.

**Comment by SpaceSocks** [comment]
yep having this problem as well

**Comment by SpaceSocks** [comment]
reimaged my SD card freash RetroPie and just installed my Atari 7800 Roms.. tried to Scrape again with RetrioPie Mixed and same results.. 

[](http://puu.sh/t8YkI/707281d97d.png)

**Comment by SpaceSocks** [comment]
If you register on the website it will work / stop just hashing. 

http://www.screenscraper.fr/

**Comment by tsarrack** [comment]
It's working again for me, no need to register on the screenscraper site.

**Comment by SpaceSocks** [comment]
weird. ok i guess not ! lol..

**Comment by Universal-Rom-Tools** [comment]
As said in #97 we experienced som instability with the new server...

Can you try again and keep me up to date ?

Thank you

**Comment by whyttygr3326** [comment]
I registered on the screenscraper website. Never received an email to confirm stil waiting on that.

I had some free time to test again and it seems to be working great. Thanks

**Comment by Universal-Rom-Tools** [comment]
@whyttygr3326 I'll pass that on the main admin ;) ( whyttygr3326 is the pseudo you use to register on Screenscraper ? )

So I close the Issue ;) (seems to be ok)

**Comment by whyttygr3326** [comment]
Yes whyttygr3326 is the username I used to register. Never received a confirmation email.
