### ISSUE TITLE
Only downloads some images

### ISSUE THREAD

**Issue by Brandoskey** [Universal-Rom-Tools/Universal-XML-Scraper#117]
When scraping roms it finds all my roms and seems to scrape everything except it only gets maybe 1/4 of the images. I've tried the same set of nes roms multiple times and it gets the images for the same 270 out of 966 images each time.

I'm currently running it in pictures only mode and it appears to be getting all the images now.

**Comment by krazynez** [comment]
I've had that same problembefore as well. Im using the RetroPie (video) I've had to do the RetroPie (mix) then check the folders that got scraped and make sure the right files and folders are In there. Then rescrape with the retropie (video) and it worked. It might just be luck but seems the only way to get it to work for myself so far.

**Comment by Brandoskey** [comment]
It's possible it's user error as I'm new to using this scraper, but it seems odd how consistently it downloaded only certain images.

**Comment by Universal-Rom-Tools** [comment]
As said in #97 
We experienced some instabilty since the migration.
Normally, we are near back to "normal" (even better than before with the new server ;) )

So can you retry and keep me up to date ?

**Comment by Brandoskey** [comment]
All seems to be working now. It's grabbing pictures for everything with a normal scrape.
