### ISSUE TITLE
Changing picture extension doesn't work

### ISSUE THREAD

**Issue by Brandoskey** [Universal-Rom-Tools/Universal-XML-Scraper#119]
Changing the pictures extension in pictures configuration seems to have no effect.

**Comment by Universal-Rom-Tools** [comment]
Hi Brandoskey,

Extension change work only on "non MIX" profil.

MIX need png to keep transparency. So changing in jpg work only on "single" picture (like screenshot or 2D/3D box)

**Comment by Brandoskey** [comment]
That makes sense
