### ISSUE TITLE
No downloaded images in version 1.5.0.10

### ISSUE THREAD

**Issue by DickyBR** [Universal-Rom-Tools/Universal-XML-Scraper#12]
![sem titulo](https://cloud.githubusercontent.com/assets/21045826/17679807/822e1784-6313-11e6-8bc8-be86b0b7be5e.png)
Dear Screech

I'm using EmulationStation in Windows, and the Scrapper found roms and descriptions, but dont downloaded images of games, instead of this it just adds the image address on the site ScreenScrappers in the image tag.
Like
"http://www.screenscraper.fr/api/mediaJeu.php?devid=xxx&devpassword=xxx&softname=UniversalXMLScraperV1.5.0.10&crc=&md5=&sha1=&systemeid=6&jeuid=37356&media=ss&mediaformat=png"

**Comment by Universal-Rom-Tools** [comment]
Wich Profil do you use ?
Do you use some Mix Profil ?

Try using **Screenscraper-RecalboxV4** as profil ;) normally it's compatible ;)

**Comment by DickyBR** [comment]
Ok... starting download, but only gamaplay images, how to download the covers of games?

**Comment by Universal-Rom-Tools** [comment]
Default profil is Screenshot, you can change it replacing a line in UXS-Config.ini

You can found some explaination (in french sorry, I need to rewrote it :S ) here :  https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/wiki/Changer-le-type-d%27image-t%C3%A9l%C3%A9charg%C3%A9e

In your case just invert these to line (55 & 56) : 
```
$ELEMENT_11 	= 'image|path:image|medias/media_screenshot|path:image'
$ELEMENT_12 	= 'image|path:image|medias/media_boxs/media_boxs2d/media_box2d_%%|path:image'
```

To

```
$ELEMENT_11 	= 'image|path:image|medias/media_boxs/media_boxs2d/media_box2d_%%|path:image'
$ELEMENT_12 	= 'image|path:image|medias/media_screenshot|path:image'
```

So it will download 2D cover and if no media found, the screenshot ;)

(Replace the 2D by 3D if you want it in 3D )

Or you can use **Screenscraper[MIX]-RecalboxV4** instead ;) with nice composition ;)

like :  
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/raw/master/Images/sf2ce-image.png
Or even better with the theme DarKade Modified : 
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/raw/master/Images/SNES%20-SF2.jpg

If you want more explaination don't hesitate to ask ;)

**Comment by DickyBR** [comment]
Great my dear friend... congrats for your work... 
I'm really enjoying it ;)

**Comment by Universal-Rom-Tools** [comment]
Thank you for using it ;)

I close the Issue
