### ISSUE TITLE
Deleted My Entire MAME Romset then Crashed

### ISSUE THREAD

**Issue by AlmtyBob** [Universal-Rom-Tools/Universal-XML-Scraper#120]
Version 2.1.0.0 - RetroPie MIX profile

I had a set of ROMs stored locally on my PC in folder: E:\Torrents\MAME2003_Reference_Set_MAME0.78_ROMs_CHDs_Samples\roms\

In Path Configuration I changed all 3 entries in the Scraper section to that above path.  Created a folder named "pics" in that same path then made changed both Pictures paths to the pics path.  Clicked scrape.  While it was scraping I noticed that my ROMs folder was now empty except the CHD folders.  Waited for it to finish scraping about 40 minutes later and right after the last ROM it crashed with an AutoIt error that I think was an array index error.  Now all of my ROMs are completely gone.  I searched every drive I have for a few ROM names I know I had and the only thing I found was one empty folder in C:\users\<myusername>\AppData\Local\Temp\ for each ROM that I used to have with folder names like UXS_ZIP_Temp_<RomNameHere>.

Also that intro sound is absolutely terrible and please don't make your popup windows modal across all of Windows.

**Comment by Universal-Rom-Tools** [comment]
Woot >< You are really almighty ^^ 

More than 19000 UXS download and near 2 000 000 request a day, and you are the first one who "loose" something.

I think you do something wrong with you path...

Can you explain me what you did with path ?

**Comment by Universal-Rom-Tools** [comment]
this is the problem : 
"XML file path"
E:\Torrents\MAME2003_Reference_Set_MAME0.78_ROMs_CHDs_Samples\roms

you MUST put the gamelist.xml path ;)
so : 
"XML file path"
E:\Torrents\MAME2003_Reference_Set_MAME0.78_ROMs_CHDs_Samples\roms**\gamelist.xml**

but, why don't you use the "autoconfiguration" ?

Make a "ROM" Folder with 1 subfolder for each system (like MAME, Snes, Mastersystem, ...)
Put your rom in the corresponding folder
Then Launch the Wizard
choose a [Rom Folder] profil
And simply put the path to your main Rom Folder (aka : your new ROM folder)
So when you go to Scrape menu, choose the system you want to scrape  (like MAME, Snes, Mastersystem, ...)
And Scrape.... UXS will "autoconfigure" all your path ;)

**Comment by AlmtyBob** [comment]
I simply wanted to scrape info for a local folder of ROMs before copying them to my Pi.  It's easy to say that I should have put "gamelist.xml" at the end of my path, but the issue isn't a configuration issue.  The issue is that a very simple configuration mistake can lead to a massive loss of data.  There should not be a scenario where a user can accidentally delete data without prompting.

**Comment by Universal-Rom-Tools** [comment]
You are right, I added a check (with an error message) when you select a folder instead of a file in the next version.

**Comment by Universal-Rom-Tools** [comment]
Added ;) normally it won't happen anymore ;)
