### ISSUE TITLE
Error when configuring at start with wizard (MIX)

### ISSUE THREAD

**Issue by Orvis** [Universal-Rom-Tools/Universal-XML-Scraper#121]
Hello,
When I launch UXS for the first, the wizard launches. I select my language, then I chose a profile : Recalbox v4 (MIX)
Then, I select the directory where the roms are stored (on a USB disk physically connected to the PC, not on the recalbox through a network share).
Then I'm asked to configure the Mix Image : Arcade (moon) or Standard (3img). Whatever I chose, an error pops up : AutoIt error : Line 16486 (File "D:\Universal_XML_Scraper.exe"): Error: The requested action with this object failed.
And it ends the UXS app.

If I chose a different profile (Recalbox v4), the wizard is fine and it ends correctly.

**Comment by Universal-Rom-Tools** [comment]
can you try delete all your UXS folder, download again the last version and try again ?

I haven't this problem :S

**Comment by Orvis** [comment]
??
I do not have any UXS folder. Just changelog.txt and UXS-config.ini files at the same root level as the exe file.
Obviously I tried to delete, and retry, and retry, ... but this does not fix.

By the way, I found a way to circumvent : If I chose the 'standard' Recalbox v4 profile, the wizard runs fine till the end and the app launches. Then, I have to configure manually the image config and to change the v4 profile to a v4 MIX from the app menus. Then I can scrape a directory. 
But it doesn't works as expected, because it hashes the roms, it creates the downloaded_images directory... but at the end, there are no pictures inside. I guess this should be considered as a new issue ^^

After all, If I close UXS, and if I launch it again ... then it crashes immediatly with the error reported above.

**Comment by Universal-Rom-Tools** [comment]
strange :( 

can you pastebin your logs.txt file ?

**Comment by Orvis** [comment]
Damn it! I wanted to restart from scratch to provide you a clean log file, and now it works fine. The only difference is that I put the .exe file in a sub-directory (D:\UXS) instead of D:\
I guess this is the origin of the bug, but now that everything worfs fine, I'm not really hot for retrying with the exe file at the root. Or at least once I've scrapped everything, I'll come back to you to test that again.

**Comment by Orvis** [comment]
OK, this is confirmed.
If Universal_XML_Scraper64.exe is placed @ D:\, it crashes with error reported above.
If Universal_XML_Scraper64.exe is placed in a sub-directory, it works fine.

The log.txt is here http://pastebin.com/t7QAvpaw
It is very light as it crashes as soon as I configure the MIX image style/

**Comment by Universal-Rom-Tools** [comment]
Oh !! Good to know...

(And the log is really light :S Need to add some ;) )

Thank you for your feedback. I close the Issue ;)
