### ISSUE TITLE
Consider 2 image mix option

### ISSUE THREAD

**Issue by Brandoskey** [Universal-Rom-Tools/Universal-XML-Scraper#122]
Would you consider adding this? I have a mini arcade cabinet and the zoomed arcade mix looks nice but it's a bit small on my 12" screen. I was thinking a mix with the screenshot and just the title/marquee. Same as the 3 image mix minus the box art. I assume most arcade games already lack box art, but I know neogeo games do have it for sure, so it would be more consistent with 2 images.

Thanks

**Comment by Universal-Rom-Tools** [comment]
I prefere you try to make it ;)

Just try : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/wiki/%5BTUTO%5D-Making-a-MIX-Template

If you didn't manage to do it ;) I'll do it ;)

(and if you manage to do it, send me your zip ;) I'll add it to the MIX repository for every one ;) )

**Comment by Brandoskey** [comment]
I'll give it a shot!

**Comment by Brandoskey** [comment]
Created the profile and made a pull request. I hope that was the best method, otherwise I can send it another way.

**Comment by Universal-Rom-Tools** [comment]
Great job dude and thank you ;) It's added to the Repository ;)

**Comment by Brandoskey** [comment]
Thanks, that is officially my first contribution.
