### ISSUE TITLE
Universal-XML-Scraper Has Stopped Working

### ISSUE THREAD

**Issue by 2xPutt** [Universal-Rom-Tools/Universal-XML-Scraper#124]
Any time I start the program, it immediately crashes and states it has stopped working. I have never even gotten the program to even launch once as it does this EVERY time.

![error2](https://cloud.githubusercontent.com/assets/24923628/21658135/4d56a2ca-d293-11e6-9191-bd7d8ef294c2.jpg)

I also notice this pops up every time I try to open the program and then disappears every time it crashes:
![error3](https://cloud.githubusercontent.com/assets/24923628/21658301/01e0d8be-d294-11e6-95f0-22550b735c63.jpg)

I remember the very first time I 'installed it' and was running it, it asked me a question that I have never seen since and if I recall correctly, it said something about ffaloader or viewer or something of that nature. 

Running on Vista  64bit, Any help?

**Comment by Universal-Rom-Tools** [comment]
ouch... Never eard about FFA ?

Don't know what it is :S 

but I think the first question you have the first time you launch UXS was your antivirus... :S and you certainly say "YES" to "do you want to stop this dangerous software ?" ;)

So I think it's that... I don't know what it can be ...

Can you see some "log.txt" file in the LOG directory ?
Can you try to launch the exe in administrator mode (SHIFT+right clic -> Launch in admin) ?
Can you check your antivirus ?

Thank you.

**Comment by SpaceSocks** [comment]
I'm having the same problem. Seems server side bad lag.  worked fine yestarday.
notice the time left in the pic.

![ff](https://cloud.githubusercontent.com/assets/24867255/21664097/09fa517c-d2aa-11e6-9dd8-dda98a5b7a1a.JPG)

**Comment by SpaceSocks** [comment]
@2xPutt there is a new version of the srapper that just popped up about an hour ago. it seems to be working now.. go grab that - 
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases

**Comment by SpaceSocks** [comment]
Ok i figured out something. In my own problems not so sure it was the version. I realized I am able to scrap my roms except my sega cds roms folder.. it halts on that one and goes slow. so my problem might not be the same as yours @2xPutt . I probably just have to reload my roms. but still allways good to upgrade to latest version see if that helps.

**Comment by Universal-Rom-Tools** [comment]
Apparently, the FFA icone is for the FFDSHOW. So maybe a problem to read the MP3 jingle.

Try to delete it in the UXS Ressource folder ;)

**Comment by pelztier3011** [comment]
here too.
new version doesnt change anything =(

**Comment by Universal-Rom-Tools** [comment]
same message with the FFA thing ?

**Comment by Keysersoze-77** [comment]
I'm also not able to start the programme. :( I'm still using Windows XP and on my laptop Windows Vista is running. But I don't get the FFA thing.

**Comment by 2xPutt** [comment]
I deleted the .mp3 jingle thinking it was using the FFDShow as someone mentioned earlier but it still plays the "XFS sound" on startup and immediately crashes. 

Newest version doesn't fix anything either, it still crashes on open. Turned off antivirus temporarily (AVG) and it still crashed.

Here is what the log.txt gives me if that helps at all:

[11:38:31] - C:\Users\Bryan\Desktop\dfbs\Scraper\Universal_XML_Scraper64.exe (2.1.0.1)
[11:38:31] - WIN_VISTA(X64) - 0409
[11:38:31] - Scrape in x64
[11:38:31] - > No updated files needed (Version : 2.1.0.1)
[11:38:31] - Starting files installation
[11:38:31] - > Ending files installation
[11:38:31] - > Verbose LVL : 2
[11:38:31] - > Path to ini : C:\Users\Bryan\Desktop\dfbs\Scraper\UXS-config.ini
[11:38:31] - > Path to log : C:\Users\Bryan\Desktop\dfbs\Scraper\LOGs\log.txt
[11:38:31] - > Path to language : C:\Users\Bryan\Desktop\dfbs\Scraper\LanguageFiles
[11:38:31] - Language Selected : 0409
[11:38:31] - > Update Checking
[11:38:32] - > File Downloaded Path : C:\Users\Bryan\Desktop\dfbs\Scraper\changelog.txt
[11:38:32] - > -In 1 try and 0.26s
[11:38:32] - Local : 2.1.0.1 - Github : 2.1.0.3
[11:38:32] - Asking to Update
[11:38:38] - > File Downloaded Path : C:\Users\Bryan\Desktop\dfbs\Scraper\Ressources\systemlist.xml
[11:38:38] - > -In 1 try and 3.51s
[11:38:39] - > systemlist.xml Opened
[11:38:39] - > File Downloaded Path : C:\Users\Bryan\Desktop\dfbs\Scraper\Ressources\Countrylist.xml
[11:38:39] - > -In 1 try and 0.25s
[11:38:39] - > Countrylist.xml Opened

**Comment by Universal-Rom-Tools** [comment]
I never try on XP and Vista :( 

On XP try to put your .net and MSSQL librairy uptodate.

On vista, I think the "bug" is different... Have you an error message ?

**Comment by Keysersoze-77** [comment]
I tried it on my fathers laptop and there it is working. He is using Windows 10.

**Comment by Universal-Rom-Tools** [comment]
great ;) so I close the Issue ;)
