### ISSUE TITLE
Only show game title for ROMS with multiple discs? (ex PSX / SEGA CD)

### ISSUE THREAD

**Issue by SpaceSocks** [Universal-Rom-Tools/Universal-XML-Scraper#126]
with systems like PSX and Sega CD they have multiple discs so i have been leaving them in folders for each game. But ideally I would like it when you clicked on the console it only shows the game and the box art without having to go into the sub folder like other consoles (NES ex).. is this possible?  (not showing the multiple discs just one title for each game)

After posting this I realized this might be more of a RetroPie Issue... but still any help would be appreciated..

**Comment by Universal-Rom-Tools** [comment]
It depend on wich "OS" you are.

On Recalbox, there is a "Hidden" function (automated in UXS) who hide the "other track" and keep only the first on visible.

On Retropie, I have no clue..

Don't know if it work on Sega CD (but it work on PSX) you can try convert your multiple track in 1 PBP file ;)

I found this : https://github.com/recalbox/recalbox-os/wiki/How-to-switch-multi-disc-PS1-games-%28EN%29
You can give it a try ;)
