### ISSUE TITLE
What is the difference between "(MIX)" and "[ROM FOLDER] (MIX)"?

### ISSUE THREAD

**Issue by tifsmo** [Universal-Rom-Tools/Universal-XML-Scraper#128]
As topic says i couldn't find any information on the difference between those profiles. also why is "rom folder" only available on retropie?

thanks for your time
cheers

**Comment by Universal-Rom-Tools** [comment]
On Recalbox, the default folder is the "rom folder"

On Retropie, by default, there is a folder for gamelist, and an other one for downloaded_images
BUT !!! It works too with the "rom folder". (Like the Sselph scraper default)

So you can choose ;) gamelist & image in the "default" retropie path OR in the rom folder ;)
