### ISSUE TITLE
Universal Scraper stopped working (crash) while scraping roms

### ISSUE THREAD

**Issue by tifsmo** [Universal-Rom-Tools/Universal-XML-Scraper#129]
While scraping l-fba the scraper crashed with the usual windows message "...stopped working". i was about 75% done and everything worked absolutley fine till that point.

here is what windows crash report had to say:

```
Problemsignatur:
  Problemereignisname:	InPageError
  Fehlerstatuscode:	c000020c
  Fehlerhafter Medientyp:	00000000
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	71ba
  Zusatzinformation 2:	71ba0f0d3c876798a0e89c158776d143
  Zusatzinformation 3:	2667
  Zusatzinformation 4:	2667e7341a6ea15246b9707f1f9f89a0
```

here are my two log files:

log.txt -> https://1drv.ms/t/s!Aq5by8Ix-jTKgZQGGecwiUGZcO3K7A
log1.txt -> https://1drv.ms/t/s!Aq5by8Ix-jTKgZQHnLbKt26t-frBIg

cheers

**Comment by Universal-Rom-Tools** [comment]
:S pretty weird... nothing in log about what can be done the wrong way :S 

Can you try again ?

**Comment by tifsmo** [comment]
already did but this time with file name only scrape. so no crc check. worked fine this time.

if i can reproduce the error, i'll let you know.

thanks for all your work by the way. your effort is greatly appreciated!

cheers

**Comment by tifsmo** [comment]
? i am using the lastest version available. in case we misunderstand each other i took a screenshot of the option i meant: https://1drv.ms/i/s!Aq5by8Ix-jTKgZQI7YNTONLf1iX0zQ

**Comment by Universal-Rom-Tools** [comment]
Lol ^^ Sorry ^^ To much work these last days... I forgot this option ;)

Take care, filename is Very very less accurate than CRC ;)

**Comment by tifsmo** [comment]
i think it works fine for mame/arcade roms since they have a certain naming convention i guess. others systems i scrape with filename+crc. 
thank you again!
