### ISSUE TITLE
[1.5.0.11] Com error with dom 

### ISSUE THREAD

**Issue by digitalLumberjack** [Universal-Rom-Tools/Universal-XML-Scraper#13]
While scrapping : 
![bug](https://cloud.githubusercontent.com/assets/1128425/17770551/b75e6422-653e-11e6-8b2b-dbe3cdfe4c2d.png)

If i press Ok the scrap continues.

**Comment by Universal-Rom-Tools** [comment]
Very strange, it's a Windows DOM error... Never happend to me :S 

Did it do it again ? Or just one time ?

Apparently it says the file is open... Maybe your antivirus scanning the file at the wrong time :S 

Tell me if you can reproduce the problem...

**Comment by digitalLumberjack** [comment]
Ok i try to reboot

**Comment by digitalLumberjack** [comment]
Still have this one, plus the other from https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/issues/11

For info i'm on windows 10 64 bits.

**Comment by digitalLumberjack** [comment]
For info the 1.5.0.5 do not have any of this issues on my computer.
