### ISSUE TITLE
another error while scraping (AutoIt Error)

### ISSUE THREAD

**Issue by tifsmo** [Universal-Rom-Tools/Universal-XML-Scraper#130]
sorry to bother you again :) but i got another error message while scraping resulting in the program to stop. this time a window opened that says: 

AutoItError

Line 220555 
Error: Array variables has incorrect number of subscripts or subscript dimension range exceeded.

here is a picture of the window:

https://1drv.ms/i/s!Aq5by8Ix-jTKgZQJ_WMfagm5xA9YyA

hope it helps debugging the program further!

cheers

**Comment by Universal-Rom-Tools** [comment]
Have you the log.txt file on this bug ? (or can reproduce it ?)

**Comment by Universal-Rom-Tools** [comment]
No news, hope it works

**Comment by thymon13** [comment]
hi !
I've excatly the same error :(

AutoItError

Line 26120
Error: Array variables has incorrect number of subscripts or subscript dimension range exceeded.
