### ISSUE TITLE
Sega CD takes 14 days to complete scrapping?

### ISSUE THREAD

**Issue by SpaceSocks** [Universal-Rom-Tools/Universal-XML-Scraper#131]
Anyone know why I can scrape all my other systems without issue but when I try to scrape my Sega CD folder it lags in and out to "Not Responding" and has an eta of 14 days for 
 36 roms for Sega CD?.. I noticed my 13 PSX games took along time aswell but not that long.. is there a corralation with "rom" size? Do I need to delete all my Sega CD roms and re add them? thanks.. Using latest verson of XML Scraper.

**Comment by Brandoskey** [comment]
For me it scraped every track of the single rom I have. So instead of having just sonic cd, I have sonic cd track 1-whatever. Might be I don't have my rom in the correct folder structure for retropie.

**Comment by Universal-Rom-Tools** [comment]
There is 2 things here : 

Time to scrape depend on a lot's of things...
To scrape efficiently, I need to Hash the file. It's very quick on small file... But very long on Big file.
And it's even very very long if you do it under network... And it's even worst if your network is wifi.

To solve this 2 solutions : 
Put your rom on a USB key on scrape on it ;)
Or
Try the new "experimental" function (scrape on pi) who ask the PI to scrape the file (so it's way faster on big file, no netxork problem... But it's slower on small file. The PI isn't so much strong ;) )

For your other problem Brandoskey you can modify the filter in General config ;)
With include file, exclude file and exclude folder.
Just put *track*.* in the exclude file ;) UXS won't scrape them ;)

**Comment by cfmarque** [comment]
I'm interested in your suggestion of putting the roms in a USB key (or directly from a hard drive if possible) .  I'm using the 3img profile, but quite often I'm missing the box art and the wheel img.

Sometimes re-running the scraper fixes it, but it takes a long time,  so could you explain a bit how could I scrape the roms from a USB drive connected to my PC?

**Comment by Universal-Rom-Tools** [comment]
Just change the "main path" in the autoconfig menu to go to the USB drive...
But on Retropie it's not so easy... because standard "path" need the PI folder structure.

But if you use the "ROM Folder" profil, Gamelist.xml and images are stored in the same directory as Rom. So it will work easily ;)

**Comment by Universal-Rom-Tools** [comment]
ho.. And I make a FAQ for problem like this one : 
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/wiki/ISO-Scrape-Freeze-or-are-very-long

**Comment by cfmarque** [comment]
Thanks for the heads up.  I was going thru the logs, and I realized that the reason it was taking so long to scrape some GB roms was due to some connection issues on my side.

Scrapping directly from the harddrive worked like a charm, much faster when you doing big groups of roms, but I still ran in to the problem of some images coming incomplete.

In case you are interested I’m attaching bits of the log showing the cases were the image came up incomplete.  Although I full don’t understand every single line in there, what caught my attention is that when it comes to downloading the image, there’s a login/password for user Screecher.  Is that what how it’s supposed to be?

I’m most cases I just delete the image and the info from gamelist.txt and the next time around the complete image makes it thru.

**Comment by Universal-Rom-Tools** [comment]
Can you test the very last version I release today...

Normally it resolve a lot's of Picture download issue...

**Comment by cfmarque** [comment]
Nice!  I just went over 94 roms, last time only 60 images got created.  This time around all 94 came back, some still have some parts missing, but you can certainly see the improvement, good work =)

**Comment by Universal-Rom-Tools** [comment]
For the missing part, it may be a lack of data on the DB ;)

If you want, you can check directly : http://www.screenscraper.fr

**Comment by cfmarque** [comment]
Oops, my bad, you are absolutely correct, in most cases the images wasn’t in the DB.  I should’ve checked before sending my last email.

The update works great.

**Comment by Universal-Rom-Tools** [comment]
great ;) so I close the Issue.

(Don't hesitate to register and submit some missing info to the DB ;) so you can scrape these new info and "Cerise sur le gateau" you will be awarned some thread to scrape faster ;) )
