### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by whyttygr3326** [Universal-Rom-Tools/Universal-XML-Scraper#132]
After scraping, why are some systems images bigger than others? Is there a way to fix.

**Comment by Universal-Rom-Tools** [comment]
It's about your config ;)

If you choose not a MIX profile, you can go to the picture configuration menu and "FIXE" a size ;)

**Comment by whyttygr3326** [comment]
I tried without mixing. Tried a couple times to change the size. Still didn't work. I am unfortunately probably have to go with the scraper that came with Retropie.

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 9, 2017 at 8:48 AM, Universal ROM Tools<notifications@github.com> wrote:   
It's about your config ;)

If you choose not a MIX profile, you can go to the picture configuration menu and "FIXE" a size ;)

**Comment by Universal-Rom-Tools** [comment]
Can you precise what sort of image ? And what sort of size difference ?

Some screenshot can have different size on the DB. But with the image configuration you can fixe a "maximum resize" after that it depend on the Ratio's picture...

Other media have standardized size I think... So I don't understand...

**Comment by Universal-Rom-Tools** [comment]
No news... so closed
