### ISSUE TITLE
Please add attached psx missing rom hashes

### ISSUE THREAD

**Issue by trutrax** [Universal-Rom-Tools/Universal-XML-Scraper#133]
I'd do it myself, but there is no documentation showing me how. 

thank you kindly.

[_Playstation_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/691645/_Playstation_missing.txt)

**Comment by Universal-Rom-Tools** [comment]
It's done...

But some weren't associate to there Game..

You can go to the website (http://www.screenscraper.fr/) to associate the orphean one ;)
