### ISSUE TITLE
Picture Only doesnt Work

### ISSUE THREAD

**Issue by RetroJoker** [Universal-Rom-Tools/Universal-XML-Scraper#134]
Hy,

i use the UXS for Recalbox V4. I want, that uxs only Scrape the pictures without descripion or rating. So i used the options:
- 2. Picture only
- Write new xml File
- Arcade (moon) Recalbox

But after uxs is finish, i don´t see the pictures in Recalbox. On my SD Card i can see, that uxs has downloaded the image.

**Comment by Universal-Rom-Tools** [comment]
Picture only, generate only picture without touching your gamelist.xml.

BUT !!! Emulationstation need at least gamelist.xml to know where to found the picture....

I think you must scrape with the standard mode...

If you don't want to "see" metadata, you need to chosse an other Theme in you recalbox ;)

**Comment by Universal-Rom-Tools** [comment]
No news... so closed
