### ISSUE TITLE
NeoGeo currently unscrapable

### ISSUE THREAD

**Issue by paradadf** [Universal-Rom-Tools/Universal-XML-Scraper#137]
Hi!

There is a bug after the unification of NeoGeo AES and MVS. The system isn't scrapable anymore, neither with UXS not with sselph's scraper.

https://github.com/sselph/scraper/issues/128

**Comment by Universal-Rom-Tools** [comment]
I see that... System exist and all is OK... Except it don't show up in the Systemlist API :S (like the 2 New system TO7 and MO5...)

I need a marblemad intervention ;)

**Comment by Universal-Rom-Tools** [comment]
Just corrected it in the next version...
It was a double problem..

Screenscraper have a cache on the systemlist (purged)
And Match table in UXS return the wrong system in case of neogeo. (corrected in 2.1.0.3 ;) )

**Comment by paradadf** [comment]
Great, thanks!
