### ISSUE TITLE
XML Scraper fatal error on load

### ISSUE THREAD

**Issue by BSAKat** [Universal-Rom-Tools/Universal-XML-Scraper#138]
Hey guys. This morning when I tried to open XML Scraper (09:40 eastern daylight time in the U.S.), the program refused to load. I got the launch screen and the voice announcing the program's name, and then it just hung. Eventually, after about a minute or two, I got a message stating "Fatal Error! Problem connecting to the database". I tried downloading a new version and trying again, but that didn't help.

**Comment by BSAKat** [comment]
Never mind, apparently the problem fixed itself.

**Comment by MaryBray140** [comment]
Yeah, it'll do that occasionally when the software is down and they're doing maintenance. I would keep an eye out for a new update soon. Usually they go hand-in-hand.

**Comment by Universal-Rom-Tools** [comment]
apparently all is good now ;)
