### ISSUE TITLE
Universal XML Scrapper Fatal error! (Scrap Engine launch Failed. Thank you to check your Antivirous)

### ISSUE THREAD

**Issue by ConstantinosKoup** [Universal-Rom-Tools/Universal-XML-Scraper#139]
It was working just fine, but when the scrapping finished I realized that it didn't recognize some games so I changed them and when I tried to run it again I got this error message "Universal XML Scrapper Fatal error! (Scrap Engine launch Failed. Thank you to check your Antivirus)". My antivirus and firewall are turned off. I even tried restarting the computer and deleting the Scrapper and re-downloading it but nothing worked.

**Comment by Universal-Rom-Tools** [comment]
Did you delete only the exe or the directory ?
Let's try with the last version in a new directory and keep me in touch ;)

**Comment by ConstantinosKoup** [comment]
I don't know what was the problem but the next day it was all working fine.

**Comment by Universal-Rom-Tools** [comment]
great ^^ maybe a temporary problem with the DB.. (we've got a few these last days...)
