### ISSUE TITLE
Add ScummVM support

### ISSUE THREAD

**Issue by paradadf** [Universal-Rom-Tools/Universal-XML-Scraper#14]
Hi! To be able to play ScummVM games with a libretro core, you need to create an empty file on the respective folder with a short name of the game ([listed here](http://scummvm.org/compatibility/)) and change the extension to .scummvm ([as explained here](https://github.com/recalbox/recalbox-os/wiki/Manual-(EN)#network-scummvm)). This is probable something that needs to be added to ScreenScraper as well, but creating this issue will probably reach the correct person ;)

**Comment by Universal-Rom-Tools** [comment]
Done, ScummVM added to Screenscraper ;)
