### ISSUE TITLE
Mame  Scrapping RetroPi 4.1

### ISSUE THREAD

**Issue by RetroPiFan** [Universal-Rom-Tools/Universal-XML-Scraper#141]
Hey all not sure if anyone else is have this issue. I'm running retropie 4.1 on a Raspberry Pi zero. I am able to scrape the rest of my roms for Sega Nintendo, Gameboy, turbo Graphics 16 and pulls in the artwork for those systems. It just MAME I am having troubles with. It Downloads all the MAME art work but does not display it. I see all the screenshots in the all images downloaded folder but why doesn't it show in retropie? Am I missing something?

**Comment by Universal-Rom-Tools** [comment]
Can you check the path in your gamelist.xml ?

**Comment by RetroPiFan** [comment]
Thank you for your reply.  Which one are you referring to? The one in the Roms folder or in the \all\emulationstation\gamelists\mame-mame4all?

![image](https://cloud.githubusercontent.com/assets/25175210/22170756/cfed5484-df47-11e6-969a-9feb9eec913e.png)

![image](https://cloud.githubusercontent.com/assets/25175210/22170783/0fb64d8c-df48-11e6-8909-260f76ef5935.png)

**Comment by RetroPiFan** [comment]
Here are the 2 that shows that one of the XML's point to the correct path and the other does not. Which one should I change? 



![image](https://cloud.githubusercontent.com/assets/25175210/22171077/6fba37ee-df4c-11e6-8f35-987394308c63.png)


![image](https://cloud.githubusercontent.com/assets/25175210/22171094/8ceccca0-df4c-11e6-848a-c8feac5ae7ac.png)

**Comment by RetroPiFan** [comment]
OK I figured it out. I removed the gamelist XML file that was in the ROM folder.
