### ISSUE TITLE
GBA scraping is not working anymore

### ISSUE THREAD

**Issue by paulosor** [Universal-Rom-Tools/Universal-XML-Scraper#142]
Since 2 days ago the GBA scraping is not working anymore.

**Comment by paulosor** [comment]
Seems that the software tries to contact mirror.screenscraper.fr that is down but I don't know why this affect only GBA scraping.

**Comment by Universal-Rom-Tools** [comment]
Sorry to be late, we found a bug "cache" related on the DB website.

It's OK now.
