### ISSUE TITLE
Having a hard time with PS1 titles

### ISSUE THREAD

**Issue by assassin316** [Universal-Rom-Tools/Universal-XML-Scraper#144]
I'm trying to get my PS1 titles sraped using RecalBox v4 [MIX], but many titles get skipped, and no matter which version I download I can't get them to work. Titles such as Castlevania: SOTN, Darkstalkers 3, Dino Crisis, Dino Crisis 2.

Is there something I have to do for PS1? I've also decoded ecm files into bin files whenver I got them, but that didn't help.

**Comment by Universal-Rom-Tools** [comment]
You need to check if they are missing (look in the missing.txt file)

Try scrape with "filename" only (instead of "CRC+Filename") in General menu.
Or use the Experimental function "SSH HASH" (don't forget to put your root path ;) )

**Comment by assassin316** [comment]
Does the filename get checked against the name used on screenscrapers.fr??  In other words, where is the list (or database) I can match it against?

Thanks for your help!

**Comment by Universal-Rom-Tools** [comment]
Just check http://www.screenscraper.fr/ The matching filename is done between only rom filename (not Game Name.. not enough accurate)

On a game file, you have (at the end) the list of associated Roms ;)

**Comment by assassin316** [comment]
It worked by filename, thanks!!  :)

**Comment by Universal-Rom-Tools** [comment]
Great ;) I close the Issue
