### ISSUE TITLE
Fatal Error (Time Out)

### ISSUE THREAD

**Issue by jumpman3000** [Universal-Rom-Tools/Universal-XML-Scraper#145]
Hello,

I have been using the latest version for weeks now when all of a sudden I receive "Fatal Error (Time Out)" messages. The splash screen will hang until the error is thrown. Nothing in the logs seems to indicate an issue. I have also tried downloading new copies with the same result. Pi is running and can Samba and Putty into the OS from desktop.

Please let me know what I can provide to aid in troubleshooting.

**Comment by gromp43** [comment]
Same thing happens to me as well.  Definitely a server side issue.  Was running fine earlier today.  I tried 2 different PCs and 2 different internet connections. same result.

**Comment by jumpman3000** [comment]
glad I am not crazy :)

**Comment by gromp43** [comment]
and it's working again for me!

**Comment by jumpman3000** [comment]
me too! Must have been a server side issue like you said.
