### ISSUE TITLE
Add Missing ROMs in XML Not Working in 2.1.0.3

### ISSUE THREAD

**Issue by SuperMagicom** [Universal-Rom-Tools/Universal-XML-Scraper#147]
Confirmed working in 2.1.0.2 but not 2.1.0.3

**Comment by Universal-Rom-Tools** [comment]
:S need to re check this so...

(I make some modification on this in 2.1.0.3... Maybe I broke something)

**Comment by Universal-Rom-Tools** [comment]
I just push out a new release, can you test it ?

**Comment by runechronos** [comment]
I tried with the 2.1.0.6, it doesn't seem to work. I have for example a ROM called "**Chrono Cross.iso"**, it's a fan translated version of the game so , the software is not finding it with the "**hash**" but it should with the **name** and it does not. I tried to add manually inside the **gamelist.xml** file, the xml tag with the proper "**id**" coresponding in screenscraper website (for my chronocross it's 19287)

`<game id="19287" source="ScreenScraper">
	<path>./Chrono_cross.iso</path>
	<name/>
	<desc/>
	<rating>0</rating>
	<releasedate>00000000T000000</releasedate>
	<developer/>
	<publisher/>
	<genre/>
	<players/>
	<region/>
	<hidden/>
</game>`

What should I do, I might have misunderstood how it's working ! Thanks in advance for your help.

**Comment by Universal-Rom-Tools** [comment]
"Chrono_cross.iso" doesn't exist in our DB...

look at the end of the game url, you have the list of referenced Roms : 
https://www.screenscraper.fr/gameinfos.php?plateforme=57&gameid=19287

**Comment by Universal-Rom-Tools** [comment]
I think it's ok now ;) (see the other Issue)
