### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by doriprata** [Universal-Rom-Tools/Universal-XML-Scraper#148]
Hi, I´m trying to use the program, but every time click to open it, I received the message: 

> Universal XML Scraper fatal error! (err_SystemList)

Anyone know how to solve this issue?

**Comment by Universal-Rom-Tools** [comment]
Do you retry since ?

Have you a firewall or antivirus (you need to give authorisation to UXS)

**Comment by doriprata** [comment]
it working now, thank you ;)

**Comment by Universal-Rom-Tools** [comment]
Great :D
