### ISSUE TITLE
Choosing gamename + country for name format not working

### ISSUE THREAD

**Issue by a7mag3ddon** [Universal-Rom-Tools/Universal-XML-Scraper#149]
As title says, when i choose gamename _ country for the name format the EU/JAP game files are stored without the country code in the list of games and also in the name section in the gamlist.xml file.

**Comment by a7mag3ddon** [comment]
Forgot to say, using reteopie mix.

**Comment by Universal-Rom-Tools** [comment]
we just have a problem yesterday with the country in the API.

Normally it's ok now... I need to test :S

**Comment by a7mag3ddon** [comment]
Just tested now and sorry to say still not working.

**Comment by a7mag3ddon** [comment]
Just a quick update seeing as there is a new version out, still not create the name + country code :-(

**Comment by rickdekker** [comment]
Same problem here using 2.1.0.6

Also in menu Configuration - General Configuration, I see a country code setup screen %COUNTRY%|us|uk|eu|wor|ss|jp|cus not sure what it is for and if it is used for identifying the rom country in the filename? is it case sensitive perhaps?

**Comment by Universal-Rom-Tools** [comment]
Sorry, I haven't corrected that yet :( (I need more time :( )

@rickdekker What you see in Gen Conf ( %COUNTRY%|us|uk|eu|wor|ss|jp|cus ) is the "Fallback" function for media and some "text" like the name of the game.

What it mean : 
Look for the country of the rom. Grab the corresponding media.
If nothing grab the us media
If nothing grab the uk media
If nothing grab the eu media
If nothing grab the world media
If nothing grab the Screenscraper (Internal) Name (not valid for media)
If nothing grab the jp media
If nothing grab the custom media

So you can change the order or force to try to grab a specified media (exemple, if you want only EU cover, just put EU in first... But take care, some jap game don't have EU cover for exemple ;) )

**Comment by rickdekker** [comment]
Cool thanks for the quick feedback and explanation. It's a great scraper, I appreciate the amount of work being put into it. I'll keep an eye on this GitHub issue.

Thanks again

**Comment by Universal-Rom-Tools** [comment]
Corrected in the V2.2.0.0 ;) (with a lot's of more things ;) )
