### ISSUE TITLE
[Feature Request] linux and mac compatibility

### ISSUE THREAD

**Issue by roba91** [Universal-Rom-Tools/Universal-XML-Scraper#15]
I'd love to see a build for:
 - [ ] Linux (proffered)
 - [ ] macOS (optional for me)

**Comment by Universal-Rom-Tools** [comment]
Unfortunatly, UXS is developped in Autoit. And Autoit can only be windows APP...

Sorry, it's the only dev language I know :(

Maybe in the future I will learn a new more portable language... But it's not for Tomorrow :(
