### ISSUE TITLE
BDD connexion issue

### ISSUE THREAD

**Issue by vsabard** [Universal-Rom-Tools/Universal-XML-Scraper#151]
Hi,
since days, I could not launch anymore Universal_XML_Scraper64.exe which encounters problems with BDD connexion. I also tried the V2, updating my policies in antivirus/firewall for .exe files, but still it is not launching.

![capture](https://cloud.githubusercontent.com/assets/25399490/22395087/2e4ea6cc-e533-11e6-8a6a-c97b62326b71.PNG)

Would you have any ideas how I could recover?
Thks a lot,
Vincent

**Comment by Universal-Rom-Tools** [comment]
Do you retry since ?

We've got some DB issues recently :( 
(Sorry for this)

**Comment by vsabard** [comment]
Actually yes. 
I succeeded to launch the scrap on full Mame romset. 
However, only 30% out of the 4000 roms were recognized with a valid screenshot...
It seems that a lot of media are either absent or could not be reached, is it also part of the ongoing DB issues ?
Thanks a lot for your support

**Comment by Universal-Rom-Tools** [comment]
I just push out a new release, can you test it ?

**Comment by vsabard** [comment]
I just downloaded it, and it just works perfectly!
Thanks a lot for your amazing job.
