### ISSUE TITLE
Cant scrape any roms

### ISSUE THREAD

**Issue by stevetingate** [Universal-Rom-Tools/Universal-XML-Scraper#153]
Hi 

Im trying to use this on my retropie install on an ubuntu 16 machine

it scrapes then when finished it gives this error

"Line 22172 (c:\xml\Universal_XML_Scraper64.exe")

Error: Subscript used on non-accessable variable

please help

**Comment by Universal-Rom-Tools** [comment]
have you a log ?

Have you retry since ?

**Comment by stevetingate** [comment]
[log.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/738752/log.txt)
[log1.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/738753/log1.txt)

**Comment by stevetingate** [comment]
i have retied and same error

**Comment by Universal-Rom-Tools** [comment]
I just push out a new release, can you test it ?

**Comment by stevetingate** [comment]
still errors out

[log.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/743508/log.txt)
[log1.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/743509/log1.txt)

so in trying to scrape my ubuntu pc that runs retropie, that would still work yes ?

**Comment by Universal-Rom-Tools** [comment]
Normally no problem to scrape from you win PC to ubuntu (or everywhere else ;) ) 
If you can see trhough your win explorer so you can scrape ;)

For the error, as what I see it's a problem server side... Need to call the big boss ;)

**Comment by Universal-Rom-Tools** [comment]
The big boss make some modifications, can you retry to scrape ?

**Comment by stevetingate** [comment]
Hi same error am I supposed to get new version ?

**Comment by Universal-Rom-Tools** [comment]
>< too bad :(

normally it should work with the 2.1.0.5 and the modification Marble make on the API...

Need to check that .. again :'(

**Comment by Universal-Rom-Tools** [comment]
can you test with the 2.2.0.0 ?
