### ISSUE TITLE
Crash on Windows Vista Business

### ISSUE THREAD

**Issue by johnpstyles** [Universal-Rom-Tools/Universal-XML-Scraper#154]
When I try to install it crashes every time.  Here are some screen shots.  Any help would be great 
![capture1](https://cloud.githubusercontent.com/assets/25469605/22489860/dc73b7e0-e7e7-11e6-92bd-9799d813ca8d.JPG)
![capture2](https://cloud.githubusercontent.com/assets/25469605/22489861/dc74bfb4-e7e7-11e6-94a4-572c8fe0ca37.JPG)

**Comment by Universal-Rom-Tools** [comment]
Can you check you antivirus and/or your firewall ?

Can you try to launch it as an admin ?

**Comment by johnpstyles** [comment]
I tried to run/install the program as administrator and it is still crashing.  I also turned off all firewall and antivirus and it still crashes.
![capture](https://cloud.githubusercontent.com/assets/25469605/22532213/d0c8d5f2-e8b3-11e6-8cca-3df2b2329c8d.JPG)

**Comment by Universal-Rom-Tools** [comment]
No news... so closed
