### ISSUE TITLE
Downloaded Files Not Valid

### ISSUE THREAD

**Issue by hemijj** [Universal-Rom-Tools/Universal-XML-Scraper#156]
I am running into an issue when scraping from 2 different Windows systems. Many of the files (both the images and videos) will not open and are 1K in size. Looking at the file contexts text, they include the phrase "API close for screenscraper no member". Sometimes attempting the same files will achieve the expected result and sometimes it seems worse than others.

**Comment by Universal-Rom-Tools** [comment]
Need to make some modifications on the source code :( sorry...

Wait for the next release ;)

**Comment by Universal-Rom-Tools** [comment]
corrected on V2.2.0.0
