### ISSUE TITLE
No images upon completed scrape & incomplete gamelist.xml

### ISSUE THREAD

**Issue by rwr1977** [Universal-Rom-Tools/Universal-XML-Scraper#158]
I have scraped many files successfully in the past.  Now for at least a week I have been unable to successfully get results.  I have tried 64 bit versions of releases 2.1.0.3, 2.1.0.4, and now 2.1.0.5.  The system completes the scrape but when I check the downloaded_images folder it is empty.  Also, the gamelist.xml file that is created is missing much information i.e. there is no game description.  Attached are a couple of the log files.  Thanks in advance for any help.
[log.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/751916/log.txt)
[log1.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/751913/log1.txt)
[log2.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/751914/log2.txt)

**Comment by rwr1977** [comment]
****UPDATE****
Today using the newest release 2.1.0.6 I am getting scrapped images but it is the exact same screenshot no matter what system I scrape.  Attached are one SNES and one Neo Geo .png file as examples as well as a log file.  Also, the gamelist.xml files are still missing game description, ratings, etc.
![fatfury3-image](https://cloud.githubusercontent.com/assets/25540693/22629547/214894a4-ebb6-11e6-96d7-f63ff00575a3.png)
![chessmaster the usa -image](https://cloud.githubusercontent.com/assets/25540693/22629550/2802c922-ebb6-11e6-8708-df84b80a34e9.png)
[log2.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/753260/log2.txt)

**Comment by Universal-Rom-Tools** [comment]
Sorry to be late (5 feb :S ) I miss your issue ^^

Did the problem still here ?

**Comment by Universal-Rom-Tools** [comment]
I think (and hope) the problem is gone
