### ISSUE TITLE
No-intro sets with corresponding screenscrapper.fr hashes don't get recognized

### ISSUE THREAD

**Issue by lagranzotto** [Universal-Rom-Tools/Universal-XML-Scraper#16]
I've tried to scrape my collection and several games with valid hashes don't get scrapped, like, for example:

Baku Baku Animal (Brazil).sms

![image](https://cloud.githubusercontent.com/assets/13103586/19059574/3349f2e4-89b7-11e6-8bd2-bbf513a125aa.png)

![image](https://cloud.githubusercontent.com/assets/13103586/19059580/4b7b4368-89b7-11e6-9d34-29dc0757e609.png)

![image](https://cloud.githubusercontent.com/assets/13103586/19059592/642e0530-89b7-11e6-8b7d-7b70cdd457a5.png)

**Comment by Universal-Rom-Tools** [comment]
That's strange.

to explain it : UXS doesn't "unzip" your file before testing CRC (Maybe in the futur V2 ; ) ) so it check the 7z File CRC. no 7z file referenced in Screenscraper, so it can't find it.

BUT

Normally, if CRC check don't work, it try to search for a matching file name (without extension).

Can you confirm that you scraped file is "Baku Baku Animal (Brazil).7z" ? If yes I will try on my side and check why it didn't work.

(Make sure you have the very last version, and not the "Special RETROPIE version" if you aren't under Retropie ;) )

**Comment by lagranzotto** [comment]
Well, i've used No-Intro dat files to confirm my copy of this particular game is really legit. Also i've tried to unzip all my roms and scrape again, without any change in my success rate. From 100 Master System and 100 Mega Drive roms, i've got under 10 matches for each system. The success rate with NES and SNES roms is by far superior.

**Comment by lagranzotto** [comment]
No, i'm not using Special RETROPIE version. I've altered the paths in the config to scrape my files in my computer, not in my raspberry pi. with NES and SNES, it worked flawlesly.

**Comment by Universal-Rom-Tools** [comment]
Can you try again ? we found a bug on the Returned XML from Screenscraper when the rom is from brazil or korea.

It's corrected now ;)

**Comment by lagranzotto** [comment]
I tried again with this ROM. Now it's working. Later I will try with other files that have not been recognized before.

**Comment by Universal-Rom-Tools** [comment]
Let me now, and re-open this issue if needed ;)

**Comment by lagranzotto** [comment]
I've tried with my entire collection. It works flawlesly now!
