### ISSUE TITLE
Set output image as jpg dosen't work

### ISSUE THREAD

**Issue by gleam2003** [Universal-Rom-Tools/Universal-XML-Scraper#161]
I set $vTarget_Image_Ext=jpg but output image dosen't change.
The output is always png

Sorry for english and thank you for nice work

**Comment by Universal-Rom-Tools** [comment]
If you are on a MIX profile it's "normal"... MIX need the png format to handle the transparency.
If not, I need to check that ;)

**Comment by gleam2003** [comment]
Not a bug, sorry. Tested with normal and work

**Comment by Universal-Rom-Tools** [comment]
great ^^ 1 issue closed 1 ^^
