### ISSUE TITLE
Error: Variable used without being declared

### ISSUE THREAD

**Issue by webwurm** [Universal-Rom-Tools/Universal-XML-Scraper#163]
Hi!
I'm trying to use the program in Windows 10 and after some time scraping all systems I get the error:
"Line 22140 (File "C:\Installs\Scraper\Universal_XML_Scraper64.exe"): Error: Variable used without bing declared"
![error 01](https://cloud.githubusercontent.com/assets/1053176/22709739/2b94ff9e-ed7b-11e6-90e9-6ddcb3eba776.JPG)

The error is (sadly) reproduceable - it always stops in the GameBoy-folder. Here is the content:
![error 02](https://cloud.githubusercontent.com/assets/1053176/22709775/4afb6da0-ed7b-11e6-88a1-27cf52537f5c.JPG)

I just tested: When I take out the gb-folder, the error occurs in the gba-folder.

Same error happens with the x86-version. 
Version is 2.1.0.6 btw.

I hope I put everything in here that could help!
Thank you, 
Manuel

**Comment by Universal-Rom-Tools** [comment]
Oups !! I think I broke the "full scrape" function with my last modification :(

sorry..

I'll correct that in the next release.

**Comment by gator2003** [comment]
I ran into this as well, doing a single system scrape. I had it happen on gba and gbc during separate run sessions. I have six threads selected, RetroPie Mix profile, and standard 3img selected. I've also never done a full scrape.

**Comment by Universal-Rom-Tools** [comment]
It happen even when you "just" scrape your GBA or GBC roms folder ?

I think something goes wrong with, maybe, 1 rom...

**Comment by webwurm** [comment]
No, that works. It really only happens with the "full scrape". And when I move the GB-folder to somewhere else outside, it has the error in the GBA-folder (each has just like 10 roms in it).

**Comment by gator2003** [comment]
For me, it happened when I scraped the gbc and then the gba directories. I was not using full scrape. I tried scraping them again after restarting the program and it worked.

**Comment by Universal-Rom-Tools** [comment]
Ok :S I Spoted the problem... It's when you scrape several plateform in the same "Session"... Now I know where to look for ;)

**Comment by morgalion** [comment]
Here is my scenario to always reproduce this error if it could help: (uxs 2.1.0.6, retropie rom folder profile)
- if i try to scrape "gameandwatch" (autoconfig), i have an error after choosing "game & watch" platform in dropdownlist: "Le chemin des ROMs n'est pas accessible".
- Then I choose another platform, for example "nes" in autoconfig, i launch scrap (by clicking button) and few seconds after i get this error (Variable used without being delcared).
Btw why i cant scrap Game & Watch (and notice that autoconfig force me to chose platform in dropdown, unlike other platforms, even with checkbox ticked to look for it automatically) ?

**Comment by Universal-Rom-Tools** [comment]
OK ^^ Better clue now ^^ there is a problem with the Game & Watch ;) (certainly the "&" :X )

I investigate and release a new version as soon as I can...
(Really Sorry, not so much time to work on UXS these last time...)

**Comment by morgalion** [comment]
Yes i think it's a global issue, after an error, if the scrap is ended (incorrect manner) you can't start antoher scrap. But reloading the app is a temporary working solution ;)

No problem for time, free project means free ETA ;)

We try to help you by describing precisely issues and lacks. But if you want some help in dev, just ask :)

**Comment by Universal-Rom-Tools** [comment]
Corrected in the V2.2.0.0 normally (If it's not the case re open the issue ;) )

**Comment by grigoletto77** [comment]
Im trying game and watch in version v2.2.0.1, also get the error after chosing the system. Is there any workaround on this? thank you all and great work with the screapper!
