### ISSUE TITLE
Error at launching

### ISSUE THREAD

**Issue by vsabard** [Universal-Rom-Tools/Universal-XML-Scraper#164]
Hello,
when launching the last version, I get this error:
![capture](https://cloud.githubusercontent.com/assets/25399490/22839749/07746a4e-efcb-11e6-8851-8ae6c07f002b.PNG)

I tried older versions, but each has a different issue..finally I cannot get a working version at all.
Is that possible to labelize like stable version "released" to keep a reference of good one while developing in parallel the newest ones that can bring regressions ?

Thks a lot for your support
Vincent

**Comment by letook** [comment]
Same here, I try everthing I can but it seems it comes from the website....
https://www.screenscraper.fr/ I can randomly access it, tonight. The CPU is at 2% and less than 10 scrappers online... There is obviously an issue.

We should try later :)

**Comment by Universal-Rom-Tools** [comment]
Sorry to be late :S 
Do you try scrape "all system" or just 1 ?

The all system scrape is broken right now and return this sort of error...

**Comment by Universal-Rom-Tools** [comment]
If it's for the scrape all... It's corrected in the v2.2.0.0
