### ISSUE TITLE
scraper dont finish process

### ISSUE THREAD

**Issue by sinho14vk181** [Universal-Rom-Tools/Universal-XML-Scraper#166]
Hi, i scrape roms for super nintendo (3500) and no finish. If no finish no have gamelist.xml and dont show in recalbox.
![image](https://cloud.githubusercontent.com/assets/25721611/22862042/2621d640-f127-11e6-8c41-064cf39b2032.png)

**Comment by sinho14vk181** [comment]
why no finish the process? its creating the gamelist.xml? i dont see this archive on roms snes folder

**Comment by jaraquistain** [comment]
How long did you let it sit for? I found it hangs for a while in that state and eventually finishes. I also did about that many snes roms

**Comment by morgalion** [comment]
Same here, when 3000+ roms on differents systems ;) It always finishes for me (but after some minutes). Be patient i think.

**Comment by Universal-Rom-Tools** [comment]
Yep... I need to add an other progress bar when the Final XML is under construction...
With lot's of rom, depending on the drive/network speed, it can take a little time...

-> In the to do list.

**Comment by morgalion** [comment]
But at least it's not an issue ;)

**Comment by Universal-Rom-Tools** [comment]
Done in the v2.2.0.0 ;)
