### ISSUE TITLE
Avoiding games already scraped

### ISSUE THREAD

**Issue by cliffyb73** [Universal-Rom-Tools/Universal-XML-Scraper#167]
Might be a daft question or a option im overlooking however when i add new roms to a folder i have already scarped, I cant seem to avoid the program scarping every game again instead of the ones I have just added. Am I missing something in the settings? Thanks.

**Comment by paradadf** [comment]
You have the option to choose between creating a new XML or Updating it. Look under general options I believe.

**Comment by cliffyb73** [comment]
I see the option. Was right in front of me all the time lol. Thanks for your help.

**Comment by zoff99** [comment]
this option does still scrape all the roms again
