### ISSUE TITLE
Impossible to scrap supergraphx roms with retropie profile (autoconf)

### ISSUE THREAD

**Issue by morgalion** [Universal-Rom-Tools/Universal-XML-Scraper#168]
I can't scrap 4 turbographx games with a retropie profile (autoconf) : https://thepasteb.in/p/nZhlA8jRrlACY
In retropie, we use the same folder for turbographx / supergraphx / pc engine cd-rom (recalbox use separate folders).
In my log file, i have the error : /!\ Error File Line 1 : Erreur : Rom/Iso/Dossier non trouvée !
If i change the "systemeid" variable of the SS URL, (from turbographx value to supergraphx value) i can download the xml file and i don't get the error.

**Comment by Universal-Rom-Tools** [comment]
More simple : try to deactivate "auto select your system" in the General menu.

So it will "ask" the referencial system to scrape (and you can even choose to scrape your Gameboy rom on Neogeo DB ^^ with poor result I think ;) ) But so you can choose...

It's in the "to do list" to merge the CoregrafX, CoreGrafX II, SuperGrafX, TurboGrafx-16 and PC-Engine in the Same "System" as they are the same "plateform" (with differente name, and differente "color" ^^)

**Comment by morgalion** [comment]
Ok thank for the tips ;)
