### ISSUE TITLE
Slow down when selecting more than 5 threads

### ISSUE THREAD

**Issue by gator2003** [Universal-Rom-Tools/Universal-XML-Scraper#169]
So I contributed to editing the database at ScreenScraper and it seems they gave me 8 threads at one time. Hooray! However, if I select anything higher than 5 threads, the scraping of mame-libretro goes really, really slow. I have about 530 ROMs in that directory. The only way to reproduce the slowness is to set it to 8 threads.

To give an example, at 5 threads, scraping mame-libretro takes an hour for 530 ROMs. At 8 threads it takes over five hours.

**Comment by Universal-Rom-Tools** [comment]
Warning : Thread take a lot's of ressource "EACH".... So the more Thread you use, the more your CPU is solicited...

take a look to your CPU Use when you scrape... And add Thread 1 by 1 till you reach the 99.99% ;)

**Comment by gator2003** [comment]
Good call. Even with a beefy i5, it almost pegs all four cores at 90% for five threads. Thanks for the heads up!

**Comment by gator2003** [comment]
Also, the speed of ScreenScraper is really the bottleneck. It was being really slow the other day, now it's lightning quick.
