### ISSUE TITLE
gamelist.xml ripped after update gamelist

### ISSUE THREAD

**Issue by budanomeayuda** [Universal-Rom-Tools/Universal-XML-Scraper#17]
Hi;

I have one possible issue regarding one system: msx. Thing is, when I scrape the data and photos via Universal XML Scraper,  everthing in build well (gamelist.xml=687 KB).

Then, when I refresh the gamelists via Recalbox menu, this file is ripped and lost most of his info (gamelist.xml = 64 KB).

What do you think? Why is only happening with this system (and probably NES too)?

Thanks for your great work,
Daniel

**Comment by Universal-Rom-Tools** [comment]
Hi budanomeayuda ,

Sorry to answer you this late...

What you describ is like an emulationstation not killed BEFORE Scrape ;)

for information : 

Kill Emulationstation via SSH Menu in UXS or via SSH software (like winscp) or directly on your recalbox
When your screen turn black, launch the scrape ;)

**Comment by Universal-Rom-Tools** [comment]
No news after near one month...

I close the case.
