### ISSUE TITLE
Scraping is very slow and crashes.

### ISSUE THREAD

**Issue by saboteur111** [Universal-Rom-Tools/Universal-XML-Scraper#172]
2 questions. Is there a way to speed up the scraping process? I have a very fast connection so I'm wondering why it takes so long. Also, if it crashes, how do you continue where it left off? Since it's slow, I hate having to start all over again. Thanks.

**Comment by Universal-Rom-Tools** [comment]
You can speed up the scraping process by adding some thread.

1 thread mean : Scrape 1 game at a time
2 threads mean : Scrape 2 game simultaneously
3 threads ....
So you can have a great improvement on scrape time.

how to gain Threads ?
Thread are some "award" for contributors who help filling or supporting the DB.
You have choice : 
- Simply create an account on http://www.screenscraper.fr and help to fill the blank (synopsis in your language, dates, editor,... And the "hardest one" add media ;) ) You will gain rapidly 1 or more thread.
- or you can contribute with Tipee or Patreon and give some money to the project.
(We prefere the first one, so it's easier to gain "free" threads with just couple of submit...)

For the "crash" can you explain what happen ?
If it crash but you already have a gamelist, you can config UXS to append the file (General Conf -> Scrape Mode -> Update) It just scrape the missing file ;)

**Comment by Universal-Rom-Tools** [comment]
No news.. I close the Issue

**Comment by sbowler** [comment]
FYI, I could not register on your site using Chrome for some reason.

**Comment by KingofMetal79** [comment]
Good Morning,
I too have a similar question...
I have attempted scraping for PCEngine roms and twice it has crashed before scraping has completed and gave the standard Windows notice that the programme has stopped working and shut Universal XML scraper down. When I have gone into the game_images folder on the RetroPie I can see the Mix images that had been downloaded up until the crash, however the XML file is blank. Therefore How do I simply create an XML file without the need to download the images again? I assume I just choose General Conf > Scrape Mode .  Option 1?

Kind regards
