### ISSUE TITLE
Scraping Atari 800 vs. Atari XE

### ISSUE THREAD

**Issue by Dragontorc** [Universal-Rom-Tools/Universal-XML-Scraper#174]
I have tried several times to scrape Atari800 for my RetroPie.  Every time I ended with nothing being scraped.  It seems that Screenscraper.fr has all Atari 8-bit titles listed under Atari XE and Atari 800 listing no single title.  Could it be the case that UXS tries to scrape empty folder for Atari 800? If that is the case is there any chance to have it pointed to Atari XE?  I know I have all my Atari 800/XL/XE files using same names as titles listed on screenscraper.fr.

Thank you for making this fantastic tool!

**Comment by Universal-Rom-Tools** [comment]
I'm not very on Atari plateform ^^ so I can't help very much on what is on the DB...

But if you want, you can uncheck the "autoselect plateform to scrap" checkbox in the General Config Menu.
So before the scrape start, you can choose on "wich" plateform you want to scrape...
So if you want you can choose to scrape your Gameboy Rom in the Amiga DB ^^ (with poor result I think ^^) But in your case, scrape your Atari800 Roms in the Atari XE DB ;)

Just make a check before on http://www.screenscraper.fr to see where are the game you want ;)

**Comment by Dragontorc** [comment]
Dude, that is awesome! You've just made my day! Big thanks.

**Comment by Universal-Rom-Tools** [comment]
I close the Issue ;)
