### ISSUE TITLE
Scraped 100% MAME art but it doesnt show in my Emulationstation frontend.

### ISSUE THREAD

**Issue by DeltreeZero** [Universal-Rom-Tools/Universal-XML-Scraper#177]
I can see all the scraped images in my RETROPIE\configs\all\emulationstation\downloaded_images\arcade folder, but they do not show up in my Arcade game list in the emulationstation frontend. Any thoughts?
![mame art](https://cloud.githubusercontent.com/assets/26007513/23311096/d69a27a2-fa82-11e6-996d-48c9738646f9.PNG)

**Comment by morgalion** [comment]
What profile did you use [rom folder] or not ? Be sure to only have 1 gamelist.xml first. Because if you have a gamelist.xml in your rom folder and 1 in emulationstation folder, rom folder will take priority over emulationstation folder.

**Comment by DeltreeZero** [comment]
Forgive me I am a powernoob. I am using a rpi3-b with retropie image.

Following Eazy Hax tut on youtube, https://www.youtube.com/watch?v=0ZexFv5QdM0 I chose Retropie MIX as the profile. 

I am not familiar with gamelist.xml or its function. Should I delete one from a location you mentioned?

**Comment by morgalion** [comment]
ok so the link of your gamelist.xml should be \\retropie\configs\all\emulationstation\arcade\. Dou you see the file ? just open it and look if you see the games listed in :)

**Comment by morgalion** [comment]
One more thing, don't forget to restart emulationstation after transfer :)
and emulationstation needed to be stopped before transferring the file gamelist.xml (already the case if you correctly set ssh parameters)

**Comment by DeltreeZero** [comment]
I tried restarting emulationstation and also the pi to no avail. :(

The gamelist.xml appears to be here : 
![location 1](https://cloud.githubusercontent.com/assets/26007513/23311944/d523266e-fa85-11e6-976a-df6e88489da3.PNG)

I looked here but no joy. Is my gamelist.xml for Arcade in the wrong place?
![location 2](https://cloud.githubusercontent.com/assets/26007513/23311965/efc6be0e-fa85-11e6-93df-ff43526d7108.PNG)

 Heard on quitting emulationstation before moving the file. 07 Will do, if I do need to move this file.

**Comment by morgalion** [comment]
You need to stop ES before, and start after because ES can overwrite this file. And a restart is needed to load the new gamelist.xml.
Now, your link is good (RETROPIE\configs\all\emulationstation\gamelists\arcade). Check your arcade rom folder and be sure you dont have a gamelist.xml

**Comment by morgalion** [comment]
It's strange your gamelist.xml is 1ko ;) i think you did the scrap without stop ES and you lose the data

**Comment by DeltreeZero** [comment]
I feel like when universal xml scraper started doing its thing it shut down emulationstation automatically, but i defer to your experience, and I have very little idea whats going on. XD thanks again for the assist!

There does not seem to be an .xml file in this folder.
![data 1](https://cloud.githubusercontent.com/assets/26007513/23312358/71948b54-fa87-11e6-8423-0105c465fcd8.PNG)

Is there a place to download the proper gamelist.xml? or somehow generate one?

**Comment by DeltreeZero** [comment]
It is true! this file is basically blank! LOL

![data 2](https://cloud.githubusercontent.com/assets/26007513/23312462/db67e742-fa87-11e6-88d9-04372d37c00b.PNG)

**Comment by morgalion** [comment]
gamelist.xml is generated by UXS ;) when you use the wizard and choose the profile Retropie MIX, it sets all the path for you. So, if all is ok, UXS will stop by ssh ES, and at end of scrape generate gamelist.xml and move it to the right folder.
First, check you can acces at your retropie via ssh in UXS

**Comment by morgalion** [comment]
By default, your host is RETROPIE (it is ok if i look your screenshots). Login/pass are by default pi/raspberry. You can easily test it by clicking on "stop emulationstation" ^^

**Comment by LightningGA** [comment]
I'm having a similar issue. If the gamelist.xml file is deleted, will USX regenerate it?

**Comment by DeltreeZero** [comment]
As i observe the profile selection options, there appear to be more than seen in the Eazy Hax tut vid I mentioned earlier. Is there a better option for me than "Retropie MIX"? There is also "Retropie [Rom Folder]" and "Retropie [Rom Folder] MIX"

**Comment by morgalion** [comment]
it depends of your option "Scrape Mode", create new xml or update xml. But in both cases, yes gamelist.xml is modified ;) it's the goal of the software to generate a gamelist.xml

**Comment by morgalion** [comment]
Rom Folder = the folder downloaded_images and the file gamelist.xml will be generated in your rom folder instead of emulationstation. The only advantage : if you use an external hdd you can always have the gamelist.xml with you (for example if you have friends with retropie ;))

**Comment by DeltreeZero** [comment]
Emulationstation has been stopped and UXS has finished autoconfig with profile "Retropie MIX" selected and the arcade cabinet picture option selected.

**Comment by morgalion** [comment]
OK, so after the scrape, restart emulationstation and test :) (you can check your gamelist.xml, it shouldn't be 1ko)

**Comment by DeltreeZero** [comment]
Will this find my existing scraped images?

**Comment by morgalion** [comment]
Unfortunately, without gamelist.xml, uxs will redo a complete scrape (images or not). The update mode is based on the content of the actual gamelist.xml. I hope im clear ^^

**Comment by morgalion** [comment]
You can always check the "actual" path used by uxs in : Path configuration. The two options importants to you are : xml file path (gamelist.xml path) and "Directory where pictures will be downloaded". So after scraping, you can check your gamelist.xml is not empty and images folder too ^^

**Comment by DeltreeZero** [comment]
I will check in when it has completed.

**Comment by morgalion** [comment]
I think the common issue is to dont stop ES, navigate in menu and so overwrite gamelist.xml

**Comment by DeltreeZero** [comment]
A quick check shows the gamelist.xml has grown to 112k. This is good news.

**Comment by morgalion** [comment]
yes ;) If ES is stopped and you dont play with during scrape, all will be fine :)

**Comment by DeltreeZero** [comment]
All is working now. Problem solved. Thanks again! Excellent!

**Comment by LightningGA** [comment]
Mine too!
Thanks

**Comment by morgalion** [comment]
Happy to hear that ;) have à nice d(pl)ay ;)

**Comment by Universal-Rom-Tools** [comment]
Thank you morgalion to help people when I'm not here ^^

Very busy time out of UXS right now... (lot's of "real" work to do ^^)

It's really cool guys like you or paradadf help others ^^ Thank you very much.

(So all is OK I close he Issue :p )
