### ISSUE TITLE
Add support for http://thegamesdb.net/

### ISSUE THREAD

**Issue by Redemp** [Universal-Rom-Tools/Universal-XML-Scraper#18]
Hi!

Would it be possible to add support for http://thegamesdb.net/ when no info is found on http://screenscraper.fr/ ?

Best Regards

**Comment by Universal-Rom-Tools** [comment]
Hi Redemp,

It's not planned to add tgdb now... (and I think it will never be added ;) )

Screenscraper have nearly all the data you can found on tgdb ;) and much much more ;)

If you have a missing, don't hesitate to participe to Screenscraper (you can submit all stuff you need ;) )

But if you check ;) I think you can't found so much data on tgdb you don't have in same or better quality on Screenscraper ;)

Best regards too ^^
