### ISSUE TITLE
Can't load scrape from usb stick on retropie

### ISSUE THREAD

**Issue by ldekort** [Universal-Rom-Tools/Universal-XML-Scraper#180]
Hello,

I have a problem to read the scrape from usb stick.
On my Pi i load the game's from a usb stick. Now i wanne scrape the game's to.
Can someone explain me how to do this.
Sorry for my poor english. (Belgium)

**Comment by Universal-Rom-Tools** [comment]
Hello Idekort

Simply 'launch' the Wizzard, select your Profil ( a [Rom Folder] Profil for Retropie ) and when it ask you the path to scrape, select you USB Key (plugged in your PC).

If you have path like : **X:\Roms\**SNES
Your path must be : **X:\Roms\**

So you can use the "autoconf" to select with plateform you want to scrape ;)

**Comment by ldekort** [comment]
Maybe my question is not correct.
I can scrape them on my usb stick. it create a map then on my usb stick with the images.
but when i plug it in on my raspberry it doesn't load them. 
It is i think because i load my game's from usb and not from sd card.

**Comment by Universal-Rom-Tools** [comment]
First : on wich OS are you (Recalbox or Retropie ?)

Second : I think you "play" with path ;) so they may be wrong in the XML : that's explain why it doesn' work...

Third : That's why I ask you to use the Wizzard ;) so it will put good path ^^

Fourth : That's why too you must considere (if you are on Retropie) to scrape your USB Key with a [ROM FOLDER] Profile.... So all the info (gamelist.xml & downloaded_image) will be in each plateform folder.
It's far more easy than use the "Retropie standard path" ;)

**Comment by ldekort** [comment]
I use retropie
I followed te youtube link how to install how to scrape.
Should i put the xml files somewhere else then.
Sorry my english is not that good. 
My emulators and game's or on the usb.
If i scrape with usb the wizzard put the file's in a new map.
Should i put them somewhere else then?

**Comment by Universal-Rom-Tools** [comment]
Vu que tu es belge on va parler français ;) ce sera plus simple ;)

Ton retropie est bien sur un RaspBerryPI ? (ce n'est pas très clair ;) )

Comme conseillé, utilise le profile "Retropie [Rom Folder]" comme ça toutes tes infos de scrape (image et gamelist) seront DANS les répertoires de tes roms et ça ne te créera pas de chemin supplémentaire...

C'est l'option qu'il faut utiliser quand on a ses roms sur une clef USB ;)

**Comment by orochikun** [comment]
Im doing exactly that 👍 and it works like a charm 
So for me it works like this, 
Raspberry Pi 3 > Retropie 4.2 > [Roms in the USB ( via usb easy method  )](https://github.com/RetroPie/RetroPie-Setup/wiki/Running-ROMs-from-a-USB-drive)

And you mentioned to use ROM folder as image folder ... but I cant find the option in the app 

> Fourth : That's why too you must considere (if you are on Retropie) to scrape your USB Key with a [ROM FOLDER] Profile.... So all the info (gamelist.xml & downloaded_image) will be in each plateform folder.
It's far more easy than use the "Retropie standard path"
