### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by bobbycopter** [Universal-Rom-Tools/Universal-XML-Scraper#181]
My system:

Intel Core 2 Quad CPU Q8300 @ 2.50 Ghz
4,00 GB Ram
Windows 8.1 64bit

Allowed Universal_XML_Scraper64 in Windows Firewall and Avast Free Antivirus.

With task manager open I see the programm running for several seconds but nothing happens, no start screen or error message.

Tried several releases, from newest to older ones. Every time nothing happens :(

**Comment by Universal-Rom-Tools** [comment]
Let me guess... You are trying to launch scraper.exe or scraper64.exe....

These are the scrape engine... and do nothing launched as standalone ;)

you need the Universal_XML_Scraper.exe here : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases

**Comment by bobbycopter** [comment]
Hi! Thank you for your reply (and labeling my post).

I tried running the .exe you provided me with. It creates several folders and files. 

LanguageFiles
LOGs
Mix
ProfilsFiles
Ressources
Universal_XML_Scraper64.exe
UXS-config.ini

(and two hidden files scraper.exe and scraper64.exe)

But then again, nothing happens.

**Comment by Universal-Rom-Tools** [comment]
If it create file, it do something ^^

But it's weird if nothing else happen...

Try the new version I just release and post me the log (in the LOG folder)

**Comment by TRoZZNL** [comment]
I have the exact same issue on Windows 10 Pro, my log file output is : 
`[00:05:30] - C:\Users\Mark Rienstra\Desktop\scraper\Universal_XML_Scraper64 (1).exe (2.2.0.0)
[00:05:30] - WIN_10(X64) - 0409
[00:05:30] - Scrape in x64
[00:05:30] - Starting files installation
[00:05:31] - Unziped : C:\Users\Mark Rienstra\Desktop\scraper\Ressources.zip to C:\Users\Mark Rienstra\Desktop\scraper\`

The folders and files are created and then nothing happens.

**Comment by TRoZZNL** [comment]
I think i found a solution !
i looked in the windows event logs and found out that `C:\Windows\System32\vorbis.acm` was causing the problem.
It turns out this is part of the vorbis codec package and for some reason seems to be crashing different applications (also Remote Desktop for instance).

If you rename the file to` vorbis_back.acm` the application runs fine !

**Comment by Universal-Rom-Tools** [comment]
vorbis ??? So it's the MP3 jingle at start making problem :(
I will put an option to deactivate this...

**Comment by bobbycopter** [comment]
Worked for me too! Thanks TRoZZNL you made my day! <3

**Comment by TRoZZNL** [comment]
Thats great, happy to help

**Comment by Universal-Rom-Tools** [comment]
In the next version : 
When UXS start for the first time, it create a shortcut to an "UXS silent"... who start UXS without sound (so normally no more error about that :S )

**Comment by bobbycopter** [comment]
Thanks for that. Keep up your awesome work!

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2
