### ISSUE TITLE
uxs v2 problem

### ISSUE THREAD

**Issue by pillemats** [Universal-Rom-Tools/Universal-XML-Scraper#182]
https://forum.recalbox.com/topic/6717/mit-uxs-v2-direkt-von-usb-hdd-scrapen

**Comment by Universal-Rom-Tools** [comment]
Hi @pillemats 

Ok, so I know what Happen.

Can you try to create a UXS folder on your external hard drive (like E:\UXS ) put only the Universal_XML_Scraper64.exe in it.
Launch it.
Then on the wizzard put : F:\RECALBOX\roms when it ask you for the path...

So normally all path will be autoconfigured... And you can choose the plateform in the Autoconf menu... And scrape ;)

**Comment by pillemats** [comment]
Thanks ! I will try it and give u a Feedback

**Comment by pillemats** [comment]
hey it works perfectly.

if i understand it correctly i can not use the funkeion "Scrap all" right now because it is buggy right ?

**Comment by Universal-Rom-Tools** [comment]
Yep... sorry... Scrape all need to be "rewrote" :( (right now you will have an error :( )
