### ISSUE TITLE
Can Not find all Games 

### ISSUE THREAD

**Issue by pillemats** [Universal-Rom-Tools/Universal-XML-Scraper#184]
I have a dreamcast no Intro set but uxs can Not find all Roms 
My filename is abcde.cdi 
On the db is only abcde.gdi 
So uxs can Not find it ! Is it normaly? How can i find the artworks without much effort?

**Comment by abunille** [comment]
Hi Pillemats, look here, if this helps.
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/wiki/Rom-Missing-on-Screenscraper

**Comment by pillemats** [comment]
thank for your answer but at the moment i get not the verification mail :-( So i can not complete the registration

**Comment by pillemats** [comment]
i have been registered 5 day ago but i get not an verification mail to complete the registration on screenscraper.fr

is it normal =?

**Comment by Universal-Rom-Tools** [comment]
Hi @pillemats , I have forced you register on Screenscraper.. Normally it's OK ;)

**Comment by pillemats** [comment]
Thank you it works

**Comment by pillemats** [comment]
Is it possible to load up The complete missing.txt at once or should i only mark Every Game and enter my filename to complete the db search?

**Comment by pillemats** [comment]
And where can i find the page to upload the filename ? I get the rom but i only can upload artwork

**Comment by pillemats** [comment]
I have now the filename at the respective game submitted but these were unfortunately rejected. I think I made a mistake! Where exactly do I have to enter this game filename?

**Comment by Universal-Rom-Tools** [comment]
You can't submit directly to the DB new file..

You must send us the missing file (like you did) so we can check them...

I close the issue so ;)
