### ISSUE TITLE
Server - Can't connect with the database

### ISSUE THREAD

**Issue by ricsmachado** [Universal-Rom-Tools/Universal-XML-Scraper#185]
Hello, 

There's something happening with the servers this weekend? When I try to open the app, it keep saying about a problem to connect with the database.

I hope is only temporary, your app is great. 

Thanks for all, dude! Awesome work!

**Comment by Universal-Rom-Tools** [comment]
The server is very overloaded at Week End...
A new server is comming...

**Comment by Universal-Rom-Tools** [comment]
New server is up... normally no more problem ;)
