### ISSUE TITLE
RetroPie Won't Use Scraped MAME Artwork

### ISSUE THREAD

**Issue by Linux500** [Universal-Rom-Tools/Universal-XML-Scraper#191]
After updating to the latest version I cant get any of the scraped MAME artwork to show up on RetroPie. I tried messing with the path configuration and now at the end it says something about something not accessible. Help please!

**Comment by Universal-Rom-Tools** [comment]
don't mess with the path ;)

Try simply to use the wizard (if you have a "standard" installation it's enough)

when you say "I cant get any of the scraped MAME artwork" have you the gamelist.xml ok ?
did the kill emulationstation work ?
have you check in the download_images folder ?

**Comment by Linux500** [comment]
Ok I'll try redoing the wizard later. And yes it downloads the XML and images fine, but it doesn't show up on RetroPie unless if I tell it to locate the picture manually.

**Comment by Linux500** [comment]
It says it has an unaccessible error or something and shut down. What should I do?

**Comment by Linux500** [comment]
I tried everything I could but I can't get it to work. At least the built in scraper in RetroPie actually worked...

**Comment by Linux500** [comment]
Just had to manually tell RetroPie to show 30+ images one at a time. Not happy...

**Comment by Universal-Rom-Tools** [comment]
Try this :

In ProfilsFiles Folder, open Retropie.xml

Look for the section \<AutoConf>

and replace it by : 
```
<AutoConf>  
<Source_RootPath>\\retropie\roms</Source_RootPath>  
<Target_XMLName>%Source_RootPath%\%system%\gamelist.xml</Target_XMLName>  
<Target_RomPath>./</Target_RomPath>
<Source_ImagePath>%Source_RootPath%\%system%\downloaded_images</Source_ImagePath>
<Target_ImagePath>./downloaded_images/</Target_ImagePath>
</AutoConf>
```

**Comment by Linux500** [comment]
I changed the XML, then i downloaded the new update and Windows won't let me run your app >:(

**Comment by Linux500** [comment]
I changed the XML and updated, now it says that "Rom paths for auto configuration can't be reached."

**Comment by Universal-Rom-Tools** [comment]
As I say, take the last version, edit the retropie.xml profil. And put the "autoconf" part above..

Just one thing : If you aren't directly on retropie but on local USB juste change the "Source_RootPath"
"\\retropie\roms" is the network path to your retropie. Just change that by your USB key path (like "f:\roms" )

It will put all the gamelist.xml and downloaded_image folder directly in the roms folders with the good path...

**Comment by Linux500** [comment]
The pictures are getting to the correct destination on the USB, but EmulationStation just wont show them. I'll try changing Source_RootPath but this is really making my angry lol.

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2
