### ISSUE TITLE
Create option you really want to import

### ISSUE THREAD

**Issue by azvarel** [Universal-Rom-Tools/Universal-XML-Scraper#192]
Create option you really want to import example
If you just want to make mix images, or if you want to import only the synopsis, or just the developer, etc.

**Comment by Universal-Rom-Tools** [comment]
This option exist ^^ it's the Profil ;)

If you want just "some element" and not the full profil of Retropie or Recalbox.
Make a copy of one of these profil rename it and delete element you don't want ;)
