### ISSUE TITLE
Mix images with V2.2.0.0 incomplete

### ISSUE THREAD

**Issue by SuperMagicom** [Universal-Rom-Tools/Universal-XML-Scraper#193]
When scraping with the new V2.2.0.0 I noticed that a lot of the wheel art was missing in the mix profile image for some roms.  Went back to previous version and it scraped all mix images properly.  Seems something is fubar in V2.2.0.0.

**Comment by Universal-Rom-Tools** [comment]
:( I haven't touch the "MIX part" or even the download part in the new version :(
Can you send me some log1.txt ?

**Comment by Lecrough** [comment]
I think this is my same issue. I just scrapped my NES (255 roms) last night and quite a few (40ish) only have the screenshot and box art. Some others (about 4) only have the screenshot.

Using V2.2.0.1

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2
