### ISSUE TITLE
PSX freezing when scrapping

### ISSUE THREAD

**Issue by Deltron156** [Universal-Rom-Tools/Universal-XML-Scraper#196]
So I've tried to scrap gb, gbc, n64 games and so and worked like a charm! But when it's time for psx the scrapper just stops working when hashing...
Any solution?

**Comment by paradadf** [comment]
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/wiki/ISO-Scrape-Freeze-or-are-very-long

**Comment by Universal-Rom-Tools** [comment]
Exact, it's not it just stop working... It's just it's very slow...
Read the wiki link from @Paradadf ;)
