### ISSUE TITLE
Bad name scaping MAME

### ISSUE THREAD

**Issue by molaunmazo** [Universal-Rom-Tools/Universal-XML-Scraper#201]
When I use it to scrap MAME roms, all I get is an XML with this in every rom:

	<name> (CLONE, BETA, DEMO, PROTO, TRAD, HACK, UNL)</name>

But if I check the temporal folder while scraping, it appears the it is getting the correct data, for example:

```
<jeu>
	<id>39896</id>
	<romid>197647</romid>
	<nom>Three Wonders</nom>
	<noms>
		<nom_ss>Three Wonders</nom_ss>
		<nom_us>Three Wonders</nom_us>
	</noms>
```

**Comment by Universal-Rom-Tools** [comment]
:S Weird.. I need to check :(

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2
