### ISSUE TITLE
can not scrap jaguar

### ISSUE THREAD

**Issue by pillemats** [Universal-Rom-Tools/Universal-XML-Scraper#202]
hey guys

i can scrap all my system but not jaguar.
"Rom path not found"

i use uxs 2.2 with auto config

thanks for help

**Comment by Universal-Rom-Tools** [comment]
Jaguar extension are : ".j64 .jag .zip"
And they are in the retropie profil... So normally you can scrape them...

Check your extension...

**Comment by pillemats** [comment]
with retropie config it works ! thanks !!!

**Comment by pillemats** [comment]
Hey 

I was looking forward to early

I changed the Profile to retropie, then uxs scans the folder correctly but near by the finishing i will get this report 

http://abload.de/image.php?img=img_0702vboi3.jpg

The xml an Image folder are empty

**Comment by Universal-Rom-Tools** [comment]
This error sometime happen... but I don't know why...

If you are on Retropie, use the retropie profile ;) it's way more easier than using a Recalbox Profile on Retropie :S 

Just retry and tell me if you have the error again...

**Comment by pillemats** [comment]
i have retry it but i have the same problem

i use batocera on odroid xu4. like the same as recalbox

if i use in uxs the recalbox profile i get the message "no rom folder found"
with retopie profile he finds the folder but i get the message as i written above

**Comment by Universal-Rom-Tools** [comment]
Batocera isn't supported right now (no Profile for this OS ;) )
It's a "fork" of Recalbox (I think) so the Recalbox profile must works ;)

But on Recalbox, the Jaguar isn't supported (so the extension aren't scraped)

Just go to the General option, look for the "included" extension zone, and add the jaguar extension : ".j64 .jag". It will work ;)

**Comment by pillemats** [comment]
I dont know what you mean with "Go To Extension"

The files in the Golfer has the filetype j64

**Comment by Universal-Rom-Tools** [comment]
GENERAL CONFIGURATION

and

http://img4.hostingpics.net/pics/840365Extension.jpg

add at start : 

\*.j64;\*.jag;

I can't do more....

**Comment by pillemats** [comment]
yes !!! now it works perfectly !!!

Thanks for the great support and the understanding for the noobs like me :-)

**Comment by Universal-Rom-Tools** [comment]
So I close the Issue ;)

**Comment by KingKebab** [comment]
I got the same error while trying to scrap Satellaview and Pokemon Mini romsets. Add *.bs and *.min file extension in the "General Configuration" as "Included files", solved my issue.

Current error message isn't realy relevant. Something like "Cannot found extension files to scrap in the current roms path" can be more helpfull.
