### ISSUE TITLE
Cannot find over half my games

### ISSUE THREAD

**Issue by shakeshakedown** [Universal-Rom-Tools/Universal-XML-Scraper#203]
When I run the scraper, it cannot find over half of the NES games I have.  No metadata or images or anything.  I have scoured the internet to no avail.  Am I missing something very obvious?

**Comment by Universal-Rom-Tools** [comment]
2 possibility : 
You have a bug (and I don't know wich one for now ^^)
Or you have a very strange Romset. Try to look for No-Intro Romset ;) you will have better result in scrape.

**Comment by shakeshakedown** [comment]
Strange romset indeed!  The No-Intro ones are working great.

Thank you for your help!

**Comment by Universal-Rom-Tools** [comment]
Great ;) So I close the Issue.
