### ISSUE TITLE
Selecting PNG Images ends up with *-video.png files.

### ISSUE THREAD

**Issue by alaindesjardins** [Universal-Rom-Tools/Universal-XML-Scraper#204]
When I scraped my ROMS I ended up with jpgs that didn't have transparency so I selected the PNG option but found that the scraper was now downloading large PNG files as -video.png.  When renaming the -video.png to -video.mp4 the videos played back fine but then the data in the gamelist.xml file had to be changed as well with a simple replace all -video.png with -video.mp4.

I believe the three options under advanced > Image should do as follow:
default: images without transparency should be .jpg, images with transparency should be .png and videos should remain as mp4.
jpg: both images with transparency and without transparency should be .jpg and videos should remain as .mp4.
png: both images with transparency and without transparency should be .png and videos should remain as .mp4.

Thanks!

**Comment by Universal-Rom-Tools** [comment]
You are right...

Actually, only "Default" works correctly...
When you "force" jpg or png, it force it for video too :(

I need to correct that :S

**Comment by alaindesjardins** [comment]
Hey, thanks for the quick reply!  The way I did it right now is scraped everything as PNG, added the downloaded_images on my retropie to the samba share and then did a quick command prompt rename *-video.png *-.video.mp4 .  Then I went into notepad++ and replaced all instances of -video.png with -video.mp4 in gamelist.xml.  This fixed the file name, kept all my images with transparencies and updated my gamelist.xml with the correct path.

Now to figure out why videos are playing awful, so far I figured it's rendering with software instead of hardware and I need to figure out how to fix that in retropie emulationstation.

**Comment by Universal-Rom-Tools** [comment]
Be aware that video on ScreenScraper are (normally) in the "original" format...
So if you download a GameBoy video (160×144) and try to play it in full HD (1920x1080) you may have some crappy result...

**Comment by alaindesjardins** [comment]
Yeah that's not the problem.  I got 480p videos and they play choppy/artifacts and they look fine on my PC.  I had a similar issue in attract mode and I had to recompile ffmpeg and then attract mode as well, then enable mmal video support instead of software in options.

I have two builds doing the same thing, so someone must have an answer.

**Comment by arzhurp** [comment]
I have the same issue ! 
Do you plan to correct it quickly ?

Thank you for this great software ! ;-)

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2

**Comment by dover19** [comment]
@alaindesjardins I think you just need to set USE OMX PLAYER (HW ACCELERATED) option to ON under MAIN MENU > OTHER SETTINGS in EmulationStation.
