### ISSUE TITLE
Avira AV detects TR/BAS.Dloader signature in v2.2.0.1/Universal_XML_Scraper64.exe

### ISSUE THREAD

**Issue by rickdekker** [Universal-Rom-Tools/Universal-XML-Scraper#206]
Hi All,

Am getting the below AV warning from Avira when I execute the below x64 version, I assume this is a false warning?

Download Source:  ../releases/download/v2.2.0.1/Universal_XML_Scraper64.exe

Avira Report:

Type:	File
Source:	C:\Emulation\Tools\EmulationStation Universal XML Scraper\Universal_XML_Scraper64.exe
Status:	Infected
Quarantine object:	7a55d515.qua
Restored:	NO
Uploaded to Avira:	NO
Operating system:	Windows XP/VISTA Workstation/Windows 7
Search engine:	8.03.44.28
Virus definition file:	8.12.162.50
Detection:	TR/BAS.Dloader.943b3a (Cloud)
Date/Time:	04/04/2017, 07:21

Cheers

**Comment by Universal-Rom-Tools** [comment]
Yes, unfortunatly, the language I use (Autoit) was a used a lot to create malware.
So AV make a lot's of false positive.

I contacter several AV to tell them to "allow" it.. Some were very fast to correct that, some never answer.

Sorry for the inconveniance.

**Comment by rickdekker** [comment]
No worries it's not a big problem and thanks for the quick response, have send the file to Avira as a false positive so maybe they'll have a look.
