### ISSUE TITLE
Progress Bar for gamelist.xml?

### ISSUE THREAD

**Issue by steviekeyz** [Universal-Rom-Tools/Universal-XML-Scraper#208]
Could a progress bar or something be added when the UXS is writing the gamelist.xml file? It can take a while through wifi network especially with 900+ roms. Closed the program prematurely the first time and didn't realize this. I know there is a window that pops up at the end but it can be a big delay if its a big write.

Also, slight issue sometimes when it finishes writing the XML file. It stops fine, window pops up then for some reason the XML file will go back to zero bytes on size. Then I have to redo it, which takes an hour. EmulationStation is shutdown and everything.

Anyways, great work!! Wonderful tool!

**Comment by Universal-Rom-Tools** [comment]
Wich version do you use ?
Normally on the last one, there is a Progress Bar when the XML is generating.

Can you check ?

thank you.

**Comment by steviekeyz** [comment]
Versions in Help -> About -> says 2.2.0.1.
