### ISSUE TITLE
Strange error while scraping Retropie 4.2 Snes 

### ISSUE THREAD

**Issue by orochikun** [Universal-Rom-Tools/Universal-XML-Scraper#209]
I downloaded GameWizards retropie IMG , and was scrapping the SNES rom SET, but I got a strange error message starting that it was Fucked (literally) 
![untitled](https://cloud.githubusercontent.com/assets/27264693/24893457/9a7e606a-1e38-11e7-8b70-011df6dbbe8d.jpg)

Attaching the INI file 
[UXS-config.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/912138/UXS-config.txt)
 

Current state 
![image](https://cloud.githubusercontent.com/assets/27264693/24893498/e0211004-1e38-11e7-9139-f3e2fffa40ea.png)

**Comment by Universal-Rom-Tools** [comment]
Oups... Sorry for this "badword" ^^
It was a debbuging Error message :p 

And normally, I think I will never see him again...
I think it's a temporary "problem" with the web site (The Picture you got from website can't be resized... Certainly a corrupted downloaded picture....

Can you retry and keep me up to date ?

thank you

**Comment by orochikun** [comment]
Scrapped from zero again and this time I was not cursed hahaha 
Thank you for the quick reply .

Also while I was playing with the ini I found that I could force the app to use more threads, or at least attempt to by editing the ini right after the message to kill emulation station appears

**Comment by Universal-Rom-Tools** [comment]
normally, it check the ini at every scrape to see if you have the good Max Thread number ;)
Maybe an anomally ;)
But It's just preventiv, normally the website block the too numerous threads if you aren't "premium" ;)

But the curse is gone ^^ Great :p
