### ISSUE TITLE
Games qui s'effacent du gamelist.xml apres reboot

### ISSUE THREAD

**Issue by Aigleblanc** [Universal-Rom-Tools/Universal-XML-Scraper#214]
Sur Nes et Mame quand je reboot la recalbox 4.1, il met un long moment avant de le faire sur l’écran chargement, ensuite, je me rend compte que j'ai des centaines de jeux nes et mame qui ont disparues du gamelist.xml, alors que si je ne reboot pas, ils sont bien inscrit dans le fichier avec l'image scraper, 

j'arrive pas a identifier le problème...

Edit: en remettant le fichier save avant le reboot et en nettoyant le champs descriptions des jeux a partir de la ou cela déconne, j'ai plus de problème pour le moment.

**Comment by Universal-Rom-Tools** [comment]
Il faut absolument que EmulationStation soit killé avant de scraper...
sinon il recharge ce qu'il avait en memoire au moment de la fermeture (et donc supprime ton scrape.)

**Comment by Aigleblanc** [comment]
Bonjour,

Merci pour la réponse, mais le soft n'est pas justement censé killer EmulationStation ?

Enfin, tout est rentré dans l'ordre, merci pour le super travail mis a disposition en tout cas.

**Comment by Universal-Rom-Tools** [comment]
Si :'( il est censé le faire...

mais il arrive, qu'il n'y arrive pas ^^

dans tous les cas, il vaut mieux checker ;) (l'écran doit devenir noir sur le PI ;) )
