### ISSUE TITLE
Don't work on linux ...

### ISSUE THREAD

**Issue by manatlan** [Universal-Rom-Tools/Universal-XML-Scraper#215]
Or change the name : it's clearly not universal ;-)
(It **only** works on win's platforms)

**Comment by Universal-Rom-Tools** [comment]
Universal is for : you can scrape any plateforme with any front end...
just need some litle easy tweak for that.

but feel free to fork and make a linux version ;)
I can help if you want...

Don't hesitate to look here too : @ #200
