### ISSUE TITLE
Stop putting default image for games it can't find images?

### ISSUE THREAD

**Issue by Jaxel** [Universal-Rom-Tools/Universal-XML-Scraper#217]
If UXS can't find images for a game, or information on a game, it creates a "default" image for that game. It would be better if it simply didn't create and image at all... and possibly don't even add it to gamelist.xml. This way its easier to manually scrape it later since Emulation Station will detect it as a game without an image.

**Comment by Universal-Rom-Tools** [comment]
Hum... strange...
If UXS don't found a game, normally it add nothing (exepted if you check "missing rom" in the General config)

Need to check that :S

**Comment by Jaxel** [comment]
Nope, it definitely adds default images. I have hundreds of games with "Flashback/AnotherWorld" images; since those are the defaults.

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2
