### ISSUE TITLE
XML creation problem

### ISSUE THREAD

**Issue by pillemats** [Universal-Rom-Tools/Universal-XML-Scraper#219]
I have tried with all settings to scrape
- only CRC
- only filename
- CRC + name
- create new xml
- expand xml
And I have also set the hook at "add roms"

Now I get every time a different result and he shows me in recalbox always different roms.

In the folder "downloaded-images" are 100% of all games as a picture, so this is apparently just a mistake from the creation of the xml file

No matter what setting I make he always creates an xml file where games are missing. Times are missing these and times this. i don't understand that !

I have just deleted the xml file times completely and scrap now with the settings "CRC + Filename" + "create new xml" without hook at "roms add"

I hope he now created an xml with 100% of my roms

Have I set a setting wrong?

Please help

Thank you

**Comment by Universal-Rom-Tools** [comment]
The "standard" setup is : 
- CRC + name
- create new xml

Search mode is the way UXS try to match your rom to the DB (so in this case : by CRC and if not found, by filename)
Scrape Mode is the way UXS handle an existing XML file so New will erase the existing and create a new one, Update only try to fill the existing XML with new rom. (to gain time, it will not regenerate an existing picture. You need to delete it to regenerate)
Add missing rom tell UXS to create a "blank" entry in the XML if a rom isn't found. (but the update process will not work after that. Update simply add missing rom, not really update missing info)

You also have "Unzip file" if you want. In the case UXS don't found a match by CRC or Filename it will try to unzip file to check the inner file by CRC and/or Filename...

If you haven't a 100% XML at the end, maybe it's the DB laking for some game. Check on http://www.screenscraper.fr and add the missing info ;)
