### ISSUE TITLE
Adding not found rom to XML

### ISSUE THREAD

**Issue by Universal-Rom-Tools** [Universal-Rom-Tools/Universal-XML-Scraper#22]
Adding empty picture for the missing rom.

[Sassa]

**Comment by paradadf** [comment]
If you implement this feature, please make it optional (and better, turned off by default)

**Comment by Universal-Rom-Tools** [comment]
The aim is to implemente a function to scrape missing rom and put an entry in XML, with MIX (even if empty)

It's an option in General configuration
