### ISSUE TITLE
No second image

### ISSUE THREAD

**Issue by berrani** [Universal-Rom-Tools/Universal-XML-Scraper#221]
During scraping I chose as 1st image "2d box" and as 2nd image "screenshot", at the end all the images are  downloaded (1st + 2nd), but the xml file has only the 1st "2d box" and game without "2d box" are empty: is there something I did wrong?
Thanks

**Comment by Universal-Rom-Tools** [comment]
Did you check on http://www.screenscraper.fr the Screenschot exist ?
