### ISSUE TITLE
Blank XML file and scraping for missing images only

### ISSUE THREAD

**Issue by KingofMetal79** [Universal-Rom-Tools/Universal-XML-Scraper#222]
Good Morning,
 I too have a similar question to one previously raised (see closed question - #172)

 I have attempted scraping for PCEngine roms and twice it has crashed before scraping is completed and gave the standard Windows notice that the programme has stopped working and shut Universal XML scraper down. When I have gone into the game_images folder on the RetroPie I can see the mix images that had been downloaded up until the crash, however the XML file is blank. Therefore how do I simply create an XML file without the need to download the images again? 

I assume I just choose General Conf >> Scrape Mode >> Option 1 and re-run?

Kind regards

**Comment by Universal-Rom-Tools** [comment]
UXS will never "redo" the MIX if they already exist ;) (except with the option : Scrape mode = only picture)
so normally, just relaunch you scrape.. It will be OK.
