### ISSUE TITLE
SOS Release Date "Unknown"

### ISSUE THREAD

**Issue by micropixel70** [Universal-Rom-Tools/Universal-XML-Scraper#224]
Hi I have a problem with Universal XML Scraper, any release date gives me visibility as unknown, do you know why?

The generated hundred is only for the year here is an example:

19910000T000000

To be correct must be as well as does selph scraper:

19910313T000000

Thanks for the wonderful work you did with Universal XML Scraper! :-)

**Comment by Universal-Rom-Tools** [comment]
Some date on the DB are with Day/month/year... but some are only with Year...
In that case, UXS don't handle it right... I need to correct that...

**Comment by micropixel70** [comment]
Thank you! I hope you'll fix it soon ... so it would be perfect! :-) sselph scraper no nha this problem, but I prefer your program :-)

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2
