### ISSUE TITLE
Add missing rom in XML question...

### ISSUE THREAD

**Issue by Dragontorc** [Universal-Rom-Tools/Universal-XML-Scraper#225]
When "Add missing rom in XML" option is checked, all ROM files that I have and are not found by UXS seems to be added to the XML file however all are shown in ES as:

(Clone, Beta, Demo, Proto, Trad, Hack, Unl)

Is there any setting in UXS that would actually use ROM filenames rather in the gamelist.xml?

**Comment by Universal-Rom-Tools** [comment]
It's a known bug ;)

I need to correct it...

But if you want, you can choose the filename format in options menu :)

**Comment by Dragontorc** [comment]
Thanks.  I'll wait patiently :-)

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2

**Comment by Dragontorc** [comment]
Hate to say it, but downloaded on my W7 machine and UXS crashes each time I try to scrape one of the systems.  Also tried to download on my W10 machine byt download fails due to "virus" detected by Win Defender.
