### ISSUE TITLE
Missing roms / fallback on name?

### ISSUE THREAD

**Issue by sinedied** [Universal-Rom-Tools/Universal-XML-Scraper#226]
I'm trying to scrape my psx isos, but most of them are custom .pbp and .img made from my own dumps or converted from existing .cue/.bin dumps.

Since matching is only based on file hash, nothing matches. For PSX isos, this is really problematic due to the numerous formats and versions availables.

I also saw that there is no easy way to add rom/iso hashes to the screenscraper database, and I'm sure they won't be happy if everytime I dump a new game I have to send them the hash via IRC (also, it's really bothering...).

Is there a way that for missing matches we could perform "manual" macthes using name and searches?
Or at least a local fallback db to match personal iso hashes against screenscraper games?

Thanks for the great tool anyways 👍

**Comment by Universal-Rom-Tools** [comment]
Matching are not only based on Hash ;)

In configuration / General configuration, you can choose "Filename only".

The counterpart is you need to rename your file like a "standard" or at least referenced filename in the DB.

The Manual Match isn't possible actually with the Screenscraper API...
An API V2 is in progress, but not sure it will be added.

**Comment by sinedied** [comment]
Nice, didn't know that :) I'll try this as it seems to be the simplest way for this.
Still, it would be nice to have an easier way to submit new hashes to the DB, via the app or the website.

**Comment by sinedied** [comment]
Hmmm I tried many things, there's still games not matched with the DB, even though I tried every solution: the "internal" screenscraper name, every listed filenames, adding tags like (Europe), (USA)...

What is used as a base for a filename match?

A "simple" fallback solution would be to allow to link URL or hash of the supposed match in the missing txt file, so the scraper automatically does the fallback, or even submit the matches, what do you think?

**Comment by Universal-Rom-Tools** [comment]
Sorry as I say, the API cannot return something based on URL or ID (manual match is just impossible for now... maybe in the future...)

For the name matching. It's only on a "strict" filename matching (to catch the rom country).
You can look at the very end of a game url (exemple : https://www.screenscraper.fr/gameinfos.php?plateforme=14&gameid=5396 ) you will have all the referenced roms with their names.

That's the reason it's always bad to rename romset ;)
