### ISSUE TITLE
Bring back auto save into rom folder

### ISSUE THREAD

**Issue by a7mag3ddon** [Universal-Rom-Tools/Universal-XML-Scraper#230]
In the earlier version of UXS it used to automatically save gamelist.xml and downloaded_images into whatever Rom folder you were scraping, it no longer does.

Can you bring it back as an option like it used to ?

**Comment by Universal-Rom-Tools** [comment]
I just added it in the next version ;) and it work ;)
So wait tomorrow (or tonight) for the next release, you will have a new Advanced Menu : "Use Alt Autoconf Path"

**Comment by a7mag3ddon** [comment]
It worked before, why did you have to remove it ?

**Comment by Universal-Rom-Tools** [comment]
Because I change how the profile are handled... before you have a lot's of profile and it's not very "nice". Now you have 2 profiles : Recalbox & Retropie. With a lot's of options in them ;)

Don't worry. I realese the new version tomorrow with this "option" ;)

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2
