### ISSUE TITLE
Problem connecting to database

### ISSUE THREAD

**Issue by caerwin** [Universal-Rom-Tools/Universal-XML-Scraper#231]
Hello, 

I am trying to run v2.2.0.1 for the first time (tried earlier versions too) and I keep getting a fatal error that it cannot connect to the database.  How can I fix this?

Thank you!

**Comment by AntoineLemaire** [comment]
screenscraper.fr seems to be down right now.
Just need to wait :/

**Comment by Universal-Rom-Tools** [comment]
Just test, and all is good...

Is it the same for you ?

**Comment by AntoineLemaire** [comment]
That was just yesterday morning. I had the same error, it has been fixed as soon as screenscraper.fr was back online

**Comment by Universal-Rom-Tools** [comment]
Ok, thank you, I close the Issue
