### ISSUE TITLE
Wizard - Screenscraper connexion with 20 length password

### ISSUE THREAD

**Issue by AntoineLemaire** [Universal-Rom-Tools/Universal-XML-Scraper#232]
Hello,

When the wizard ask for a screenscraper.fr account, it doesn't accept 20 length passwords. 

![wizard20](https://cloud.githubusercontent.com/assets/2025537/26282416/6e666916-3e11-11e7-8023-4473e28ee0ed.png)

19 length passwords are working.

![wizard19](https://cloud.githubusercontent.com/assets/2025537/26282414/61d19180-3e11-11e7-9ed1-3814bb49c6da.png)

After in the General config panel, connect with a 20 length password works as well.

![config20](https://cloud.githubusercontent.com/assets/2025537/26282411/56c1ddfe-3e11-11e7-92c0-7f346fbf2b02.png)

You can test with thoses two test accounts:

login: screenscraper19
pass: abcdefghijklmnopqrs

login: screenscraper20
pass: abcdefghijklmnopqrst

**Comment by Universal-Rom-Tools** [comment]
Solved in the next version ;) (forgoten a "tag" in the Wizard ;) Input)

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2

**Comment by AntoineLemaire** [comment]
It's fixed! Thanks for your reactivity 👍
