### ISSUE TITLE
Gamelist.xml not updated during scraping

### ISSUE THREAD

**Issue by Drovitch** [Universal-Rom-Tools/Universal-XML-Scraper#238]
Hi all,

When scrapping with Universal XML Scraper on my Recalbox, images are well downloaded but gamelist.xml is not updated, hence image are not displayed on my Recalbox. I tried several time without sucess...
Thanks for your help.

**Comment by Universal-Rom-Tools** [comment]
Are you sure your EmulationStation was killed before Scrape ?

You can kill ES : 
With the SSH menu in UXS
Before UXS start scraping it ask you to kill ES
you can do it on your own with Putty on connecting in SSH to your PI

In every case : Your Recalbox must show a black screen (not the Menu screen)
If not, after Recalbox Restart, it delete your scrape and you only have picture, but no gamelist...

**Comment by Drovitch** [comment]
Thanks for your quick reply.
Druing first try it seems that I replied yes to kill my ES. Trying now using SSH it seems work fine: gamelist is well updated. I let the current scrap goes until the end to check again.

**Comment by Drovitch** [comment]
Just one question, Does xml updated in realtime or only at the end of the scrap ?

**Comment by Universal-Rom-Tools** [comment]
only at the "end" (when you cancel or when it's finish). 
The last version offert you to create the XML file in case of "crash" with the temporary file he found.
You can do an "update" after that ;)

**Comment by dedetubarao** [comment]
olá, estou com o mesmo problema, no meu recalbox ocorre a mesma coisa, já tentei de tudo, quando termina de baixar as imagens a tela fica ainda carregando e não sai disso, as imagens são baixadas, mas não aparecem no recalbox, o problema acho q é a gamelist do recalbox.  alguém pra ajudar?
