### ISSUE TITLE
Force UXS to find a specific game?

### ISSUE THREAD

**Issue by Jaxel** [Universal-Rom-Tools/Universal-XML-Scraper#242]
Tales of Phantasia for the PSX is my favorite game of all time. Unfortunately, it was only ever released in Japan. So I rip the disc, and apply a translation patch from Absolute Zero Translations for it. When I run UXS on my PSX directory though, it finds all games and creates images for them, except Tales of Phantasia.

Is there any way I can force UXS to fetch an image for Tales of Phantasia?

I have tried renaming my file to `Tales of Phantasia (Japan).cue` as listed on:
https://www.screenscraper.fr/gameinfos.php?plateforme=57&gameid=19340

However, it doesn't seem to work. It always ends up with a 0 byte image.

**Comment by Universal-Rom-Tools** [comment]
Normally it works like you did... renaming a rom with a referenced one is ok. But you must be carrefull on the Search mode (on general option) it must be "by filename" (or "by hash + filename")

**Comment by Jaxel** [comment]
Ah... that works... I am having an issue where the 4-image layout doesn't seem to always get completed. For instance:

Bushido Blade 2
`https://screenscraper.fr/gameinfos.php?plateforme=57&gameid=19766`

This has all the information required to make a 4-image layout except the CD. But when UXS makes a Mix for it, it only takes the screenshot. It doesn't put on the marquee or the box art.

**Comment by Universal-Rom-Tools** [comment]
Just check Bushido Blade 2 : 
For information, media weren't "well" country tagged... exemple : The cover was tagged as Europe. But no EU rom exist, only US or JAP. After check, the cover on ScreenScraper was a US one (checked the ESRB ;) ) So I redim and retag it...

For info bis : Media are catch with "matching" country. So if your rom is US it will take the US cover... There is fallback... But EU isn't a fallback in the US language profil.

Normally, if you rescrape Bushido Blade 2, it will be OK.

If you found other error like this one, just put a comment on Screenscraper ;) We will make the correction ;)

**Comment by Jaxel** [comment]
So I switched my searching method to "filename" and almost everything works out. However, I can't seem to match two games for the PSX... no matter what names I put them:

    Oddworld - Abe's Exoddus 
    Oddworld - Abe's Oddysee

**Comment by Jaxel** [comment]
Has anyone else been able to repeat this issue?

**Comment by Jaxel** [comment]
Okay, same issue exists with `King's Field`... so I definitely think its the apostrophe.

**Comment by Universal-Rom-Tools** [comment]
The new 2.2.0.3 will be ok with apostrophes ;)
Can you try it ?
