### ISSUE TITLE
Buggy version 2.2.0.2

### ISSUE THREAD

**Issue by vsabard** [Universal-Rom-Tools/Universal-XML-Scraper#243]
Hello
Tool is always failing during scraping for unexpected reason.

Please find below error detail for application logged by windows:

Nom du journal :Application
Source :       Application Error
Date :         30/05/2017 22:22:43
ID de l’événement :1000
Catégorie de la tâche :(100)
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   Home-PC
Description :
Nom de l’application défaillante Universal_XML_Scraper64.exe, version : 2.2.0.2, horodatage : 0x5921d68b
Nom du module défaillant : unknown, version : 0.0.0.0, horodatage : 0x00000000
Code d’exception : 0xc0000005
Décalage d’erreur : 0x000001f7a5b37420
ID du processus défaillant : 0x1e98
Heure de début de l’application défaillante : 0x01d2d9822caafc94
Chemin d’accès de l’application défaillante : C:\Users\Home\Downloads\Universal XML screenscraper\Universal_XML_Scraper64.exe
Chemin d’accès du module défaillant: unknown
ID de rapport : c9bcd3ea-8b5b-4f00-9b55-3feedae6ebf0
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-05-30T20:22:43.196708900Z" />
    <EventRecordID>676</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Home-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Universal_XML_Scraper64.exe</Data>
    <Data>2.2.0.2</Data>
    <Data>5921d68b</Data>
    <Data>unknown</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>c0000005</Data>
    <Data>000001f7a5b37420</Data>
    <Data>1e98</Data>
    <Data>01d2d9822caafc94</Data>
    <Data>C:\Users\Home\Downloads\Universal XML screenscraper\Universal_XML_Scraper64.exe</Data>
    <Data>unknown</Data>
    <Data>c9bcd3ea-8b5b-4f00-9b55-3feedae6ebf0</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by Universal-Rom-Tools** [comment]
We are on investigation on the #236 ;) 
I think the problem is the same... So I close this Issue to keep all problem in only one ;)
