### ISSUE TITLE
"downloaded_images" folder nbot found when setting custom advanced paths

### ISSUE THREAD

**Issue by mattborkin** [Universal-Rom-Tools/Universal-XML-Scraper#244]
Hello,

Love your program!  This is more of a convenience interface request, rather than a bug, perhaps... But when setting the paths under advanced configuration, all of the path set properly until you get to the downloaded images portion.  

The prompt takes you to the correct rom directory and auto-fills the 'downloaded_images" path, but you can't hit OK and then it tells you that the directory doesn't exist.  Since this is what most people use as their media directory, is there any way that if the user hits OK without specifying a new directory, that it's assumed that they want it in the defaults, "downloaded-images:" directory, and it (XML) automatically creates the folder/directory.  That may save some time and increase the flow.

Thanks, 

Matt!

**Comment by Universal-Rom-Tools** [comment]
31 May 2017 >< Sorry for the "very" long delay to answer.

You should use the "autoconf path" for that ;) if you do it the "manual" way, you have to manually create what is needed ;)
