### ISSUE TITLE
Avast alarm on Version 2.2.0.3: IDP.Generic and IDP.Alexa.51

### ISSUE THREAD

**Issue by flaviorabello** [Universal-Rom-Tools/Universal-XML-Scraper#249]
After updating to version 2.2.0.3 today, my Avast AV started recognizing it as a trojan: IDP.Generic and IDP.Alexa.51

**Comment by flaviorabello** [comment]
using: Universal_XML_Scraper64.exe

**Comment by greengeek1** [comment]
see https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/issues/240
