### ISSUE TITLE
Dots in file names

### ISSUE THREAD

**Issue by rgponce** [Universal-Rom-Tools/Universal-XML-Scraper#250]
Using search by name UXS miss game with dots in file names, games like: U.N. Squadron and E.V.O. - Search for Eden

**Comment by nestorcamacho** [comment]
Any news about this API problem?

**Comment by Universal-Rom-Tools** [comment]
Need to investigate :S

**Comment by Universal-Rom-Tools** [comment]
It's normally ok (from a long time now ^^)
