### ISSUE TITLE
Crash on startup with Win XP

### ISSUE THREAD

**Issue by GuZzO80** [Universal-Rom-Tools/Universal-XML-Scraper#251]
Every time i tried to launch the software, it starts, i choose French as language and then the first screen appears and immediatly the Windows error message appears too....

I know this OS is outdated but i only have a laptop with Windows XP right now...
Is it a known issue that it does not work with XP ? Or could i do it with missing DLL or something else ?

**Comment by Sined66** [comment]
I confirm, no way for XP (even the 32 bits version)...

**Comment by Tsunamii** [comment]
having the same issue with Win 7... :(
tried both the 32bit and the 64bit version, even with admin mode

**Comment by Universal-Rom-Tools** [comment]
Sorry, Never try on XP... It's should work (I hope)
For Seven, it work ;) Just take care about Antivirus or Firewall ;)

**Comment by pc77** [comment]
tried in two computers with win7 and got the same issue

**Comment by Universal-Rom-Tools** [comment]
Is UXS is in it's own folder ? not at the root folder of a drive ?
It can happen in this case...

pc77 open a new Issue for you crash on W7 and give me a "log" or an error screenshot I can investigate on ;)
