### ISSUE TITLE
Duplicate Names on PSX games on Recalbox

### ISSUE THREAD

**Issue by sismo99** [Universal-Rom-Tools/Universal-XML-Scraper#253]
Thats it in recalbox it appears 2 names for each game and only one has the info scrapped (text an image) the weird thing is that the two names for each game are different example: 
Dino Crisis (USA)
Dino Crisis (S)

And only one has scrapped info (The cue and the binb have exactly the same name )

Hope yoy can help me

**Comment by paradadf** [comment]
Just for reference:
https://forum.recalbox.com/topic/8053/duplicate-names-on-psx-games-on-recalbox-using-uxs-scrapper/

**Comment by Universal-Rom-Tools** [comment]
The easiest way : 
In General Config, only when you scrape PSX (or CUE/BIN rom folder) add BIN to the delete .BIN from roms scraped.

You will have a line with : 
`*.32x;*.a26;*.a78;*.bin;*.cbn;*.ccd;*.cdi;*.chd;*.col;*.cso;*.cue;*.d64;*.do;*.dos;*.dsk;*.exe;*.fba;*.fds;*.gb;*.gba;*.gbc;*.gc;*.gcz;*.gdi;*.gen;*.gg;*.img;*.iso;*.lnx;*.lua;*.lutro;*.md;*.mgd;*.mgw;*.moonlight;*.mx1;*.mx2;*.n64;*.nes;*.ngc;*.ngp;*.nib;*.p;*.pbp;*.pc;*.pce;*.po;*.rom;*.rzx;*.scl;*.scummvm;*.sfc;*.sg;*.sgx;*.smc;*.smd;*.sms;*.st;*.stx;*.t64;*.tap;*.trd;*.tzx;*.v64;*.vb;*.vec;*.wad;*.wbfs;*.ws;*.wsc;*.x64;*.z64;*.z80;*.zip;*.zx80||`

Just copy past this : 
`*.32x;*.a26;*.a78;*.cbn;*.ccd;*.cdi;*.chd;*.col;*.cso;*.cue;*.d64;*.do;*.dos;*.dsk;*.exe;*.fba;*.fds;*.gb;*.gba;*.gbc;*.gc;*.gcz;*.gdi;*.gen;*.gg;*.img;*.iso;*.lnx;*.lua;*.lutro;*.md;*.mgd;*.mgw;*.moonlight;*.mx1;*.mx2;*.n64;*.nes;*.ngc;*.ngp;*.nib;*.p;*.pbp;*.pc;*.pce;*.po;*.rom;*.rzx;*.scl;*.scummvm;*.sfc;*.sg;*.sgx;*.smc;*.smd;*.sms;*.st;*.stx;*.t64;*.tap;*.trd;*.tzx;*.v64;*.vb;*.vec;*.wad;*.wbfs;*.ws;*.wsc;*.x64;*.z64;*.z80;*.zip;*.zx80||`

(and reverse for the other folder)
