### ISSUE TITLE
Wrong country name is chosen?

### ISSUE THREAD

**Issue by verybadsoldier** [Universal-Rom-Tools/Universal-XML-Scraper#254]
I try to scrape a Dreamcast game "Virtua Tennis - Sega Professional Tennis (Europe) (En,Fr,De,Es).gdi" which should resolve to this I guess:
https://screenscraper.fr/gameinfos.php?plateforme=23&gameid=13556

So the game name for all countries except Japan is "Virtua Tennis". For Japan it is "Power Smash". But in the end in my gamelist.xml it still shows up as "Power Smash":
```
<game id="13556" source="ScreenScraper">
	<path>/home/vbs/RetroPie/roms/dreamcast/Virtua Tennis - Sega Professional Tennis (Europe) (En,Fr,De,Es).gdi</path>
	<name>PowerSmash [Europe]</name>
```

This my config:
![image](https://user-images.githubusercontent.com/364469/27609145-32a2b196-5b8a-11e7-97fc-4b96e728e3b3.png)

So what can I do to get the Europe or US name ("Virtua Tennis") in my gamelist.xml?

Thanks!

**Comment by Universal-Rom-Tools** [comment]
Arg ... Issue from "Jun" ><

Can you retry ? it should be ok right now ^^
