### ISSUE TITLE
SUGGESTIONS TO CORRECT BUGS AND ERRORS ON UXS V2

### ISSUE THREAD

**Issue by andrellvs** [Universal-Rom-Tools/Universal-XML-Scraper#255]
**First** of all I would like to thank you for the great work done by **"Universal-Rom-Tools".**
----------------------------------------------

**UNIVERSAL** XML **SCRAPPER**

1 - UXSv2 bug and pretend to download images of covers, when scraping in "image" folders that do not yet exist in RETROPIE. This forces me every time I am going to do scrap, go in CONFIGURATION / ADVANCED / PATH SETTINGS / PASTE TO WHICH PICTURES WILL BE DISCHARGED: - And add a " \ " at the end of the path

Ex: \\ retropie \ configs \ all \ emulationstation \ downloaded_images \ gba \ <<<< - here
1 (SOLUTION) - Include the " \ " at the end of the image folders path for all systems.

2 - UXSv2 crashes when scraping folders with ".7z" files.
2 (SOLUTION) - Include the native ".7Z" format. I have already tried doing this by updating the settings manually, but it, upon rebooting, stubbornly deletes.

3 - UXSv2 could for every rom not found, create an identical generic scrap at all, with a photo of a cartridge chip or something.

4- UXSv2  - killall message "Are you sure you want to stop emulationstation?" - It could only be replaced by a warning, without requiring user confirmation such as: "After completing the process, restart EMULATIONSTATION!"

**UNIVERSAL** XML **EDITOR**

I suggest for this program support linked to "google trasnlate", so that it can translate the DESCRIPTIONS of the games.
I also suggest a shortcut button, to navigate between ROM DESCRIPTIONS with facility.
I suggest he can do these processes in an automated way.

Similar program: XML-CONTENT-TRANSLATOR - This program does almost this, but still, manually, which makes REGIONALIZATION of rom descriptions difficult.

**Comment by Universal-Rom-Tools** [comment]
Hi,

1- Strange, first time I have this issue ? You can (if you want) automate the "/" process by editing Autoconf path.. Look for this path : %host%\configs\all\emulationstation\downloaded_images\\%System% and add the '/' at the end ;) (You can do it in the retropie.xml file in ProfilesFiles Folder or directly in the Menu ;) )

2- I'm not sure and don't want to say crap, but Retropie handle 7z ??? not sure ;) anyway, I need to test some... but in all case, Screenscraper DB haven't 7z hash (or at least very few)... you better have to unzip them ;)

3- You already can, in General config, just check "Missing rom", it will add an entry for missing rom in your XML and, if you choose a MIX with a "empty" visual, it will put it in (like the "Arcade" Mix ;) )

4- At first, it was just a warning ;) and I have so much people who don't kill ES and complain it don't work I put it as a "obligation" (in all case, it's an obligation ;) )

Concerning Translation, The best way is to participate to the ScreenScraper DB and put you work on it ;) (so every one can have your translation :D and you can scrape without editing)

(For now UXE is in a really standby state... not so much time :( )
