### ISSUE TITLE
ERROR GENERATING THE PATH OF IMAGES IN XML

### ISSUE THREAD

**Issue by andrellvs** [Universal-Rom-Tools/Universal-XML-Scraper#256]
First of all, to post the text of the xml, I replace the symbols: <.> By: [.]
------------------------------
When creating XML I realized that several games were left without the image in raspberry-pi, observing the XML discovered the error. Take the example XML clipping below:
---------------------------------------------------------------------------------------
[name]4 Nin Uchi Mahjong [Japan][/name]
	[desc]This is a generic and very primitive mahjong game.  It  is Nintendo's second mahjong game made for the Famicom, the first titled simply Mahjong.</desc>
	[image/]
	[image]/home/pi/.emulationstation/downloaded_images/nes/4 Nin Uchi Mahjong (Japan)-image.jpg[/image]

--------------------------------------------------------------
Unnecessarily, in certain games, it creates a markup: [image /], above the line of the path that goes to the image:

[Image /]
[Image] /home/pi/.emulationstation/downloaded_images/nes/4 Nin Uchi Mahjong (Japan) -image.jpg [/ image]

And I just need to re-edit XML in NOTEPAD ++, otherwise I get incomplete SCRAP.

**Comment by Universal-Rom-Tools** [comment]
Already known... I need to check why :S 
-> #252
