### ISSUE TITLE
Absolutely Cannot Get My Scrapes Working...

### ISSUE THREAD

**Issue by BeatDownByUXS** [Universal-Rom-Tools/Universal-XML-Scraper#257]
Hi everyone,

I'm new here & posting as a last resort. I recently built a Retro system w/ a Raspberry Pi 3 running Retropie. I am using a Sandisk 128gb card. Assembly was easy, straightforward and went off beautifully. Everything has been working flawlessly for weeks, EXCEPT my UXS scrapes; which I cannot get to work despite many hours of YouTube videos & internet searches. I was so desperate, I actually reformatted the card twice, wiping everything and starting from scratch, which as you know takes a lot of time. Still no results. My screen is gray and either no artwork, or when I choose a game and select it, I see this small version of the MIX artwork at the top left of the screen. Usually, I just see nothing but the names of the games, a description, rating, etc. All in a gray color format and the layout id different than the Screech version as well.

Here is what transpires when I scrape:

I use WinSCP to access my Pi via hardwired network

Open UXS, choose the 3 img MIX,, choose a system to scrape, etc.

Start to scrape, it asks if I want to kill emulation station, I click yes. I can still see emulation station on the computer screen next to me that the Pi is hooked to, not sure if that is normal.

Scraping starts and in the taskbar of USX, it says "Hashing" in front of every game as it moves along.

Scraping ends, I get "scrape results" saying "Roms found present" is 100% every time.

I look inside Retropie, I can see all the gaming system folders in the "downloaded images" folder, I open each system folder and can see that the artwork is inside the folders.

I reboot my Pi or restart emulation station only to see the same gray screen with no Screech scrapes present on screen. So they appear to be on the Pi, but will not display for me.

As I said, I have logged many hours trying to solve this! Can someone please help me? Does anyone know why this is happening or heard of this before? Every video I see shows it working easily & I can find zero "troubleshooting" information for the UXS scraper.

Also, if anyone is willing to help me, please request my email & we can email or talk on the phone. I took several screenshots of everything mentioned above.

Thanks, 

Jon

**Comment by paradadf** [comment]
You MUST shut down EmulationStation before scrapping or transfering the gamelist.xml to your rom folder on the Pi. As you are still seeing ES even after "shutting it off", that means it is still running.

**Comment by Universal-Rom-Tools** [comment]
Or maybe a problem with the SSH connection from UXS to your PI...

Check this to be sure SSH works : https://www.youtube.com/watch?v=4RrspvwZhvQ
And check your credential in UXS to be sure you have the good one...
(Or eventually, kill Emulationstation yourself BEFORE scraping ;)

In every case, Emulations MUST be killed BEFORE the scrape generate the gamelist.xml.

**Comment by Universal-Rom-Tools** [comment]
No news.. I hope it's ok now...
