### ISSUE TITLE
Marquee is not transparent

### ISSUE THREAD

**Issue by McSwindler** [Universal-Rom-Tools/Universal-XML-Scraper#258]
Visual type is simple visual, I have set the Marquee option to download the 'Wheel' image. 
The image gets saved as a jpg instead of a png with a transparent background. This leaves a dark-green background on the logo.

Did I miss a configuration option, or is this a bug?

**Comment by DieKatzchen** [comment]
Configuration -> Advanced -> Pictures Configuration. Set it to png.

**Comment by McSwindler** [comment]
Thanks! That worked perfectly.
