### ISSUE TITLE
[ADD] Add the Recalbox Mix to UXS

### ISSUE THREAD

**Issue by Fab2Ris** [Universal-Rom-Tools/Universal-XML-Scraper#261]
I have advanced in the encoding of my collection of PS1 games (400+...)
I scrapped the file with UXS from @screech
A major part is recognized (quite impressed level of precision for personnal rip !)

For the rest, the search integrated in Recalbox is absolutely brilliant (and cruelly lacking UXS ...) to complete / fine-tune its scrap, thanks to the possibility to choose in case of lack / doubt / conflict, in a selection of results on Screenscraper. Absolutely Topissime!

Disadvantage (minimal, but ...): the image mix Recalbox (very nice!) Is not quite the same as the Mix 3 images by default of UXS.
So the gamelist is not totally homogeneous ...

Is it possible to add the Mix Recalbox to UXS (since you can not add mixes) ... or add the default mix UXS to Recalbox?

Thanks for your feedback !

/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/

Bonjour à tous,

J'ai pas mal avancé dans l'encodage de ma collection de jeux PS1. (+400...)
J'ai scrapé le dossier avec UXS de @screech
Une majeure partie est reconnue (assez épaté du niveau de précision pour des rip perso !)

Pour le reste, la recherche intégrée à Recalbox est absolument géniale (et manque cruellement à UXS...) pour compléter/peaufiner son scrap, grâce à la possibilité de choisir en cas de manque/doute/conflit, dans une sélection de résultats sur Screenscraper. Absolument topissime !

Inconvénient (minime, mais...) : le mix image Recalbox (très joli!) n'est pas tout à fait le même que le Mix 3 images par défaut de UXS.
Du coup la gamelist n'est pas totalement homogène...

Est-il envisageable d'ajouter le Mix Recalbox à UXS (vu qu'on peu visiblement ajouter des mix)... ou ajouter le mix par défaut UXS à Recalbox ?

Merci pour votre retour !

**Comment by Universal-Rom-Tools** [comment]
The MIX from Recalbox is directly generated by ScreenScraper WebSite, I need some extra info from the ScreenScraper boss ;) and I'll can make a new MIX for UXS ;)

/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/

Le MIX de Recalbox est généré directement par le Site ScreenScraper, j'ai besoin d'info supplémentaire du Big Boss du Site et je pourrais en faire un MIX pour UXS ;)

**Comment by paradadf** [comment]
This can be closed already.

**Comment by Universal-Rom-Tools** [comment]
You are right ;) It's done ;)
