### ISSUE TITLE
Error: Subscript used on non-accessible variable.

### ISSUE THREAD

**Issue by azvarel** [Universal-Rom-Tools/Universal-XML-Scraper#264]
![image](https://user-images.githubusercontent.com/129056/28964663-1551503a-78e4-11e7-916e-958b3609a418.png)

[log.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/1199980/log.txt)

**Comment by Universal-Rom-Tools** [comment]
What I see from your log : 

/!\ Error Downloading File : E:\Raspberry Pi\Universal XML Scraper-2.x\Ressources\ServerList.txt

So UXS can't connect to Internet (it try to download this file : [ServerList.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/blob/master/Ressources/ServerList.txt) directly on Github and can't... )

So check your antivirus / firewall ;)

**Comment by azvarel** [comment]
I disabled the firewall and the antivirus and continue with the error!
I delete the log file and the UXS generated new log.
[log.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/1206473/log.txt)

**Comment by azvarel** [comment]
This problem occurs with the last update of windows 10, I just test in a virtual machine with windows 10 without being updated and worked normally. It's good to check what's going on.

**Comment by azvarel** [comment]
After upgrading windows 10 to build 15063 the UXS reopened normally

**Comment by santiagomoneta** [comment]
I have the latest windows 10 pro (1709) on a VM and I got the error. I do notice that when I wanted to download it from the VM
<img width="1006" alt="2018-04-20_0951" src="https://user-images.githubusercontent.com/8931496/39051886-75f22c58-4480-11e8-9af4-b38b3cef8776.png">
 I went to GitHub and got an untrusted paged with no option to proceed

**Comment by rkkoszewski** [comment]
Getting the same error as the first post. This is definitely not fixed.

**Comment by JmB11** [comment]
Hi, i have found something interesting with this issue : 
it seems that AutoIT uses Internet Explorer as download tool...
So what I did was to open the old Internet Explorer in Windows 10, then configure it to be able to access the folowing url : https://raw.githubusercontent.com/Universal-Rom-Tools/Universal-XML-Scraper/master/Ressources/ServerList.txt
When done I ran Universal-XML-Scraper again and no more error 👍
