### ISSUE TITLE
UXS can't scrape game that already scraped with default retropie scraper

### ISSUE THREAD

**Issue by dicktivity** [Universal-Rom-Tools/Universal-XML-Scraper#265]
hello. i need help. i don't know about coding and stuff, this is my first time using retropie and uxs
and i have this problem where uxs can't scrape some of my game that i already scraped with default scraper form retropie. it will just back to the original file name, if i try to scrape it with default scraper my retropie will hang. i try to reinstall retropie to my raspberry pi 3 and no luck.

please help
sorry for bad english

**Comment by Universal-Rom-Tools** [comment]
In wich mode do you scrape ? choose the "Full Scrape" (not an update) and don't forget to kill EmulationStation before scraping... 

It will rescrape everything..

**Comment by dicktivity** [comment]
@Universal-Rom-Tools 
hey, thank you for reply.
i'm sorry but there is no "full scrape"
only "new xml file, update xml, and create picture only" and i set it to new xml file.
here is my setting
![capture](https://user-images.githubusercontent.com/30734552/29060332-891d6672-7c43-11e7-95f7-4e519f10ff3f.PNG)

**Comment by Universal-Rom-Tools** [comment]
Sorry for the delay.

Make sure your Emulationstation is killed (you must have a "black" screen on your PI)
try delete manually your gamelist.xml (sometime they are corrupted :S )

Everything seems to be good in your screenshot.

**Comment by dicktivity** [comment]
it's already fixed. thanks for helping, i don't know what's the problem but it's fixed :D
