### ISSUE TITLE
Roms path can't be reached

### ISSUE THREAD

**Issue by PaulyW84** [Universal-Rom-Tools/Universal-XML-Scraper#268]
I have a issue where every time I try to scrape I get an error message 'Roms path can't be reached'.

I have tried scraping ROMS stored on an external hard drive and also through Emulationstation but I'm getting this error message every time,  I have used this method flawlesseley for a few weeks but has now stopped working.

Any suggestions please?

![image](https://user-images.githubusercontent.com/31140153/29471529-3d1d05f4-8448-11e7-9869-1b53921a0000.png)

![image](https://user-images.githubusercontent.com/31140153/29471561-5b5554b8-8448-11e7-903a-b1c9580eadce.png)

**Comment by rafaelmarinids** [comment]
I have a same issue, could someone solve that?

**Comment by neushane** [comment]
You can fix it by going under your Network tab in windows and connect to your retropie. I had the same issue. Once I reconnected, I was able to run the program again.

**Comment by rafaelmarinids** [comment]
Where is this "Network Tab"? I'm using Windows 7 and can't find it... however i can see the Retropie through address "\\retropie\roms\atari2600".

![captura de tela de 2017-11-03 09-45-04](https://user-images.githubusercontent.com/30094358/32372486-2e72a9a8-c07c-11e7-9a88-3d6729358ae2.png)

**Comment by TriggerThumb** [comment]
My solution in the end was to remove all files from compressed zip/7 zip archives before running. Also I moved my rom folder path to my C:/ drive. It wouldn’t do it in a folder on my desktop or directly onto my portable hard drive either so may be something to do with folder permissions?

**Comment by Crom79** [comment]
I used an older version of UXS and it's working again, so I asume this is a bug in the newest version.

**Comment by Crom79** [comment]
Not a bug in the newest version, but a mistake on my side. the message dissapears, when you include missing filesextensions like *.7z  in the general configuration.

**Comment by Universal-Rom-Tools** [comment]
*.7z aren't in the extension scraped (maybe it's added on the last retropie version ?)

And for the path : If you can reach the folder from a windows explorer, UXS can ;)
After that, it may be a autorisation problem (try launch UXS in Admin mode)

**Comment by KingKebab** [comment]
I got the same error while trying to scrap Satellaview and Pokemon Mini romsets. Add *.bs and *.min file extension in the "General Configuration" as "Included files", solved my issue.

Current error message isn't realy relevant. Something like "Cannot found extension files to scrap in the current roms path" can be more helpfull.
