### ISSUE TITLE
Images are in folder but not on device screen

### ISSUE THREAD

**Issue by Ackille** [Universal-Rom-Tools/Universal-XML-Scraper#269]
I have scraped all my games and the pictures are physically on the Pi, but when I go through my library all except one game have the image posted. The rest have a description but no image. I have retried multiple times and restarted without success.

**Comment by Universal-Rom-Tools** [comment]
Check your gamelist.xml, you have the path to the picture, check if the path is ok.
If not, you must check the autoconf path configuration.
