### ISSUE TITLE
Still Scraping One by One VERY Slowly

### ISSUE THREAD

**Issue by franco265** [Universal-Rom-Tools/Universal-XML-Scraper#270]
Hi, I donated ten euros and my profile shows I have 6 threads now, but when I run UXS it is incredibly slow scraping my N64 games and it's still scraping them one by one.  So far it has been running for 40 minutes to complete six games.

How do I get it to scrape 6 at a time?

Also, it often crashes and I have to start from the beginning

Thanks

Franco

**Comment by Universal-Rom-Tools** [comment]
Check in general option if you thread number is on "6"...

With the last version, you can see the thread running (small white square on the right down corner).
1 thread = 1 square
6 Threads = 6 squares
They are checked when used and unechecked when in wait mode.
