### ISSUE TITLE
Grab artwork from different regions

### ISSUE THREAD

**Issue by dover19** [Universal-Rom-Tools/Universal-XML-Scraper#274]
I've been testing this program out with Atari 7800 roms and the first time around it didn't grab game cases or carts. I checked on www.screenscraper.fr and most artwork was tagged as being EU and my roms are mostly US. If artwork isn't available for a specific region, shouldn't it grab the next best thing? Perhaps we could have a profile with our favorite regions in a specific order. If US isn't available grab EU, if not grab JP etc.

**Comment by Universal-Rom-Tools** [comment]
It's already the case, check in the General config option, you have the Country Fallback (depending on your country, it should be something like : "%COUNTRY%|uk|eu|wor|ss|us|jp|cus"

Just Check "EU" is in the fallback list ;) (or add it if needed ;) )
