### ISSUE TITLE
Hashing - Hashes every single game, even tho set to just update missing ones

### ISSUE THREAD

**Issue by fOmey** [Universal-Rom-Tools/Universal-XML-Scraper#283]
I assume UXS should be skipping games already in the gamelist.xml and only updating the missing ones.. however this is not currently the case. 

Looks like it pulls all the data for the entire library of roms, even tho I have set it to only update missing.. Wouldn't it make more sense to read the gamelist.xml, loop through the rom directory and isolate just the titles that need scraping before even pulling any data.. This would speed the entire process up dramatically !

**Comment by Universal-Rom-Tools** [comment]
Normally it's the case : 
If you are in "Update mode", UXS check if the rom file is already in the XML and do nothing on the file if it's the case... If it's not, it calculate CRC and scrape information to add them at the end of the gamelist.xml.

**Comment by fOmey** [comment]
Yes.. however this is not the behavior I'm experiencing. Please re-read my issue..
