### ISSUE TITLE
UXS ignoring CRC of rom inside a zip and downloading wrong region

### ISSUE THREAD

**Issue by rubenjavier** [Universal-Rom-Tools/Universal-XML-Scraper#285]
Hello,
I have roms from the NoIntro sets, but downloaded from the internet archive, every rom has been correctly named and rezipped by the internet and has its correct CRC, but since the roms are inside new zips the CRC of he zip doesnt match, even though the name of the zip matches, the name of the rom matches, the CRC of the rom inside the zip matches... UXS just not unzip the rom and doesnt use the internal CRC.
Example:
Aero the Acro-Bat 2 (USA).zip CRC does NOT mach screenscraper, name matches USA
inside the zip:
Aero the Acro-Bat 2 (USA).md CRC 39EB74EB matches screenscraper USA, name matches USA

UXS download art from European version instead of american version
Already tried with all the combinations of CRC, Filename and UnzipFiles from the configuration
Also my country and language preferences start with north american versions
%COUNTRY%|us|wor|cus|ame|eu|ss|jp|xx

This is happening to a LOT of roms on the collection

best regards
Thanks in advance,

**Comment by Universal-Rom-Tools** [comment]
Hi,

2 possibilities : 
- Have you the "Search inside ZIP" function checked in the general config (it's unchecked by default)
- The country isn't well registered in the ScreenScraper DB (it happen sometime) feel free to send a correction as a proposition on the DB Website ;)
