### ISSUE TITLE
fatal error databases connection

### ISSUE THREAD

**Issue by kalma05** [Universal-Rom-Tools/Universal-XML-Scraper#287]
hi today is not posible use xml universal scrapper
error databases connection....
solution?
thanks

**Comment by akime1984** [comment]
I am having the same issues.

**Comment by luck2414** [comment]
same problem...

**Comment by ale296** [comment]
Same problem

**Comment by chfarges** [comment]
Same problem

**Comment by Foebik** [comment]
dito

**Comment by dongxuan** [comment]
Same problem

**Comment by Chimera111x** [comment]
Not trying to troll, but I am having the same issue.  I saw the same thing happened on Jan 4.

Could there be another login issue on your end?

**Comment by Universal-Rom-Tools** [comment]
Sorry Guys, it's a problem on Screenscraper DB side. 
The new server have some issue :(

The boss is working on it.
