### ISSUE TITLE
do not convert to uppercase/lowercase

### ISSUE THREAD

**Issue by JuliaEMS** [Universal-Rom-Tools/Universal-XML-Scraper#289]
I would like to use the scraped description as it is stored at screenscraper. Using the default it is converted to uppercase. Is it possible to avoid the conversion?

**Comment by Universal-Rom-Tools** [comment]
Of course
Check in the "option" menu under description, you can choose : lower/upper/normal Case ;)

**Comment by JuliaEMS** [comment]
Thank you for the quick answer.
I am using v. 2.2.0.3

Option-> Case-> Descrption-Case:
I have only the decision between: Default, UPPERCASE, lowercase

**Comment by Universal-Rom-Tools** [comment]
use "Default" ;)

**Comment by JuliaEMS** [comment]
Thank you, this helps!

**Comment by Universal-Rom-Tools** [comment]
I think it's ok ;) so I close the Issue ;)
