### ISSUE TITLE
Won't scrape region specified even with media available

### ISSUE THREAD

**Issue by dover19** [Universal-Rom-Tools/Universal-XML-Scraper#290]
I've noticed several of my games end up with the EU covert art and when I double check screenscraper.fr the artwork for US region is available.

This is my current country preference settings:
%COUNTRY%|us|ame|wor|cus|uk|eu|fr|ss|jp

**Comment by Universal-Rom-Tools** [comment]
In this case, it mean your Rom is an EU version ;)

If you want to "force" US media (without matching the rom country) just delete %COUNTRY%| from your country preference.

FYI, how it works : 

UXS try to match your romfile with a romfile referenced in the ScreenScraper DB (with Hash or with filename)
When it's OK, it check the country referenced from the matching file in DB
Then, with %COUNTRY%|us|ame|wor|cus|uk|eu|fr|ss|jp in your preference, it look for the media in this order : 
Referenced Rom %COUNTRY% media, if not found US media, if not found AME(erica) media, if not found WOR(ld) media, if not found CUS(tom) media, if not found UK media, if not found EU media, and so on...

When deleting the %COUNTRY% part, it do the same without checking the referenced country for you matching romfile. so directly US media -> AME media -> WOR media -> .....

If you are sure your romfile is a US one, so maybe the data in DB is wrong, don't hesitate to propose a correction....

**Comment by dover19** [comment]
Great, thanks. According to the romset I got they're all supposed to be US versions but who really knows.

Merci
