### ISSUE TITLE
Manually editing images and videos in xml ...

### ISSUE THREAD

**Issue by moltke44** [Universal-Rom-Tools/Universal-XML-Scraper#295]
So I had pretty good luck getting most of my roms scrapped perfectly but there are a few that it looks like I need to update images or add a different video I want. For instance I edited descriptions alright but for a couple roms I changed paths to the marquee and image files but they still wont' show up in ES (Retropie 3). I even reduced their size as I thought maybe the images were too big. What gives? Just basic JPG files and I've looked several times to makes sure the names mach. Normal location/directory too. Any thoughts? 

   If I had one request for the next update to XML it would be for a nice option in the menu to select a rom and then allow you to directly select the images or video you want and edit right from the scraper gui.

**Comment by Universal-Rom-Tools** [comment]
Sorry, don't think it happen one day ;)
UXS is only for Scrapping, not editing ^^.
