### ISSUE TITLE
Text gets cut off in german translation

### ISSUE THREAD

**Issue by Madmeggo** [Universal-Rom-Tools/Universal-XML-Scraper#33]
The text in the "scraped files" section (in the general configuration) gets cutt off when the german translation is used.  The words "Dateien" (files) and "Ordner" (folders) can't be read

Also some text in the same menu (on the left side) that is longer, isn't correctly displayed. I think it would help, if the Window would be a little bit wider.

[Screenshot](http://b64i.imgup.net/issue5fa3.png)

**Comment by Universal-Rom-Tools** [comment]
Normally it's corrected in the very last version ;)
I need to release it ;) (but I'm correcting some minor bug right now ^^)
(Word in german are really too long ^^ Entschuldigung )

**Comment by Madmeggo** [comment]
I tried to make the translation as short as possible. But yeah, some german phrases are very long :D

**Comment by Universal-Rom-Tools** [comment]
Madmeggo, can you confirm it's ok now ? (to close the issue ^^)

**Comment by Madmeggo** [comment]
Yes. Now the text can be read :)

**Comment by Universal-Rom-Tools** [comment]
Thank you ^^ I close the Issue
