### ISSUE TITLE
Scrape ROMs inside ZIPs?

### ISSUE THREAD

**Issue by verybadsoldier** [Universal-Rom-Tools/Universal-XML-Scraper#35]
Hello gentlemen!

Big thanks for this scraper, I like it alot! But I have one question please: Some games have multiple disks (many Amiga games for example) and I have put all the disks (ADFs and IPFs) for one game into one ZIP. So I can really have one file per game.
But it seems that UXS is not looking into the ZIPs but is only hashing the ZIP file itself which does not match any game in the DB. So is it possible to configure (or maybe possible to add as a feature) that UXS also can identify game disks inside ZIPs?

For example I have this Amiga game: `Sword of Sodan.zip` with the files inside and I would be great if UXS would identify that:
```
1103_Sword of Sodan_Disk1.ipf
1103_Sword of Sodan_Disk2.ipf
1103_Sword of Sodan_Disk3.ipf
```

Thanks & Cheers!

**Comment by Universal-Rom-Tools** [comment]
unfortunatelly it's impossible (or extremly complicated :S)...

BUT !! I have 2 solutions for you ;)

First one : simply name your file "Sword of Sodan (Europe).zip" it's an already referenced zip is the Screenscraper Database.
Second one : Send me your _Amiga_missing.txt file ;) I'll send it to our Amiga specialist who can put your zip file hash directly in Screenscraper database ;)

**Comment by verybadsoldier** [comment]
Thanks for quick answer!

Regarding the ZIP hashes: Since normal ZIPs are not reproducible (zipping the same data again will result in a different new hash) I think putting hashes of ZIPs into the database is of limited use. If someone else zips the same files into a ZIP then it will result in a ZIP with a different hash. The only solution I know is to use torrentzip which makes sure that always the same ZIP is created when using the same input.
So I could torrentzip my games and send you the missing-txt?

On the other hand: I code sometimes myself so I could try to add the feature to scrape inside ZIPs myself into UXS. I read a bit from the source code of UXS and I think I could maybe do it, but maybe I missed some problems that would arise. Do you really think it is near impossible? If not, would you mind if I give it a try and would you consider merging it then if it is of sufficient quality?

A last question please: I thought that UXS matches databasde entry solely based on hashes but I learned from your answer that it also uses filenames. Is it possible to disable filename matching? I'm afraid that it would be to unreliable for me.

Thanks!

**Comment by Universal-Rom-Tools** [comment]
you are right, zipping/dezipping/rezipping file will change the hash :s 
That's why we prefere "original" zip coming from a comon source...

For scraping "IN" the zip, the main problem I see is : when you have multiple file in a zip... Wich one do you want to scrape ? 
- All of them ? so you will have duplicate entry in your XML.
- the first one ? maybe it's not the good one...

for the filename, it's a fallback function... It's pretty rarelly used and it's work pretty well.

Based on the ROM filename, it look for a match in referenced ROM filename in the scraped system...
Till now I never found 2 roms with the same name matching 2 differents game in a same system ;)

So it's pretty reliable ;)
(If you found mistake telle me I'll look what I can do ;) )

**Comment by verybadsoldier** [comment]
I think torrentzip would be a solution for the unreliable ZIP hashes. But I would still prefer to scrape inside the ZIPs.

> For scraping "IN" the zip, the main problem I see is : when you have multiple file in a zip... Wich one do you want to scrape ?
All of them ? so you will have duplicate entry in your XML.
the first one ? maybe it's not the good one...

Regarding scraping inside ZIPs: I think you are fine as soon as you find ONE match. It probably does not matter which one. I assume that all files inside the ZIP belong to the same game. So a single match would be sufficient, no matter which file. The scrape result would be assigned to the original ZIP file, so it will still be just a single entry in your XML (just like now).

I am actually playing around with the code right now. My plan currently is:

- When a ROM did not match then check if the extension is ZIP
- If ZIP then extract it to a temp folder and iterate over the files
- Try to find a match one after the other
- If a match is found then stop processing the other files from the ZIP and copy the result to the "original" `$aRomList[$vBoucle]`
- If no match was found inside the ZIP then the `$aRomList[$vBoucle]` will just stay in status 'unmatched'


> Based on the ROM filename, it look for a match in referenced ROM filename in the scraped system...
Till now I never found 2 roms with the same name matching 2 differents game in a same system ;)
So it's pretty reliable ;)
(If you found mistake telle me I'll look what I can do ;) )

I think I stumbled recently about some Amiga and/or C64 games that had the same name actually. I do not remember which ones actually right now, but I will find out! In those cases matching by name would lead to wrong results though.

**Comment by Universal-Rom-Tools** [comment]
Ok, why not ;)

If you manage to did it works, it will be a good enhancement ;) 
Can you do it under a "function" ? It will be easier to add ^^ (My main code change a lot's these last time ^^ so a PR will be not easy :p )

And for rom filename... You maybe found the 0.0001% case it can happen ^^

**Comment by Universal-Rom-Tools** [comment]
I closed the Issue, Nicely done by verybadsoldier
