### ISSUE TITLE
Add Sudo to Retropie SSH function

### ISSUE THREAD

**Issue by Universal-Rom-Tools** [Universal-Rom-Tools/Universal-XML-Scraper#37]

**Comment by Shakz76** [comment]
<killall>killall emulationstation</killall>
			<start>/etc/init.d/S31emulationstation start</start>
			<reboot>sudo /sbin/reboot</reboot>
			<poweroff>sudo /sbin/poweroff</poweroff>

**Comment by Universal-Rom-Tools** [comment]
delete <start>emulationstation</start>

**Comment by Universal-Rom-Tools** [comment]
done
