### ISSUE TITLE
Add %System% Variable to put xml and images in the correct directories for retropie

### ISSUE THREAD

**Issue by Shakz76** [Universal-Rom-Tools/Universal-XML-Scraper#38]
By my thinking It should be used as such. 
/opt/retropie/configs/all/emulationstation/gamelists/%System%/gamelist.xml
and
/opt/retropie/configs/all/emulationstation/downloaded_images/%System%/<game>-image.png

**Comment by Universal-Rom-Tools** [comment]
I'm nearly ok, but I want to know 2 things : 

The SMB path (from your windows PC through network) to the "gamelist.xml" directory and to the "downloaded_images" directory.

Thanks ;)

**Comment by Universal-Rom-Tools** [comment]
Think  found it... This seems to be ok for 

		<Target_XMLName>\\retropie\configs\all\emulationstation\gamelists\%System%\gamelist.xml</Target_XMLName>
		<Target_RomPath>/opt/retropie/configs/all/emulationstation/gamelists/%system%/</Target_RomPath>
		<Source_ImagePath>\\retropie\configs\all\emulationstation\downloaded_images\%System%\</Source_ImagePath>
		<Target_ImagePath>/opt/retropie/configs/all/emulationstation/downloaded_images/%system%/</Target_ImagePath>

**Comment by Shakz76** [comment]
\\RETROPIE\configs\all\emulationstation\gamelists
\\RETROPIE\configs\all\emulationstation\downloaded_images

**Comment by Universal-Rom-Tools** [comment]
Normally it's ok in the new UXS Version.

Can you test ?

**Comment by Shakz76** [comment]
Not sure where its putting the pictures and gamelist...but I do not see them in the downloaded_images or gamelists dir

**Comment by Shakz76** [comment]
In the RetroPie Mix.xml file change to this...
```		<Source_RootPath>\\retropie\roms</Source_RootPath>
		<Target_XMLName>\\retropie\configs\all\emulationstation\gamelists\%System%\gamelist.xml</Target_XMLName>
		<Target_RomPath>/home/pi/RetroPie/roms/%system%/</Target_RomPath>
		<Source_ImagePath>\\retropie\configs\all\emulationstation\downloaded_images\%System%</Source_ImagePath>
		<Target_ImagePath>/home/pi/.emulationstation/downloaded_images/%system%/</Target_ImagePath>
```
I am still testing but I am going out of town and "might" not be able to log in...though I think I will in the mornings and wanted to get this code change to you.

**Comment by Universal-Rom-Tools** [comment]
Normally it's ok, this is the change I made : 

	<AutoConf>
		<Source_RootPath>\\retropie\roms</Source_RootPath>
	<Target_XMLName>%Source_RootPath%\..\configs\all\emulationstation\gamelists\%System%\gamelist.xml</Target_XMLName>
		<Target_RomPath>/home/pi/RetroPie/roms/%system%/</Target_RomPath>
		<Source_ImagePath>%Source_RootPath%\..\configs\all\emulationstation\downloaded_images\%System%</Source_ImagePath>
		<Target_ImagePath>/home/pi/.emulationstation/downloaded_images/%system%/</Target_ImagePath>
	</AutoConf>
```

**Comment by Universal-Rom-Tools** [comment]
I think it's OK now...
I close the Issue
