### ISSUE TITLE
Handling of multi-file games

### ISSUE THREAD

**Issue by verybadsoldier** [Universal-Rom-Tools/Universal-XML-Scraper#40]
Hi again,

I have another question please:
Is it possible to use UXS for multi-disk games? I am especially thinking of Playstation and Dreamcast games. They often come as cue/bins or gdi/bins.

For example:
```
House of the Dead 2, The (Europe) (En,Fr,De,Es) (Track 1).bin
House of the Dead 2, The (Europe) (En,Fr,De,Es) (Track 2).bin
House of the Dead 2, The (Europe) (En,Fr,De,Es) (Track 3).bin
House of the Dead 2, The (Europe) (En,Fr,De,Es).gdi
```

or
```
Wip3out (Europe) (Demo) (Track 1).bin
Wip3out (Europe) (Demo) (Track 2).bin
Wip3out (Europe) (Demo).cue
```
or just one bin:
```
Resident Evil (Germany).bin
Resident Evil (Germany).cue
```

If I put them just in the ROM folder then UXS will match multiples file per game so the game will show up multiple times in EmulationStation:
```
<game id="19476" source="ScreenScraper">
	<path>./Metal Slug X (USA).bin</path>
...
</game>
<game id="19476" source="ScreenScraper">
	<path>./Metal Slug X (USA).cue</path>
	<name>Metal Slug X</name>
...
```
Also when I want to start the game then I have to start the cue-file, the bin-file will not work (depending on the used emulator of course). So I would like each game to show up only once and the filename in the gamelist.xml should only mention the cue-file.

Are there any ideas about this? Big thanks!

**Comment by Universal-Rom-Tools** [comment]
Are you on Retropie ?

normally, on Recalbox profil, I add a "autohide" function...

If there is a cue+bin, it put the <hidden>true</hidden> for the bin (and all the bin matching the cue filename)...
It does it for (bios) or [bios] as well
And for all file with a "(Track " in the romfilename...
But it's a Recalbox function... Retropie haven't the <hidden> tag in gamelist....

**Comment by verybadsoldier** [comment]
Oh yes sorry, I should have mentioned: I am using RetroPie on an x86 NUC i5. So there is no such option for RetroPie? Anything else I can do?

**Comment by Universal-Rom-Tools** [comment]
unfortunatly, even if you don't scrape the not needed file (the bin when a cue exist) so they weren' in gamelist.xml, they will be shown in the gamelist on Emulationstation (with no data because not scraped)...

so I have no solution for now... maybe they're is one, but I'm not so "aware" about retropie ;)

If you have one ;) I can check what to do ;)

**Comment by verybadsoldier** [comment]
> unfortunatly, even if you don't scrape the not needed file (the bin when a cue exist) so they weren' in gamelist.xml, they will be shown in the gamelist on Emulationstation (with no data because not scraped)...

I think this would not happen since RetroPie/ES has for every emulator a list of extensions that is supported by that particular emulator. Like this:
```
<system>
    <name>dreamcast</name>
    <fullname>Dreamcast</fullname>
    <path>/home/vbs/RetroPie/roms/dreamcast</path>
    <extension>.cdi .chd .gdi .CDI .CHD .GDI</extension>
...
 <system>
    <name>psp</name>
    <fullname>PlayStation Portable</fullname>
    <path>/home/vbs/RetroPie/roms/psp</path>
    <extension>.iso .pbp .cso .ISO .PBP .CSO</extension>
    <command>/opt/retropie/suppl
```
They removed "bin" from the list some time ago so they won't show up. I think emulators cannot run bin directly anyway?

So maybe one solution would be if UXS would also have this list of supported extensions and only add files with such an extension to the gamelist.xml. But it would still be cool if UXS would still try to match hashes of all files belonging to the game.

For example when having a game like this:
```
Crazy Taxi (USA).gdi
Crazy Taxi (USA) (Track 1).bin
Crazy Taxi (USA) (Track 2).bin
Crazy Taxi (USA) (Track 3).bin
```
Then UXS would detect that all these files belong to the same game (by cropping the extension and the " (Track x)" part. Then it would try to find a match for any of the files by hash (stop on first find).
But then only add the gdi-file (based on the list of supported extensions) to gamelist.xml.

These naming convetion with "(Track x") is from the Redump romset, as far as I know all there romset use that convention.

**Comment by Universal-Rom-Tools** [comment]
an easy way is to use the "excluded" parameter in General configuration ;) 

just add *.bin, and no more bin were scraped ;)

But it's not solve the solution about finding one file on the list...

But it's here the "last" API request come ;) finding a match with the romfilename (without exension).
In your exemple : who many chance have you for having a rom named "Crazy Taxi (USA).*" not matching Crazy Taxi ;)

**Comment by verybadsoldier** [comment]
Ok thank you, that sounds good actually, I will try that!

Could you please tell me how the matching by filename work? Judging from the code: for the file "Crazy Taxi (USA).gdi" UXS would send "Crazy Taxi (USA)" to the screenscraper.fr, right? But when I manually search for "Crazy Taxi (USA)" on the website then I get no matches.

**Comment by Universal-Rom-Tools** [comment]
The API and the website don't work exactly the same ;)

But you can look for "Crazy Taxi (USA)" not in the "first" research input, but in the second one ;) (just under the first one :p ) : Search Roms files/isos/... 
You need to select the system too to "match" the API Function ;)

A normal API request is like that : 
http://www.screenscraper.fr/api/jeuInfos.php?devid=xxx&devpassword=yyy&softname=zzz&output=xml&ssid=test&sspassword=test&crc=50ABC90A&systemeid=1&romtype=rom&romnom=Sonic%20The%20Hedgehog%202%20(World).zip&romtaille=749652

For a research "only" by rom name it's like : 
http://www.screenscraper.fr/api/jeuInfos.php?devid=xxx&devpassword=yyy&softname=zzz&output=xml&ssid=test&sspassword=test&systemeid=1&romtype=rom&romnom=Sonic%20The%20Hedgehog%202%20(World).zip

(the second one will not work... devid and devpassword needed ;) the first one, is the exemple ^^ so it works ^^)

**Comment by verybadsoldier** [comment]
That is very helpful, thanks a lot! I will dig into it!

**Comment by Universal-Rom-Tools** [comment]
Sorry it's in French, but you have the WebAPI Page here : http://www.screenscraper.fr/webapi.php

And if you want a DevId and DevPassword, Ask MarbleMad here : http://www.screenzone.fr/forum/

**Comment by verybadsoldier** [comment]
I think it works for me using hashes of the .cue files, thanks alot!
