### ISSUE TITLE
English spelling mistakes

### ISSUE THREAD

**Issue by windale** [Universal-Rom-Tools/Universal-XML-Scraper#41]
After scraping I noticed a few spelling errors in the gamelist.xml :--

in the name field, '(Monde)' should be '(World)'
in the name field, 'Japon' should be 'Japan'
in the genre field, 'Plateform' should be 'Platform'

There maybe others but I haven't had time to study it.

**Comment by Universal-Rom-Tools** [comment]
Thank you windale, for information, these infos are from the DB : http://www.screenscraper.fr/
At start this DB was only in french ;) and we have enhanced it to have more and more language.
A v2 is in progress with a better language support.
We need to wait to have these new translated item ;)

(I correct the plateform as platform ;) cause I can on this one ;) )
