### ISSUE TITLE
Autoconfiguration bug

### ISSUE THREAD

**Issue by Madmeggo** [Universal-Rom-Tools/Universal-XML-Scraper#44]
The autoconfiguration doens't work for me anymore.
If i want to scrape only one system, i choose it with "scrape -> Select your system (Autoconf)", klick on scrape and then the Scraper puts the images in "/roms/downloaded_images" and the xml file in "/roms"
I have to manually adjust the paths in the "paths option" before i scrape my selected system, to get it to work, since the autoconfiguration sets a wrong path for the images and the xml every time i choose a system.

**Comment by Universal-Rom-Tools** [comment]
Can you guide me on the modification you do ?

I do a lot's of modification in the Autoconf Path to adjust path to the Retropie Standard...

**Comment by Madmeggo** [comment]
Let's say I want to scrape my SNES Roms:

I klick on "scrape -> select your system (autoconf) -> SNES
Then I go to "configuration -> path configuration"
There the Paths are:

Rom directory to scrape: (...)\roms\snes
XML file path: (...)\roms\gamelist.xml
Path to XML file: ./
Pictures: (...)\roms\downloaded_images
Path to pictures in XML: ./downloaded_images/


Then I adjust the paths to this (how it is supposed to be and how it was before this version)

XML file path: (...)\roms\snes\gamelist.xml
Pictures: (...)\roms\snes\downloaded_images

I have to do that every time when i chose another system. But I don't know what happens when I want to scrape all systems, since I normally don't do that.

**Comment by Madmeggo** [comment]
My Autoconfiguration paths standard and look like this:

Roms directory to scrape: (...)roms\snes
XML path: %Source_RootPath%\gamelist.xml
Path to roms in XML: ./
Folder name for downloaded pictures: %Source_RootPath%\downloaded_images
Path to picture in XML: ./downloaded_images/

**Comment by Universal-Rom-Tools** [comment]
I did exactly what you did...

Selecting "Retropie" profil
In menu "Scrape/Select your system (autoconf)/snes"
And this is my path in "Configuration/Path configuration" : 

Rom directory to scrape: \\RETROPIE\roms\snes
XML file path: \\RETROPIE\roms\..\configs\all\emulationstation\gamelists\snes\gamelist.xml
Path to XML file: /home/pi/RetroPie/roms/snes/
Pictures: \\RETROPIE\roms\..\configs\all\emulationstation\downloaded_images\snes
Path to pictures in XML: /home/pi/.emulationstation/downloaded_images/snes/

It seems to be good... (They are the right path for Retropie)

and if you are on Recalbox : 
I just Change the Recalbox Profil to adapt the standardisation I put on Retropie profil ^^ 
I had make a mistake on them ;) it's ok now in the V2.0.01 ;)

Can you test ?

**Comment by Madmeggo** [comment]
I totally forgot to say that I'm a Recalbox user. I hope that didn't cause trouble.
I'll check the new version out right now! :)

**Comment by Universal-Rom-Tools** [comment]
thank you ;) I close the Issue ;)
