### ISSUE TITLE
Universal XML Scraper fatal error ! (Timeout)

### ISSUE THREAD

**Issue by AnthraxLeprosyPi** [Universal-Rom-Tools/Universal-XML-Scraper#46]
Hey,

I started using this marvelous time saver a week ago and after some wrangling with the settings it produced very nice fanart (MIX is briliant)...

Beta 2.0.0.6 was running smoothly with good results - but the new stable version 2.0.0.2 gives me fatal error / timeout :-(

I checked my firewall and specifically allowed the scraper.exe(s) - but it didnt work.

Any idea what might be the problem?

best regards
Anthrax

**Comment by Universal-Rom-Tools** [comment]
I add a "check" for launching scrape engine. And it seems it cannot launch it (Need to add a better Error message than only "Time out")

Try delete these 2 files : scraper.exe and scraper64.exe (they are hidden files in the UXS folder)

UXS will add them with the last version (who handle the Check Scrape Engine Start).

Maybe there is a problem to update them...

(I'll add in the 2.0.0.3 a filedelete to be sur they will be update in this version...)

**Comment by AnthraxLeprosyPi** [comment]
That did the trick!!!

Now it's scraping again. 
This happened while coming from Beta 0.6 and only overwriting Universal_XML_Scraper.exe...
My settings were overwritten as well btw...

**Comment by Universal-Rom-Tools** [comment]
Yep :S sorry, every update will "reset" all settings...

Because sometime, I change them to add new functionnality (or correcting a bug comming from settings)

But if it works ;) it's great ;)

I close the Issue ;)

**Comment by AnthraxLeprosyPi** [comment]
THX!
