### ISSUE TITLE
Feature request - System Detection (No-Intro Folder layout)

### ISSUE THREAD

**Issue by AnthraxLeprosyPi** [Universal-Rom-Tools/Universal-XML-Scraper#47]
Is there any change to have system detection allow for "No-Intro" folder names?

See picture...
![image](https://cloud.githubusercontent.com/assets/1488146/20619171/5c83f5fa-b2f3-11e6-8ef2-78ec1c50b907.png)

A simple mapping ini-file would be nice ;-)

ciao
Anthrax

**Comment by Universal-Rom-Tools** [comment]
Yes, it's possible.

You found there the matching file (between "standard folder" | "Selected system") here : 
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/blob/master/Ressources/systemlist.txt

If you have the full list of "standard NO-INTRO folder" I can add them easyly ;)

**Comment by AnthraxLeprosyPi** [comment]
Damn you're quick and seem to have thought of everything already ;-)

PLEASE DO ADD THEM 💯 !!!

**Comment by Universal-Rom-Tools** [comment]
Do you know where I can find the full folder list ?
(or can you make a pastebin with all the NO-INTRO folder list ?)

**Comment by AnthraxLeprosyPi** [comment]
There you go:

[no-intro_folders.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/612902/no-intro_folders.txt)

**Comment by windale** [comment]
That list you posted is old, this is the current list :--

Atari - 5200
Atari - 7800
Atari - Jaguar
Atari - Lynx
Atari - ST
Bandai - WonderSwan
Bandai - WonderSwan Color
Benesse - Pocket Challenge V2
Casio - Loopy
Casio - PV-1000
Coleco - ColecoVision
Commodore - 64
Commodore - 64 (PP)
Commodore - 64 (Tapes)
Commodore - Amiga
Commodore - Plus-4
Commodore - VIC-20
Emerson - Arcadia 2001
Entex - Adventure Vision
Epoch - Super Cassette Vision
Fairchild - Channel F
Funtech - Super Acan
GamePark - GP32
GCE - Vectrex
Hartung - Game Master
LeapFrog - Leapster Learning Game System
Magnavox - Odyssey2
Microsoft - MSX
Microsoft - MSX2
NEC - PC Engine - TurboGrafx 16
NEC - PC Engine SuperGrafx
Nintendo - Family Computer Disk System
Nintendo - Game Boy
Nintendo - Game Boy Advance
Nintendo - Game Boy Advance (e-Cards)
Nintendo - Game Boy Color
Nintendo - New Nintendo 3DS
Nintendo - New Nintendo 3DS (DLC)
Nintendo - Nintendo 3DS
Nintendo - Nintendo 3DS (DLC)
Nintendo - Nintendo 64
Nintendo - Nintendo 64DD
Nintendo - Nintendo DS
Nintendo - Nintendo DSi
Nintendo - Nintendo DSi (DLC)
Nintendo - Nintendo Entertainment System
Nintendo - Pokemon Mini
Nintendo - Satellaview
Nintendo - Sufami Turbo
Nintendo - Super Nintendo Entertainment System
Nintendo - Virtual Boy
Philips - Videopac+
RCA - Studio II
Sega - 32X
Sega - Game Gear
Sega - Master System - Mark III
Sega - Mega Drive - Genesis
Sega - PICO
Sega - SG-1000
Sinclair - ZX Spectrum +3
SNK - Neo Geo Pocket
SNK - Neo Geo Pocket Color
Tiger - Game.com
VTech - CreatiVision
VTech - V.Smile
Watara - Supervision

See here http://datomatic.no-intro.org/?page=download for more info.

**Comment by AnthraxLeprosyPi** [comment]
Alright, cheers - I guess I gotta got rom hunting again...

**Comment by Universal-Rom-Tools** [comment]
Added in last version ;)

(Some weren' because doesn't exist in DB...)

**Comment by AnthraxLeprosyPi** [comment]
Thank you so much. This saved me hours.

Very nice.
