### ISSUE TITLE
alternative pictures not entered in gamelist.xml

### ISSUE THREAD

**Issue by gishfish** [Universal-Rom-Tools/Universal-XML-Scraper#52]
i use the profile on recalbox 4, set default image to 2D box and alternative image to screenshot.

the screenshots (alternative images) are being downloaded and put in the correct folder, but the image path is not written into the gamelist.xml files.

is this meant to be that way?

EDIT: i found an exception; it worked on gameboy folder but not on any other.

**Comment by Universal-Rom-Tools** [comment]
Corrected in the last version...

(It put a </images> in the XML when the main picture isn't found... so it will not now ^^)
