### ISSUE TITLE
Scrape Results wrong?

### ISSUE THREAD

**Issue by verybadsoldier** [Universal-Rom-Tools/Universal-XML-Scraper#54]
I have a question/problem the scrape results that get displayed at the end of the scraping process. A scraped NES ROMs with this results:
![image](https://cloud.githubusercontent.com/assets/364469/20639677/7cd2c73c-b3ca-11e6-977d-f13150f01a02.png)

Also I have 289 files in `_NES_missing.txt`, so I think "100% ROMs found is wrong". Maybe the "Roms found: 2722/2722" should be `2722/3011` and the percentage should be lowered accordingly?

**Comment by Universal-Rom-Tools** [comment]
I need to improve that you are right ;)

**Comment by Universal-Rom-Tools** [comment]
So now rom found is when the rom is "really found" on "rom Returned from the scraper Engine"

Percentage adapted too...

I think it will be better ;)

**Comment by Universal-Rom-Tools** [comment]
it's seems to be ok
