### ISSUE TITLE
Option to enter username and password for shell access

### ISSUE THREAD

**Issue by verybadsoldier** [Universal-Rom-Tools/Universal-XML-Scraper#56]
This is a feature idea:
RetroPie does not only support RaspberryPi but also can run on x86/x11 systems (as in my case). So the username/password of the machine is not necessarily `pi/pi` but something custom. The shell commands to stop ES will not work in that case
So it would be great if you could configure the username/password that UXS will use for shell commands.

**Comment by Universal-Rom-Tools** [comment]
Added in last version
