### ISSUE TITLE
killall/ending ES message

### ISSUE THREAD

**Issue by gishfish** [Universal-Rom-Tools/Universal-XML-Scraper#57]
The warning message to end emulation station, appears everytime a new folder is beeing scraped.
which is quite anoying when using "scrape all" to scrape the entire library (which takes several hours (days)).

**Comment by Universal-Rom-Tools** [comment]
Arg ... sorry I need to correct that quickly...

**Comment by Universal-Rom-Tools** [comment]
Corrected in the last version
