### ISSUE TITLE
Nintendo Disk System Games not found. Not a Child of NES?

### ISSUE THREAD

**Issue by verybadsoldier** [Universal-Rom-Tools/Universal-XML-Scraper#58]
I scraped a directory which contains NES games and also Disk System games. As far as I understand it, Disk System should be a child of NES so it is ok to scrape them using NES cause it will also look in Disk System then.
Is my assumption wrong or is there maybe a problem with the DB?

I can provider a list of missing files later if needed!

Thanks!

**Comment by Universal-Rom-Tools** [comment]
Normally you are right...
I need to check FDS is a child of NES on the DB...

**Comment by Universal-Rom-Tools** [comment]
I just check the DB... FDS is a child for NES... But if you want to try some test, uncheck the "Auto select your system" in General config... And choose manually FDS.... normally it will scrape only FDS roms.

**Comment by verybadsoldier** [comment]
You are right, it works! Sorry! Either it was fixed in the last days or maybe it was just wrong on my end, thanks!
