### ISSUE TITLE
[Feature Request] Auto-reconection

### ISSUE THREAD

**Issue by ppmeis** [Universal-Rom-Tools/Universal-XML-Scraper#6]
First of all, I just want to say thank you for this tool. It works really well and It's all we need to make our launcher better. Congrats ;).

I only have some suggestions for make this tool better. Normally, this tool takes a lot of time downloading all images (for my snes set takes about 8 hours!). And I detect if there's a disconnection, a message says "there's no connection with database" and it stops downloading. So I have to cut the already done files to other folder, relaunch the tool and finally merge manually both gamelist.xml into one.

I think thats all. Thanks for your work.

**Comment by Universal-Rom-Tools** [comment]
Auto-reconection to where ?
Normaly, if you have a timeout, it continue with the next rom...
I must check, but if Picture is already present, he skip the ne one... (Except in MIX profil... I need to correct this ;) )

**Comment by ppmeis** [comment]
Sorry I press enter without write anything.

That's could be a reason, because I am using the MIX profil (what's the different between the normal one). Also I am using a custom profil from the forum called "Standard 4img" (it also makes the cartridge image), so I don't know if it can be a problem with that.

Anyways, the error happened to me a few times, and when I close the error button, the tool starts making all images and xmls with the already downloaded files, and don't keep downloading the remaining ones.

Thanks for your fast answer @Universal-Rom-Tools

**Comment by Universal-Rom-Tools** [comment]
Ok, ^^ I need to check this (I'm right now working on the MIX profil so I'll try to not doing the MIX if picture already exist).

I'll try to check why it's desconect with an error :S (are you using the very last version ?)
And if it's working (more or less) don't try to merge or something, just go to the configuration, and check "Append XML file" It will skip the already scraped file.

**Comment by ppmeis** [comment]
@Universal-Rom-Tools yes I am, the latest version v1.4.0.5.

Does the tool skip already checked files if I use this option? I mean, If It had already done 100 roms, will the tool begin again with 101 rom and then merge xml files from the 101 rom?

**Comment by Universal-Rom-Tools** [comment]
It check if the rom is already in the xml file, if yes, go to the next rom ;)

Only adding the new one (not already in the XML file)

**Comment by ppmeis** [comment]
Ok I check again and it works like you said, so i will change the title of this issue.

**Comment by Universal-Rom-Tools** [comment]
Normally I modified in the last version the TimeOut function... So Now, No more disconnection, If it's Timing out on a Rom, it try the next one... So you can have missing. But Re-Scrapping in Happend Mode will add the missing one ;)

Just a thing 8h for how many Roms ??? I think it's too much ;) Is your recalbox in WIFI ?
Maybe you can try putting your Rom on a USB support to Scrape from your PC TO your PC ;)

**Comment by ppmeis** [comment]
I don't use recalbox, but loading Roms locally on my desktop. The set was snes for about 1500 Roms.

**Comment by Universal-Rom-Tools** [comment]
8 Hours for 1500 Roms ??? There is a problem somewhere... 

Just make about 900 Roms in 1h30 With a very complicated MIX Template (with a lot's of differente pictures in big size)

**Comment by ppmeis** [comment]
Zip files takes longer times for THIS maybe?

**Comment by ppmeis** [comment]
I check again it's spending about 2 hours for 1400 with MIX Template (the one with screenshot, logo, cover and cartridge). Normal values or still rare?

**Comment by Universal-Rom-Tools** [comment]
2Hour is a descent time for 1400 Rom with a "simple" mix
(For information, the Mix template you choose must download 4 pictures. Not so much, juste few second more by rom... But x1400 it's a lot more ^^)
