### ISSUE TITLE
If you do not omit/exclude .bin files when scraping PSX the app locks up. 

### ISSUE THREAD

**Issue by Shakz76** [Universal-Rom-Tools/Universal-XML-Scraper#65]
If you do not omit/exclude .bin files when scraping PSX the app locks up. 
To correct this I removed .bin from the general configuration. Some users only have bin files though and no cue files so this workaround might cause them issues.

**Comment by Universal-Rom-Tools** [comment]
Are you sur the app locks up ? Or is it just very long ? (Calculating CRC / MD5 on big BIN file can take a long time...)

**Comment by Shakz76** [comment]
Actually you may be right...as some of the games have a ton of .bins. And I see active threads but windows reports "application is not responding".

**Comment by Universal-Rom-Tools** [comment]
So, it's not really a freeze ;) only a very slow down of your computer ;)

I close the case ;)
