### ISSUE TITLE
JPG image format does not work

### ISSUE THREAD

**Issue by bkg2k** [Universal-Rom-Tools/Universal-XML-Scraper#66]
Whatever image format you choose, the software generates PNG.
I tried to stop and rerun scrapping, stop and relaunch the application, and checked the output format in the config.ini file, but nothing change.

**Comment by Universal-Rom-Tools** [comment]
If you are on a "MIX" profil it's normal...

jpg work only without MIX....

(MIX need transparency that jpg can't handle)
