### ISSUE TITLE
PSX .pbp .PBP scraping really slow compared to other systems

### ISSUE THREAD

**Issue by joshsmithtogo** [Universal-Rom-Tools/Universal-XML-Scraper#68]
.pbp files are placed directly in root of psx roms folder and renamed to match game name.  Start scraper and it starts and just goes and goes.  Ends up scraping 8 out of 51 games. Weird?

**Comment by Universal-Rom-Tools** [comment]
need to find a way to accelerate big file Hashing...

**Comment by Universal-Rom-Tools** [comment]
Added a new Option to scrape only by Filename (usefull for very big roms, but less accurate) in 2.0.0.6
