### ISSUE TITLE
Upload the source code, not binaries

### ISSUE THREAD

**Issue by krcroft** [Universal-Rom-Tools/Universal-XML-Scraper#69]
This is not currently open source if only binaries are available.

**Comment by Universal-Rom-Tools** [comment]
what do you mean ?

All sources are available... *.au3 are sources...  some binary where uploaded to make the compilation easier (when compiling Universal XML Scraper, you need to have the Scraper.exe and Scraper64.exe... And if you look well, you have the scraper.au3 as sources...)

Do you know how autoit works ?
