### ISSUE TITLE
[Suggestion] Add an option to keep attributes: (USA, EU, JAP),  (REV 1), etc.

### ISSUE THREAD

**Issue by paradadf** [Universal-Rom-Tools/Universal-XML-Scraper#7]
Hi! Could it be possible to add an option to keep the attributes after the game's name?
This would be specially useful when netplay is implemented, as both parties must have the exact same rom. But also, for people that just want to know which version of the rom they have. And I don't mean to keep the rom name without the extension (although there surely are people that would like that), but to use the game's name from ScreenScraper + keeping whatever the rom's name has between brackets (...) and [...].

**Comment by Universal-Rom-Tools** [comment]
An option like : The name of the game is the filename without extension is easy to do ^^
But Retrieving the info between (..) and [..] and adding it to the scrapped name is feasable... But it's very particular.... (How many person will used it ???)

I have an other project to do a conversion Table for the Region in brackets and the Region Tag in the gamelist.xml (we have that now in the V4+ ^^ But I think it's not used...)

Maybe in the futur ;) But It's a big thing for the time I have right now... So it's not in my priority list ;)

**Comment by paradadf** [comment]
Thanks for the answer. I'll check your other tool. Didn't know how complex such a function would be. Fell free to close the issue if you want.

**Comment by Universal-Rom-Tools** [comment]
Catchin between bracket information is not the hard part ;) It implementing a merge between something scraped and something coming from the filename ;)

I'll try to take a look ;) (But I don't know when) so I leave this Issue Open ;)

**Comment by digitalLumberjack** [comment]
I just ran into this.
With no intro romsets, the full name is composed by information really exhaustive like the region, the prototype but it's not polluted by the standard rom conventions like the [A] or [!].

So maybe we can add an option to save the rom name in place of the game name.

@Universal-Rom-Tools what do you think ?

**Comment by Universal-Rom-Tools** [comment]
Yes it's a good Idea ;) And it's done ;)

In the last reseale (1.5.0.2 and above) you can change the profile like this :  

`$ELEMENT_8 		= 'name|value|noms/nom_%%|value'`

Become :  

`$ELEMENT_8 		= 'name|value|%RomName%|variable'`
-> Full filename of the rom

Or

`$ELEMENT_8 		= 'name|value|%RomNameShort%|variable'`
-> Filename of the rom without extension.

**Comment by paradadf** [comment]
This totally works for me! The reason why I suggested that 'particular' option is because, for example:

No-intro name: 
Legend of Zelda, The - Ocarina of Time (USA) (Rev A)

Real name (Screenscraper):
The Legend of Zelda: Ocarina of Time

My suggestion:
The Legend of Zelda: Ocarina of Time (USA) (Rev A)

That might be only me, but I consider the last one the niciest (best name and informative), don't you think?

But please, it is just a suggestion. I'm so grateful for the current state of your tool that my eyes just shine a bit brighter with every new realese and the great features you creatively add!

**Comment by Universal-Rom-Tools** [comment]
Tadaaaa !!!!

It's done :  

Now you can :  

`$ELEMENT_8 = 'name|value|%RomName%|variable'`
-> Full filename of the rom
Exemple : **Zero Tolerance (USA, Europe).zip**

`$ELEMENT_8 = 'name|value|%RomNameShort%|variable'`
-> Filename of the rom without extension.
Exemple : **Zero Tolerance (USA, Europe)**

`$ELEMENT_8 = 'name|value|noms/nom_%%|form:region'`
-> Scraped Name and Scraped Region Merged. (So it work very well with Arcade game ;) )
Exemple :
Scraped Name : _Zero Tolerance_
Scraped Region : _USA_
Name result : **Zero Tolerance (USA)**

`$ELEMENT_8 = 'name|value|noms/nom_%%|form:%FileNameBracket%'`
-> Catch the first bracket ( '(' or '[' ) in the file name and merge the end of the filename (without extension) with the scraped name (Your suggestion @paradadf ^^)
ex : 
Game Name : _Zero Tolerance_
Filename : _zerotolerance (USA, Europe) [Proto].zip_
FileNameBracket : _(USA, Europe) [Proto]_
Name Result : **Zero Tolerance (USA, Europe) [Proto]**

I think I can close this Issues ^^ Don't hesitate to ask more function ^^

It's a cool to add it ;)

**Comment by paradadf** [comment]
AMAZING!!!

**Comment by digitalLumberjack** [comment]
Ô yeah!
