### ISSUE TITLE
Cant'run

### ISSUE THREAD

**Issue by marcos1500** [Universal-Rom-Tools/Universal-XML-Scraper#78]
hi , i have a problem, the scraper don't run in my computer i don't know why. simply extracted some archives but doesn't run nothing. please help me, the version is the last https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.0.0.7 for windowsx64

**Comment by marcos1500** [comment]
Sorry, i changed the version and worked

**Comment by Universal-Rom-Tools** [comment]
great ;) it's working ;)
