### ISSUE TITLE
Can t scrap roms with large size

### ISSUE THREAD

**Issue by giventofly** [Universal-Rom-Tools/Universal-XML-Scraper#79]
Tried psx, dreamcast and PSP roms but after a while program just crashes/blocks.

An option to search only by name could be used in this cases. Instead of trying to hash the file.

**Comment by Universal-Rom-Tools** [comment]
The option already exist.

Check in the 2.0.0.7 version, in General Option, the scrape mode menu...

You have 0 - CRC+Filename, 1 - CRC, 2 - Filename.

The counter part it's a way less accurate than with CRC.... But calculating HASH from very big file is very long :S
