### ISSUE TITLE
Add explorer options ex. Swish

### ISSUE THREAD

**Issue by joshsmithtogo** [Universal-Rom-Tools/Universal-XML-Scraper#81]
Swish is used to mount sftp connections into windows explorer for remote connections.  In theory you could scrape or scrape someone else's recalbox remotely as long as port forwards were programmed into the router or gateway,  Currently Universal Scaper does not give the option to use this connection even though it is mapped.  Request this feature be added.  It would help in giving assistance to others.

**Comment by Universal-Rom-Tools** [comment]
I don't really understand your demand :S (sorry)

UXS can scrape every directory you can see in windows explorer.

So if you mount a netdrive (or something similar) and you can access it with your file explorer. You can scrape it...

(For exemple : I have all my romset on my NAS... I can scrape them directly with a netpath like //NAS/Romset or with a mounted netdrive like Y:/Romset where Y: is the netdrive to //NAS )

**Comment by joshsmithtogo** [comment]
Yes.  It was a Swish issue.  I am removing the post.

**Comment by Universal-Rom-Tools** [comment]
no problem ;)
