### ISSUE TITLE
Permanently the message "Hashing Please Wait..."

### ISSUE THREAD

**Issue by verybadsoldier** [Universal-Rom-Tools/Universal-XML-Scraper#82]
Regarding this change:
> message "Hashing Please Wait..." when hashing big file (to not think UXS freeze on big file)

I have now permanently this message in the title bar. I think it was nicer when you could see the game title it is currently working on instead of always just the message "Hashing Please wait...". Maybe a matter of taste though but for me that message does not add any information.

**Comment by Universal-Rom-Tools** [comment]
Yep, it's a bug... Corrected in 2.0.0.9
