### ISSUE TITLE
Profile options

### ISSUE THREAD

**Issue by stayupthetree** [Universal-Rom-Tools/Universal-XML-Scraper#83]
Im not understand the difference when I start up and have to choose between the options:

RetroPie
RetroPie Mix
RetroPie Mix (roms folder)

Is there any major difference I should be aware of. Sorry to put this here but don't know where else to ask

**Comment by Universal-Rom-Tools** [comment]
No problem ;)

**Retropie** = Standard Retropie Path and "simple" media (like screenshot or 2D Box/3D Box)
**Retropie Mix** = Standard Retropie Path and "MIX" Media. You can mixe some media to have a nice render in Retropie (see exemple https://github.com/Universal-Rom-Tools/Universal-XML-Scraper )
**RetroPie Mix (roms folder)** = Like Sselph scraper, Media and gamelist.xml were downloaded in the rom directory, not the standard Retropie Path. And MIX media ;)

**Comment by Universal-Rom-Tools** [comment]
no news in 20 days...  I close the issue
