### ISSUE TITLE
2.0.0.9 SSH Options dont work (for me)

### ISSUE THREAD

**Issue by giallone1970** [Universal-Rom-Tools/Universal-XML-Scraper#87]
I cant stop Emulation station, reboot or halt
all is configured as should (i also tried with IP instead of host name)

If i use 2.0.0.8, all works as should

i use recalbox latest version avaialble and i can access the share and use normal ssh with putty
thank you =)

**Comment by Universal-Rom-Tools** [comment]
Hum... sorry, it's possible... I change some SSH function in the last one... I will correct these.

**Comment by chaseruk** [comment]
same issues with me too.
upon checking the logs..no sudo in ssh commands

**Comment by Deltron156** [comment]
Same here. And also I can't see any visual changes in my retropie. The images are downloaded and placed in the correct directory, but no changes at all.

**Comment by Universal-Rom-Tools** [comment]
I really need to release the correction >< sorry.

**Comment by tsarrack** [comment]
2.0.0.9 is the same for me. I can only get it to scrape roms on my computer. The previous release was working great until today when I started getting an XML error.

**Comment by Universal-Rom-Tools** [comment]
Normally solved with the last version.

no news in 10 days...  I close the issue
