### ISSUE TITLE
Keep ratio for logo with Arcade (Moon) By Supernature2K

### ISSUE THREAD

**Issue by digitalLumberjack** [Universal-Rom-Tools/Universal-XML-Scraper#9]
Arcade (Moon) By Supernature2K : 
The logo in right of the cab may be really scaled, it should keep its original ratio.

**Comment by digitalLumberjack** [comment]
Did i say it's a great work ? I say i now :D

**Comment by Universal-Rom-Tools** [comment]
Corrected in the last version 

And also in 

- Arcade (moon) By Supernature2k
- Standard (3img)
- Standard (4img) By Supernature2k

Thank you for your Compliment and the bug issue ;)

**Comment by digitalLumberjack** [comment]
Cool !

**Comment by digitalLumberjack** [comment]
Just tested, you can reopen :) 
![3wonders-image](https://cloud.githubusercontent.com/assets/1128425/17727821/024e6498-645c-11e6-9401-e582befe3526.png)

**Comment by Universal-Rom-Tools** [comment]
Can you try the very last version ? (1.5.0.11)

I try and it's OK for me ;)

**Comment by digitalLumberjack** [comment]
Allright that's fixed :)
