### ISSUE TITLE
Grey out (or similar) not active sub-menu "Path configuration"

### ISSUE THREAD

**Issue by paradadf** [Universal-Rom-Tools/Universal-XML-Scraper#91]
When the Auto Conf is enabled, changes on "Path configuration" have no effect.
To make it (even more) user friendly, some sort of visual differentiation should be used to make clear that that sub-menu isn't active. Not necessarily remove the option to edit it, but just some kind of warning.
For example, if you save changes on the "Path configuration" tab AND the Auto Conf is enabled, bring a pop-up message saying something like: "Autoconfiguration is enabled. Its paths have preference." XD
I'm not sure what the better option would be :S

**Comment by Universal-Rom-Tools** [comment]
Need to test, but "normally" if you use autoconf, select your system in the list and go to "Path configuration" to make adjustment. It keep your adjustment till you select an other system.

What autoconf really do is simple : 

When you select a system in the list, it "create" the path in "Path configuration" accordingly to your selected system.

When you scrape, UXS use what is in "Path configuration".

So if you don't select an other system in between, it will keep the modification you do in "Path configuration".

**Comment by paradadf** [comment]
After your explanation I finally understood what the user was complaining about!
What he told me is that the the path he changed on Path configuration wasn't being kept after selecting another system. I think the most intuitive would be to retain those mods even after a new system is selected.

**Comment by Universal-Rom-Tools** [comment]
If he want to change path, he must do his "change" in "autoconfiguration path configuration" ;)

So when he select a new system, it will be ok in "path configuration" ;)

I can't "keep" modification in "path configuration" after selecting a system. 
Selecting the system create these path with data in "autoconfiguration path configuration" .

**Comment by paradadf** [comment]
Understood. This is no bug then, but just the way it is! Thanks for the clarification!
