### ISSUE TITLE
Scraping NES (original Nintendo)

### ISSUE THREAD

**Issue by twidget2011** [Universal-Rom-Tools/Universal-XML-Scraper#92]
I am trying to get a successful scrape on my NES (Nintendo) folder.  the scrape runs, it gathers the images and writes the gamelist.xml file and places it into the correct location \\RETROPIE\configs\all\emulationstation\gamelists\nes

I have looked at the file and it appears correct.  Currently there are only two games in there.

I cannot see the graphics and/our game descriptions in Retropie.

A similar thing happened with the Sega Genesis folder but I corrected that by putting the roms into the megadrive folder.  The Sega games work fine that way, only issue is it shows them as megadrive games in the gui. 

I tried putting the NES roms into the FDS folder but they dont show there either.

Anyone have simmilar issues?

my NES gamelist.xml is below.

<?xml version="1.0"?>
<gameList>
	<game>
		<path>./1943/1943.nes</path>
		<name>1943 : The Battle of Midway</name>
		<desc>The sequel to 1942, which is still a vertically scrolling shooter, has the player once again fighting over the clouds during the second world war, this time in an intense battle just off the coast of Midway islands.

Updates to the gameplay include an energy bar, which can be run down by either being hit from incoming fire or using a special weapon. The energy bar can be replenished by picking up power-ups, while special weapons (lightning, cyclones and waves) can knock down all fighters on the screen at the time.
</desc>
		<image>/home/pi/.emulationstation/downloaded_images/nes/1943_1943-image.png</image>
		<rating>0.7</rating>
		<releasedate>19881002T000000</releasedate>
		<developer>Capcom</developer>
		<publisher>Capcom</publisher>
		<genre>Shoot'em Up</genre>
	</game>
</gameList>

**Comment by Universal-Rom-Tools** [comment]
your rom path is really strange : ./1943/1943.nes 

Is it normal you have a "subfolder" named 1943 with the 1943.nes rom inside ?

Try to use "autoconfiguration" without "touching" path... and just select you system before scrape.

**Comment by Universal-Rom-Tools** [comment]
no news in 13 days...  I close the issue
