### ISSUE TITLE
Repeated names for Arcade roms

### ISSUE THREAD

**Issue by mgoulartBR** [Universal-Rom-Tools/Universal-XML-Scraper#93]
Hi,

I don't know if this feature is implemented but for some arcade games there are many version for a same game. For example Cadillac and Dinosaurs (Asia, Japan, Europe, USA, 2 players version, 3 players version) and all roms are named equally (In this example "Cadillac and Dinosaurs"). on Universal XML Scraper. Is there a way to change it, for rename with different names?

**Comment by Kamakiri77** [comment]
I would like to see this too

**Comment by Universal-Rom-Tools** [comment]
First of all, you can choose in "option configuration" Name = "gamename+country".
Your game will be in this format : "mario bros. (japan)"

And for the second part ;) be patient ;) Screenscraper V2 is comming with a lot's more "options" and "metadata". So i can grab info like "clone",...

**Comment by mgoulartBR** [comment]
Thanks!!! I will try it!!!

**Comment by a7mag3ddon** [comment]
That option doesn't work, I opened an issue for it.

**Comment by Universal-Rom-Tools** [comment]
Corrected and added
