### ISSUE TITLE
Crash while scraping FBA and MAME on Retropie

### ISSUE THREAD

**Issue by Bloomfear** [Universal-Rom-Tools/Universal-XML-Scraper#94]
UXS crashes when there're big number of roms in the folder. It's fine with 50-100 roms but when it's 1000, UXS can't finish scraping. I tried 2009 and 2008 and both crashed on Retropie MIX and regular Retropie settings even by decreasing image size to 320x240.

**Comment by Universal-Rom-Tools** [comment]
pretty strange, I scrape folder with much much more than 1000 roms without any problem.

can you describe your "crash" ? Any error ? what's the "logs" says ? Have you enough free space ? Have you some network problem ?

**Comment by Bloomfear** [comment]
Thank you for the response. I've found out there's a network problem between laptop and raspberry pi 3. When connection lost, UXS crashes. Is there a way to add "wait for network" option?

**Comment by Universal-Rom-Tools** [comment]
Sorry :S impossible for me :s 

I use "standard" windows SMB sharing function... so if there is any network problem, it crash :S 

Are you in wifi ? try with a network cable.

**Comment by Bloomfear** [comment]
Ok, thank you, no problem. That's actually how i fixed my issue, using an ethernet cable.

**Comment by Universal-Rom-Tools** [comment]
great. And sorry for that
