### ISSUE TITLE
2.0.0.9 doesn't work with my Pi

### ISSUE THREAD

**Issue by tsarrack** [Universal-Rom-Tools/Universal-XML-Scraper#95]
2.0.0.8 was working just fine for me up until today and I started getting an error related to the systemlist.xml.

[21:31:21] - /!\ _XML_Load @error:
@error description:
$XML_ERR_LOAD=13
Error opening specified file.

@extended description:
$XML_EXT_DEFAULT=0
Default - Do not return any additional information

So I upgraded to 2.0.0.9 (again) and it just refuses to cooperate. It won't kill ES or reboot. It won't even start hashing games. This is the reason I had been using the last version until today. I've deleted all UXS files and re-downloaded a fresh exe and I get the same result every time. I can point it to roms on my computer and it works just fine.

**Comment by tsarrack** [comment]
2.0.0.9 now errors out on me at startup. 

[08:18:17] - --------------------------------------------------------------------------------
[08:18:17] - /!\ _XML_Load @error:
@error description:
$XML_ERR_PARSE=11
Error: with Parsing objects, .parseError.errorCode=0 Use _XML_ErrorParser_GetDescription() for get details.

@extended description:
$XML_EXT_DEFAULT=0
Default - Do not return any additional information

[08:18:17] - --------------------------------------------------------------------------------

**Comment by Universal-Rom-Tools** [comment]
Sorry for that,

just check : 
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/issues/97
