### ISSUE TITLE
Scraping bug/issues

### ISSUE THREAD

**Issue by trutrax** [Universal-Rom-Tools/Universal-XML-Scraper#96]
Hi there I wanted to first and foremost thank you for creating this program that finally allows both screenshot and cases to be shown. 

I come to you with a problem and question that I'm hoping can be easily solved. I've been wracking my brain trying to get this scraper to work properly on my Psx and Nes collection. Snes and others worked flawless, but just recently the scrape job on psx and nes is anything but.

The issue is, It seems to be going completely random on which roms it recognizes and will often scrape only partial elements such as the background but no case (even though there is one on the database website). I'll run it again, and suddenly it will fill in, or get recognized, only to take away another or remove it entirely from the list! The problem then arises where the gamelist.xml goes strange and even games that got properly scrapped the second or third go around still no longer show up once browsing in emulationstation. 

My question is, is this a server instability issue? any suggestions? I'm about to throw in the towel on this one after trying multiple versions, al sorts of different settings, etc. 

thanks very much,
-AM﻿

**Comment by trutrax** [comment]
As an update, I can no longer open the program as I get an error "Universal XML Scraper fatal error! (Problem connecting to the database)" Welp. :/

**Comment by Universal-Rom-Tools** [comment]
Sorry for that, just check here : 
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/issues/97

**Comment by Universal-Rom-Tools** [comment]
Same issue as #97
no news in 10 days...  I close the issue
