### ISSUE TITLE
Unable to scrape any game

### ISSUE THREAD

**Issue by Raphyy** [Universal-Rom-Tools/Universal-XML-Scraper#98]
Hello,

I am not able to scrape any game: it seems that UXS does not recognize games.

Here is the log files:
[log.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/673182/log.txt)
[log1.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/673183/log1.txt)
[_NES_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/673185/_NES_missing.txt)

Please keep me updated if you have any solution to fix this !

Thanks.

**Comment by giventofly** [comment]
http://pastebin.com/epmd7SV7

**Comment by Raphyy** [comment]
I'm not sure to get your point...
Can you explain it to me :)

**Comment by giventofly** [comment]
sorry, forgot to put the rest of the text :D

happening the same here

**Comment by Raphyy** [comment]
Oh ok! Wait'n See then... and I hope we'll get a reply soon ;)

**Comment by Raphyy** [comment]
Problem solved for me: it was probably due to the down DB.
