### ISSUE TITLE
[suggestion] standard3 - mix profile - expand the "background"

### ISSUE THREAD

**Issue by giventofly** [Universal-Rom-Tools/Universal-XML-Scraper#99]
In the 3d standard Mix can the background be full instead of shrinked to be more centered with the art box + name?

**Comment by Universal-Rom-Tools** [comment]
All is possible with MIX ;)

You can check the Tuto to make New MIX template

https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/wiki/%5BTUTO%5D-Making-a-MIX-Template

But you just have to change the config.xml in the 3img : 
Look for the elements named : "ScreenTEMP"
and modify Target_width and Target_Height to %1 and it's done ;)
